// ══════════════════════════════════════════════════════════════════════════════
// CARA — PRACTICE QUALITY INTELLIGENCE API ROUTE
// GET /api/v1/practice-quality-intelligence
//
// Surfaces practice quality assessments generated by Cara — per-child domain
// scores, weakest practice areas, and manager review status.
//
// CHR 2015 Reg 45 (evidence of practice quality), SCCIF practice quality
// standard. Supports the RM's quality assurance role and evidences that
// Cara's assessments are actioned and reviewed.
// ══════════════════════════════════════════════════════════════════════════════

export const dynamic = "force-dynamic";

import { NextResponse } from "next/server";
import { getStore } from "@/lib/db/store";

type PracticeSignal = "concern" | "attention" | "good";

type DomainScore = {
  domain: string;
  label: string;
  score: number;
  signal: PracticeSignal;
};

type PracticeAssessment = {
  id: string;
  sourceType: string;
  status: string;
  overallScore: number;
  createdBy: string;
  createdAt: string;
  summary: string;
  domainScores: DomainScore[];
  hasManagerDecision: boolean;
  managerDecision: string | null;
};

type ChildPracticeProfile = {
  childId: string;
  childName: string;
  signal: PracticeSignal;
  assessmentCount: number;
  openCount: number;
  latestOverallScore: number | null;
  weakestDomains: DomainScore[];
  assessments: PracticeAssessment[];
};

type PracticeQualitySummary = {
  totalAssessments: number;
  openAssessments: number;
  awaitingManagerReview: number;
  avgOverallScore: number | null;
  childrenAtConcern: number;
  childrenAtAttention: number;
  overallSignal: PracticeSignal;
};

type PracticeQualityResponse = {
  profiles: ChildPracticeProfile[];
  summary: PracticeQualitySummary;
};

const DOMAIN_LABELS: Record<string, string> = {
  developmental_gap_score: "Developmental awareness",
  child_lived_experience_score: "Child's lived experience",
  protective_factor_score: "Protective factors",
  relationship_depth_score: "Relationship depth",
  safeguarding_threshold_score: "Safeguarding threshold",
  supervision_quality_score: "Supervision quality",
  workforce_wellbeing_score: "Workforce wellbeing",
};

const SCORE_DOMAINS = [
  "developmental_gap_score",
  "child_lived_experience_score",
  "protective_factor_score",
  "relationship_depth_score",
  "safeguarding_threshold_score",
  "supervision_quality_score",
  "workforce_wellbeing_score",
];

function scoreSignal(score: number): PracticeSignal {
  if (score < 40) return "concern";
  if (score < 65) return "attention";
  return "good";
}

function childPracticeSignal(
  assessments: PracticeAssessment[],
  openCount: number
): PracticeSignal {
  const openWithoutReview = assessments.filter(
    (a) => a.status === "open" && !a.hasManagerDecision
  );
  const anyWeakDomain = assessments.some((a) =>
    a.domainScores.some((d) => d.signal === "concern")
  );
  const anyAttentionDomain = assessments.some((a) =>
    a.domainScores.some((d) => d.signal === "attention")
  );

  if (anyWeakDomain || openWithoutReview.length > 0) return "concern";
  if (anyAttentionDomain || openCount > 0) return "attention";
  return "good";
}

export async function GET() {
  const store = getStore();

  // ── Child name map ──────────────────────────────────────────────────────────
  const ypMap = new Map(
    ((store.youngPeople as any[]) ?? []).map((yp: any) => [
      yp.id,
      yp.preferred_name ??
        (`${yp.first_name ?? ""} ${yp.last_name ?? ""}`.trim() || "Unknown"),
    ])
  );

  // ── Staff name map ──────────────────────────────────────────────────────────
  const staffMap = new Map(
    ((store.staff as any[]) ?? []).map((s: any) => [
      s.id,
      s.full_name ?? (`${s.first_name ?? ""} ${s.last_name ?? ""}`.trim() || s.id),
    ])
  );

  // ── Parse assessments ─────────────────────────────────────────────────────
  const assessmentsByChild = new Map<string, any[]>();
  for (const a of (store.caraPracticeAssessments as any[]) ?? []) {
    if (!a.child_id) continue;
    const list = assessmentsByChild.get(a.child_id) ?? [];
    list.push(a);
    assessmentsByChild.set(a.child_id, list);
  }

  // ── Build per-child profiles ───────────────────────────────────────────────
  const profiles: ChildPracticeProfile[] = [];
  let totalAssessments = 0;
  let openAssessments = 0;
  let awaitingManagerReview = 0;
  let scoreSum = 0;
  let scoreCount = 0;

  for (const [childId, rawList] of assessmentsByChild.entries()) {
    const childName = ypMap.get(childId) ?? childId;

    const parsedAssessments: PracticeAssessment[] = rawList
      .sort((a: any, b: any) =>
        String(b.created_at ?? "").localeCompare(String(a.created_at ?? ""))
      )
      .map((a: any) => {
        const domainScores: DomainScore[] = SCORE_DOMAINS.map((key) => ({
          domain: key,
          label: DOMAIN_LABELS[key] ?? key,
          score: typeof a[key] === "number" ? a[key] : 100,
          signal: scoreSignal(typeof a[key] === "number" ? a[key] : 100),
        }));

        return {
          id: a.id ?? "",
          sourceType: a.source_type ?? "unknown",
          status: a.status ?? "open",
          overallScore:
            typeof a.overall_practice_quality_score === "number"
              ? a.overall_practice_quality_score
              : 0,
          createdBy:
            staffMap.get(a.created_by) ?? a.created_by ?? "Unknown",
          createdAt: String(a.created_at ?? "").slice(0, 10),
          summary: a.summary ?? "",
          domainScores,
          hasManagerDecision: !!(a.manager_decision),
          managerDecision: a.manager_decision ?? null,
        };
      });

    const openList = parsedAssessments.filter((a) => a.status === "open");
    const withoutReview = openList.filter((a) => !a.hasManagerDecision);

    totalAssessments += parsedAssessments.length;
    openAssessments += openList.length;
    awaitingManagerReview += withoutReview.length;

    for (const a of parsedAssessments) {
      if (a.overallScore > 0) {
        scoreSum += a.overallScore;
        scoreCount++;
      }
    }

    const latestOverallScore =
      parsedAssessments.length > 0 ? parsedAssessments[0].overallScore : null;

    // Weakest domains across all assessments (score < 65)
    const allDomains = parsedAssessments.flatMap((a) =>
      a.domainScores.filter((d) => d.signal !== "good")
    );
    // Deduplicate by domain key, take lowest score
    const weakMap = new Map<string, DomainScore>();
    for (const d of allDomains) {
      const existing = weakMap.get(d.domain);
      if (!existing || d.score < existing.score) weakMap.set(d.domain, d);
    }
    const weakestDomains = [...weakMap.values()].sort(
      (a, b) => a.score - b.score
    );

    profiles.push({
      childId,
      childName,
      signal: childPracticeSignal(parsedAssessments, openList.length),
      assessmentCount: parsedAssessments.length,
      openCount: openList.length,
      latestOverallScore,
      weakestDomains,
      assessments: parsedAssessments,
    });
  }

  // Sort: concern → attention → good
  const ORDER: Record<PracticeSignal, number> = {
    concern: 0,
    attention: 1,
    good: 2,
  };
  profiles.sort((a, b) => ORDER[a.signal] - ORDER[b.signal]);

  const childrenAtConcern = profiles.filter(
    (p) => p.signal === "concern"
  ).length;
  const childrenAtAttention = profiles.filter(
    (p) => p.signal === "attention"
  ).length;
  const overallSignal: PracticeSignal =
    childrenAtConcern > 0
      ? "concern"
      : childrenAtAttention > 0
      ? "attention"
      : "good";

  const response: PracticeQualityResponse = {
    profiles,
    summary: {
      totalAssessments,
      openAssessments,
      awaitingManagerReview,
      avgOverallScore: scoreCount > 0 ? Math.round(scoreSum / scoreCount) : null,
      childrenAtConcern,
      childrenAtAttention,
      overallSignal,
    },
  };

  return NextResponse.json({ data: response });
}
