// ══════════════════════════════════════════════════════════════════════════════
// CORNERSTONE — SEED DATA
// Real Oak House staff data, realistic care home scenarios
// ══════════════════════════════════════════════════════════════════════════════

import type {
  StaffMember, YoungPerson, Task, Incident, Shift, LeaveRequest,
  TrainingRecord, Supervision, Medication, MedicationAdministration,
  DailyLogEntry, Expense, Candidate, Document, Home,
} from "@/types";
import { daysFromNow, todayStr, generateId } from "./utils";

const today = todayStr();
const yesterday = daysFromNow(-1);
const twoDaysAgo = daysFromNow(-2);
const threeDaysAgo = daysFromNow(-3);
const tomorrow = daysFromNow(1);
const inTwoDays = daysFromNow(2);
const inThreeDays = daysFromNow(3);
const inFiveDays = daysFromNow(5);
const nextWeek = daysFromNow(7);
const inTwoWeeks = daysFromNow(14);
const inThirtyDays = daysFromNow(30);
const lastMonth = daysFromNow(-30);
const twoMonthsAgo = daysFromNow(-60);

const now = new Date().toISOString();
const hoursAgo = (n: number) => new Date(Date.now() - n * 3600000).toISOString();

// ── Home ─────────────────────────────────────────────────────────────────────

export const HOME: Home = {
  id: "home_oak",
  name: "Oak House",
  address: "Oak House, Derby, DE1 3AA",
  phone: "01332 000 000",
  ofsted_urn: "SC123456",
  registered_manager_id: "staff_darren",
  responsible_individual_id: "staff_alicia",
  max_beds: 3,
  current_occupancy: 3,
  last_inspection_date: "2025-10-15",
  last_inspection_grade: "Good",
  created_at: "2025-01-01T00:00:00Z",
};

// ── Staff ────────────────────────────────────────────────────────────────────

const base = { created_at: now, updated_at: now, created_by: "system", updated_by: "system", home_id: "home_oak", is_active: true, avatar_url: null };

export const STAFF: StaffMember[] = [
  { ...base, id: "staff_darren", first_name: "Darren", last_name: "Laville", full_name: "Darren Laville", email: "darren@acaciatherapyhomes.org", phone: "07700 000001", role: "registered_manager", job_title: "Registered Manager", employment_type: "permanent", employment_status: "active", start_date: "2024-03-01", end_date: null, probation_end_date: null, contracted_hours: 40, hourly_rate: null, annual_salary: 38000, payroll_id: "0013", dbs_number: "DBS001234", dbs_issue_date: "2024-02-01", dbs_update_service: true, emergency_contact_name: null, emergency_contact_phone: null, next_supervision_due: inTwoWeeks, next_appraisal_due: daysFromNow(90) },
  { ...base, id: "staff_ryan", first_name: "Ryan", last_name: "Forsythe", full_name: "Ryan Forsythe", email: "ryan@acaciatherapyhomes.org", phone: "07700 000002", role: "deputy_manager", job_title: "Deputy Manager", employment_type: "permanent", employment_status: "active", start_date: "2024-06-15", end_date: null, probation_end_date: null, contracted_hours: 40, hourly_rate: null, annual_salary: 32000, payroll_id: "0012", dbs_number: "DBS001235", dbs_issue_date: "2024-05-01", dbs_update_service: true, emergency_contact_name: "Jane Forsythe", emergency_contact_phone: "07700 100002", next_supervision_due: inThreeDays, next_appraisal_due: daysFromNow(60) },
  { ...base, id: "staff_alicia", first_name: "Alicia", last_name: "Clarkson", full_name: "Alicia Clarkson", email: "alicia@acaciatherapyhomes.org", phone: "07700 000003", role: "responsible_individual", job_title: "Responsible Individual", employment_type: "permanent", employment_status: "active", start_date: "2023-01-01", end_date: null, probation_end_date: null, contracted_hours: 0, hourly_rate: null, annual_salary: null, payroll_id: null, dbs_number: "DBS001000", dbs_issue_date: "2023-01-01", dbs_update_service: true, emergency_contact_name: null, emergency_contact_phone: null, next_supervision_due: null, next_appraisal_due: null },
  { ...base, id: "staff_edward", first_name: "Edward", last_name: "Fitzpatrick", full_name: "Edward Fitzpatrick", email: "edwardfitzpatrick1@outlook.com", phone: "07700 000004", role: "residential_care_worker", job_title: "Residential Care Worker", employment_type: "permanent", employment_status: "active", start_date: "2024-09-01", end_date: null, probation_end_date: null, contracted_hours: 37.5, hourly_rate: 12.50, annual_salary: null, payroll_id: "0007", dbs_number: "DBS002001", dbs_issue_date: "2024-08-01", dbs_update_service: false, emergency_contact_name: "Mary Fitzpatrick", emergency_contact_phone: "07700 200004", next_supervision_due: tomorrow, next_appraisal_due: daysFromNow(45) },
  { ...base, id: "staff_lackson", first_name: "Lackson", last_name: "Phiri", full_name: "Lackson Phiri", email: "lackieagle@gmail.com", phone: "07700 000005", role: "residential_care_worker", job_title: "Residential Care Worker", employment_type: "permanent", employment_status: "active", start_date: "2024-07-01", end_date: null, probation_end_date: null, contracted_hours: 37.5, hourly_rate: 12.50, annual_salary: null, payroll_id: "0008", dbs_number: "DBS002002", dbs_issue_date: "2024-06-15", dbs_update_service: false, emergency_contact_name: "Grace Phiri", emergency_contact_phone: "07700 200005", next_supervision_due: nextWeek, next_appraisal_due: daysFromNow(75) },
  { ...base, id: "staff_anna", first_name: "Anna", last_name: "Lingolo", full_name: "Anna Lingolo", email: null, phone: "07700 000006", role: "residential_care_worker", job_title: "Residential Care Worker", employment_type: "permanent", employment_status: "active", start_date: "2024-04-01", end_date: null, probation_end_date: null, contracted_hours: 37.5, hourly_rate: 12.50, annual_salary: null, payroll_id: "0001", dbs_number: "DBS002003", dbs_issue_date: "2024-03-15", dbs_update_service: false, emergency_contact_name: null, emergency_contact_phone: null, next_supervision_due: inFiveDays, next_appraisal_due: daysFromNow(30) },
  { ...base, id: "staff_diane", first_name: "Diane", last_name: "Ugbogbo", full_name: "Diane Ugbogbo", email: "u.diane0903@gmail.com", phone: "07700 000007", role: "residential_care_worker", job_title: "Residential Care Worker", employment_type: "permanent", employment_status: "active", start_date: "2025-01-15", end_date: null, probation_end_date: daysFromNow(45), contracted_hours: 37.5, hourly_rate: 12.00, annual_salary: null, payroll_id: "0006", dbs_number: "DBS002004", dbs_issue_date: "2025-01-01", dbs_update_service: false, emergency_contact_name: "Frank Ugbogbo", emergency_contact_phone: "07700 200007", next_supervision_due: inTwoDays, next_appraisal_due: null },
  { ...base, id: "staff_mirela", first_name: "Mirela", last_name: "Tshawa Kalongo", full_name: "Mirela Tshawa Kalongo", email: "mirratk19@gmail.com", phone: "07700 000008", role: "residential_care_worker", job_title: "Residential Care Worker", employment_type: "permanent", employment_status: "active", start_date: "2025-02-01", end_date: null, probation_end_date: daysFromNow(60), contracted_hours: 37.5, hourly_rate: 12.00, annual_salary: null, payroll_id: "0011", dbs_number: "DBS002005", dbs_issue_date: "2025-01-20", dbs_update_service: false, emergency_contact_name: null, emergency_contact_phone: null, next_supervision_due: nextWeek, next_appraisal_due: null },
  { ...base, id: "staff_alex", first_name: "Alex", last_name: "Bennett", full_name: "Alex Bennett", email: "alexrileyhart@gmail.com", phone: "07700 000009", role: "residential_care_worker", job_title: "Residential Care Worker", employment_type: "permanent", employment_status: "active", start_date: "2025-03-01", end_date: null, probation_end_date: daysFromNow(120), contracted_hours: 37.5, hourly_rate: 12.00, annual_salary: null, payroll_id: "0015", dbs_number: "DBS002006", dbs_issue_date: "2025-02-15", dbs_update_service: false, emergency_contact_name: "Sarah Bennett", emergency_contact_phone: "07700 200009", next_supervision_due: inTwoDays, next_appraisal_due: null },
  { ...base, id: "staff_chervelle", first_name: "Chervelle", last_name: "Kinina", full_name: "Chervelle Kinina", email: null, phone: "07700 000010", role: "residential_care_worker", job_title: "Residential Care Worker", employment_type: "permanent", employment_status: "active", start_date: "2025-01-01", end_date: null, probation_end_date: null, contracted_hours: 37.5, hourly_rate: 12.50, annual_salary: null, payroll_id: "0019", dbs_number: "DBS002007", dbs_issue_date: "2024-12-15", dbs_update_service: false, emergency_contact_name: null, emergency_contact_phone: null, next_supervision_due: inFiveDays, next_appraisal_due: daysFromNow(90) },
  { ...base, id: "staff_bianca", first_name: "Bianca", last_name: "Dowe", full_name: "Bianca Dowe", email: null, phone: "07700 000011", role: "bank_staff", job_title: "Bank Staff", employment_type: "bank", employment_status: "active", start_date: "2025-06-01", end_date: null, probation_end_date: null, contracted_hours: 0, hourly_rate: 13.00, annual_salary: null, payroll_id: "0014", dbs_number: "DBS003001", dbs_issue_date: "2025-05-15", dbs_update_service: false, emergency_contact_name: null, emergency_contact_phone: null, next_supervision_due: inThirtyDays, next_appraisal_due: null },
  { ...base, id: "staff_ryan_r", first_name: "Ryan", last_name: "Ramsey", full_name: "Ryan Ramsey", email: "rwramsey92@gmail.com", phone: "07700 000012", role: "bank_staff", job_title: "Bank Staff", employment_type: "bank", employment_status: "active", start_date: "2025-07-01", end_date: null, probation_end_date: null, contracted_hours: 0, hourly_rate: 13.00, annual_salary: null, payroll_id: "0016", dbs_number: "DBS003002", dbs_issue_date: "2025-06-20", dbs_update_service: false, emergency_contact_name: null, emergency_contact_phone: null, next_supervision_due: inThirtyDays, next_appraisal_due: null },
];

// ── Young People ─────────────────────────────────────────────────────────────

export const YOUNG_PEOPLE: YoungPerson[] = [
  { ...base, id: "yp_alex", first_name: "Alex", last_name: "W", preferred_name: "Alex", date_of_birth: "2010-03-14", gender: "Male", ethnicity: "White British", religion: null, placement_start: "2025-09-01", placement_end: null, placement_type: "Full-time residential", local_authority: "Derby City Council", social_worker_name: "Karen Holding", social_worker_phone: "01332 641 700", social_worker_email: "karen.holding@derby.gov.uk", iro_name: "James Patterson", iro_phone: "01332 641 800", key_worker_id: "staff_edward", secondary_worker_id: "staff_lackson", legal_status: "Section 20", risk_flags: ["missing from care", "self-harm", "exploitation concern"], dietary_requirements: null, allergies: [], gp_name: "Dr. S. Patel", gp_phone: "01332 500 100", school_name: "Derby Alternative Provision", school_contact: "01332 600 200", photo_url: null, status: "current" },
  { ...base, id: "yp_jordan", first_name: "Jordan", last_name: "M", preferred_name: "Jordan", date_of_birth: "2011-08-22", gender: "Male", ethnicity: "Black British", religion: null, placement_start: "2025-11-15", placement_end: null, placement_type: "Full-time residential", local_authority: "Nottinghamshire County Council", social_worker_name: "Michael Osei", social_worker_phone: "0115 977 3100", social_worker_email: "michael.osei@nottscc.gov.uk", iro_name: "Ruth Chambers", iro_phone: "0115 977 3200", key_worker_id: "staff_anna", secondary_worker_id: "staff_mirela", legal_status: "Section 31 (Full Care Order)", risk_flags: [], dietary_requirements: "Halal", allergies: ["Penicillin"], gp_name: "Dr. A. Khan", gp_phone: "01332 500 200", school_name: "Highfields Academy", school_contact: "01332 600 300", photo_url: null, status: "current" },
  { ...base, id: "yp_casey", first_name: "Casey", last_name: "T", preferred_name: "Casey", date_of_birth: "2009-12-05", gender: "Female", ethnicity: "Mixed Heritage", religion: null, placement_start: "2026-01-10", placement_end: null, placement_type: "Full-time residential", local_authority: "Derbyshire County Council", social_worker_name: "Fiona Brennan", social_worker_phone: "01629 533 190", social_worker_email: "fiona.brennan@derbyshire.gov.uk", iro_name: "Sarah Mitchell", iro_phone: "01629 533 200", key_worker_id: "staff_chervelle", secondary_worker_id: "staff_diane", legal_status: "Section 31 (Full Care Order)", risk_flags: ["medication refusal", "sleep disturbance"], dietary_requirements: "Vegetarian", allergies: ["Nuts"], gp_name: "Dr. L. Chen", gp_phone: "01332 500 300", school_name: "Allestree Woodlands", school_contact: "01332 600 400", photo_url: null, status: "current" },
];

// ── Today's Shifts ───────────────────────────────────────────────────────────

export const SHIFTS: Shift[] = [
  { ...base, id: "shift_001", staff_id: "staff_darren", date: today, shift_type: "day", start_time: "08:00", end_time: "17:00", break_minutes: 60, actual_start: "07:55", actual_end: null, clock_in_at: hoursAgo(5), clock_out_at: null, overtime_minutes: 0, notes: null, status: "in_progress", is_open_shift: false },
  { ...base, id: "shift_002", staff_id: "staff_ryan", date: today, shift_type: "day", start_time: "08:00", end_time: "17:00", break_minutes: 60, actual_start: "08:02", actual_end: null, clock_in_at: hoursAgo(5), clock_out_at: null, overtime_minutes: 0, notes: null, status: "in_progress", is_open_shift: false },
  { ...base, id: "shift_003", staff_id: "staff_edward", date: today, shift_type: "day", start_time: "07:00", end_time: "22:00", break_minutes: 60, actual_start: "06:58", actual_end: null, clock_in_at: hoursAgo(6), clock_out_at: null, overtime_minutes: 0, notes: null, status: "in_progress", is_open_shift: false },
  { ...base, id: "shift_004", staff_id: "staff_anna", date: today, shift_type: "sleep_in", start_time: "22:00", end_time: "07:00", break_minutes: 0, actual_start: null, actual_end: null, clock_in_at: null, clock_out_at: null, overtime_minutes: 0, notes: null, status: "scheduled", is_open_shift: false },
  { ...base, id: "shift_005", staff_id: "staff_lackson", date: today, shift_type: "day", start_time: "10:00", end_time: "20:00", break_minutes: 30, actual_start: "10:05", actual_end: null, clock_in_at: hoursAgo(3), clock_out_at: null, overtime_minutes: 0, notes: "Late — traffic delay, called ahead", status: "in_progress", is_open_shift: false },
  { ...base, id: "shift_006", staff_id: "staff_chervelle", date: today, shift_type: "sleep_in", start_time: "22:00", end_time: "07:00", break_minutes: 0, actual_start: null, actual_end: null, clock_in_at: null, clock_out_at: null, overtime_minutes: 0, notes: null, status: "scheduled", is_open_shift: false },
  // Tomorrow open shift
  { ...base, id: "shift_007", staff_id: "", date: tomorrow, shift_type: "day", start_time: "07:00", end_time: "15:00", break_minutes: 30, actual_start: null, actual_end: null, clock_in_at: null, clock_out_at: null, overtime_minutes: 0, notes: "OPEN — Diane called in sick", status: "scheduled", is_open_shift: true },
  // Yesterday completed
  { ...base, id: "shift_008", staff_id: "staff_diane", date: yesterday, shift_type: "day", start_time: "08:00", end_time: "20:00", break_minutes: 60, actual_start: "08:00", actual_end: "20:15", clock_in_at: daysFromNow(-1) + "T08:00:00Z", clock_out_at: daysFromNow(-1) + "T20:15:00Z", overtime_minutes: 15, notes: null, status: "completed", is_open_shift: false },
];

// ── Tasks (full set for dashboard) ───────────────────────────────────────────

const tb = { ...base, evidence_files: [], escalated: false, escalated_to: null, escalated_at: null, escalation_reason: null, linked_document_id: null, parent_task_id: null, tags: [] };

export const TASKS: Task[] = [
  // OVERDUE
  { ...tb, id: "task_001", title: "Complete Reg 44 action plan responses", description: "Three actions from the February Reg 44 visit still need written responses with evidence.", category: "compliance", priority: "urgent", status: "in_progress", assigned_to: "staff_darren", assigned_role: "registered_manager", due_date: twoDaysAgo, start_date: threeDaysAgo, completed_at: null, completed_by: null, estimated_minutes: 90, actual_minutes: null, recurring: false, recurring_schedule: null, requires_sign_off: false, signed_off_by: null, signed_off_at: null, evidence_note: null, linked_child_id: null, linked_incident_id: null },
  { ...tb, id: "task_002", title: "Safeguarding log oversight — two entries pending", description: "Entries from Sunday and Monday need RM oversight comments. One involves a repeat missing pattern for Alex, another is a safeguarding disclosure.", category: "safeguarding", priority: "urgent", status: "not_started", assigned_to: "staff_darren", assigned_role: "registered_manager", due_date: yesterday, start_date: null, completed_at: null, completed_by: null, estimated_minutes: 30, actual_minutes: null, recurring: false, recurring_schedule: null, requires_sign_off: false, signed_off_by: null, signed_off_at: null, evidence_note: null, linked_child_id: "yp_alex", linked_incident_id: "inc_004" },
  { ...tb, id: "task_003", title: "Chase GDPR e-learning completion — three staff overdue", description: "Edward, Anna, and a bank worker have not completed the refresher module. Deadline was last Friday.", category: "training", priority: "high", status: "not_started", assigned_to: "staff_ryan", assigned_role: "deputy_manager", due_date: twoDaysAgo, start_date: null, completed_at: null, completed_by: null, estimated_minutes: 30, actual_minutes: null, recurring: false, recurring_schedule: null, requires_sign_off: false, signed_off_by: null, signed_off_at: null, evidence_note: null, linked_child_id: null, linked_incident_id: null },
  { ...tb, id: "task_004", title: "Medication audit — March MAR sheet discrepancies", description: "Two medication events found in the March MAR audit. One late administration for Casey, one recording gap.", category: "medication", priority: "urgent", status: "in_progress", assigned_to: "staff_ryan", assigned_role: "deputy_manager", due_date: yesterday, start_date: twoDaysAgo, completed_at: null, completed_by: null, estimated_minutes: 60, actual_minutes: null, recurring: false, recurring_schedule: null, requires_sign_off: true, signed_off_by: null, signed_off_at: null, evidence_note: null, linked_child_id: "yp_casey", linked_incident_id: "inc_002" },

  // DUE TODAY
  { ...tb, id: "task_005", title: "Daily walkround and premises check", description: "Inspect all communal areas, bedrooms (with consent), kitchen, laundry, outside space. Log findings.", category: "health_and_safety", priority: "high", status: "not_started", assigned_to: "staff_chervelle", assigned_role: "residential_care_worker", due_date: today, start_date: null, completed_at: null, completed_by: null, estimated_minutes: 45, actual_minutes: null, recurring: true, recurring_schedule: "daily", requires_sign_off: false, signed_off_by: null, signed_off_at: null, evidence_note: null, linked_child_id: null, linked_incident_id: null },
  { ...tb, id: "task_006", title: "Supervision session — Anna Lingolo", description: "Scheduled 1:1 supervision. Cover recent incident response, training needs, and wellbeing.", category: "supervision", priority: "high", status: "not_started", assigned_to: "staff_ryan", assigned_role: "deputy_manager", due_date: today, start_date: null, completed_at: null, completed_by: null, estimated_minutes: 60, actual_minutes: null, recurring: false, recurring_schedule: null, requires_sign_off: true, signed_off_by: null, signed_off_at: null, evidence_note: null, linked_child_id: null, linked_incident_id: null },
  { ...tb, id: "task_007", title: "Update Alex placement plan — risk section", description: "Social worker requested updated risk section following missing from care incidents and safeguarding disclosure.", category: "young_person_plans", priority: "high", status: "in_progress", assigned_to: "staff_darren", assigned_role: "registered_manager", due_date: today, start_date: yesterday, completed_at: null, completed_by: null, estimated_minutes: 45, actual_minutes: null, recurring: false, recurring_schedule: null, requires_sign_off: false, signed_off_by: null, signed_off_at: null, evidence_note: null, linked_child_id: "yp_alex", linked_incident_id: "inc_001" },
  { ...tb, id: "task_008", title: "Call Jordan's LA — placement review date", description: "Confirm the date for the next LAC review and ensure all reports are submitted on time.", category: "professional_communication", priority: "medium", status: "not_started", assigned_to: "staff_darren", assigned_role: "registered_manager", due_date: today, start_date: null, completed_at: null, completed_by: null, estimated_minutes: 20, actual_minutes: null, recurring: false, recurring_schedule: null, requires_sign_off: false, signed_off_by: null, signed_off_at: null, evidence_note: null, linked_child_id: "yp_jordan", linked_incident_id: null },
  { ...tb, id: "task_009", title: "Submit weekly incident summary to RI", description: "Compile and email the weekly incident summary covering all logged incidents.", category: "compliance", priority: "medium", status: "not_started", assigned_to: "staff_diane", assigned_role: "residential_care_worker", due_date: today, start_date: null, completed_at: null, completed_by: null, estimated_minutes: 40, actual_minutes: null, recurring: true, recurring_schedule: "weekly", requires_sign_off: true, signed_off_by: null, signed_off_at: null, evidence_note: null, linked_child_id: null, linked_incident_id: null },
  { ...tb, id: "task_010", title: "Strategy discussion follow-up — Alex safeguarding", description: "Following yesterday's disclosure, attend strategy discussion with social worker and police. Prepare chronology.", category: "safeguarding", priority: "urgent", status: "not_started", assigned_to: "staff_darren", assigned_role: "registered_manager", due_date: today, start_date: null, completed_at: null, completed_by: null, estimated_minutes: 90, actual_minutes: null, recurring: false, recurring_schedule: null, requires_sign_off: false, signed_off_by: null, signed_off_at: null, evidence_note: null, linked_child_id: "yp_alex", linked_incident_id: "inc_004" },

  // UPCOMING
  { ...tb, id: "task_011", title: "Prepare staff rota for next two weeks", description: "Cover bank holiday weekend. Check leave requests and agency availability.", category: "staffing", priority: "high", status: "not_started", assigned_to: "staff_ryan", assigned_role: "deputy_manager", due_date: inTwoDays, start_date: null, completed_at: null, completed_by: null, estimated_minutes: 90, actual_minutes: null, recurring: false, recurring_schedule: null, requires_sign_off: true, signed_off_by: null, signed_off_at: null, evidence_note: null, linked_child_id: null, linked_incident_id: null },
  { ...tb, id: "task_012", title: "Weekly medication audit", description: "Audit all MAR sheets, PRN records, stock levels, and controlled drug register.", category: "medication", priority: "high", status: "not_started", assigned_to: "staff_ryan", assigned_role: "deputy_manager", due_date: inThreeDays, start_date: null, completed_at: null, completed_by: null, estimated_minutes: 45, actual_minutes: null, recurring: true, recurring_schedule: "weekly", requires_sign_off: true, signed_off_by: null, signed_off_at: null, evidence_note: null, linked_child_id: null, linked_incident_id: null },
  { ...tb, id: "task_013", title: "Fire drill — quarterly scheduled", description: "Coordinate with all staff. Complete fire drill report and log.", category: "health_and_safety", priority: "high", status: "not_started", assigned_to: "staff_chervelle", assigned_role: "residential_care_worker", due_date: inFiveDays, start_date: null, completed_at: null, completed_by: null, estimated_minutes: 60, actual_minutes: null, recurring: false, recurring_schedule: null, requires_sign_off: true, signed_off_by: null, signed_off_at: null, evidence_note: null, linked_child_id: null, linked_incident_id: null },
  { ...tb, id: "task_014", title: "Casey key work session — medication and routine", description: "Planned key work session to discuss morning routine, medication compliance, and sleep concerns.", category: "young_person_plans", priority: "medium", status: "not_started", assigned_to: "staff_chervelle", assigned_role: "residential_care_worker", due_date: inTwoDays, start_date: null, completed_at: null, completed_by: null, estimated_minutes: 45, actual_minutes: null, recurring: false, recurring_schedule: null, requires_sign_off: false, signed_off_by: null, signed_off_at: null, evidence_note: null, linked_child_id: "yp_casey", linked_incident_id: null },

  // COMPLETED TODAY
  { ...tb, id: "task_015", title: "Morning handover review and sign-off", description: "Reviewed night shift handover. Casey sleep pattern concern noted for follow-up.", category: "compliance", priority: "high", status: "completed", assigned_to: "staff_darren", assigned_role: "registered_manager", due_date: today, start_date: today, completed_at: hoursAgo(3), completed_by: "staff_darren", estimated_minutes: 20, actual_minutes: 15, recurring: true, recurring_schedule: "daily", requires_sign_off: false, signed_off_by: null, signed_off_at: null, evidence_note: "Handover reviewed. Casey sleep pattern concern noted — flagged for key work session.", linked_child_id: "yp_casey", linked_incident_id: null },
  { ...tb, id: "task_016", title: "Check shift coverage for today", description: "Confirmed all shifts covered. Lackson late but called ahead.", category: "staffing", priority: "high", status: "completed", assigned_to: "staff_ryan", assigned_role: "deputy_manager", due_date: today, start_date: today, completed_at: hoursAgo(4), completed_by: "staff_ryan", estimated_minutes: 15, actual_minutes: 10, recurring: true, recurring_schedule: "daily", requires_sign_off: false, signed_off_by: null, signed_off_at: null, evidence_note: "Full coverage confirmed. Lackson late — traffic, called ahead.", linked_child_id: null, linked_incident_id: null },
  { ...tb, id: "task_017", title: "Respond to social worker email — Alex contact arrangements", description: "Confirmed contact schedule for the next fortnight with Karen Holding.", category: "professional_communication", priority: "medium", status: "completed", assigned_to: "staff_darren", assigned_role: "registered_manager", due_date: today, start_date: today, completed_at: hoursAgo(2), completed_by: "staff_darren", estimated_minutes: 20, actual_minutes: 15, recurring: false, recurring_schedule: null, requires_sign_off: false, signed_off_by: null, signed_off_at: null, evidence_note: "Email sent. Contact confirmed for Tuesday and Friday.", linked_child_id: "yp_alex", linked_incident_id: null },

  // BLOCKED
  { ...tb, id: "task_018", title: "Install CCTV camera — rear garden", description: "Approved by RI but waiting on contractor availability. Chased twice.", category: "maintenance", priority: "high", status: "blocked", assigned_to: "staff_diane", assigned_role: "residential_care_worker", due_date: yesterday, start_date: threeDaysAgo, completed_at: null, completed_by: null, estimated_minutes: 15, actual_minutes: null, recurring: false, recurring_schedule: null, requires_sign_off: false, signed_off_by: null, signed_off_at: null, evidence_note: null, linked_child_id: null, linked_incident_id: null },
];

// ── Incidents ────────────────────────────────────────────────────────────────

const ib = { ...base, linked_task_ids: [], linked_document_ids: [] };

export const INCIDENTS: Incident[] = [
  { ...ib, id: "inc_001", reference: "INC-2026-0041", type: "missing_from_care", severity: "high", child_id: "yp_alex", date: twoDaysAgo, time: "22:40", location: "Community", description: "Alex returned 90 minutes late from unsupervised community time. No contact during absence. Found at local park. Calm on return, no signs of substance use.", immediate_action: "Welfare check completed on return. Verbal debrief. Parents and social worker informed next morning.", reported_by: "staff_edward", witnesses: ["Lackson Phiri"], body_map_required: false, body_map_completed: false, body_map_url: null, notifications: [{ role: "Social Worker", name: "Karen Holding", method: "Phone", notified_at: daysFromNow(-1) + "T09:15:00Z", acknowledged: true }, { role: "Registered Manager", name: "Darren Laville", method: "Phone", notified_at: twoDaysAgo + "T22:50:00Z", acknowledged: true }], requires_oversight: true, oversight_note: null, oversight_by: null, oversight_at: null, status: "open", outcome: null, lessons_learned: null, linked_task_ids: ["task_002"] },
  { ...ib, id: "inc_002", reference: "INC-2026-0040", type: "medication_error", severity: "medium", child_id: "yp_casey", date: threeDaysAgo, time: "08:15", location: "Medication Room", description: "Morning medication administered 45 minutes late due to Casey refusing initially. Second attempt successful. MAR sheet updated with delay noted.", immediate_action: "Medication administered. Casey monitored for 30 minutes. No adverse effects. Documented on MAR.", reported_by: "staff_anna", witnesses: [], body_map_required: false, body_map_completed: false, body_map_url: null, notifications: [{ role: "Deputy Manager", name: "Ryan Forsythe", method: "In person", notified_at: threeDaysAgo + "T08:30:00Z", acknowledged: true }], requires_oversight: true, oversight_note: "Late administration logged correctly. Staff followed PRN protocol. No harm caused. Pattern of morning refusals noted — review approach with pharmacy and CAMHS.", oversight_by: "staff_darren", oversight_at: twoDaysAgo + "T10:00:00Z", status: "closed", outcome: "No adverse effect. Approach review scheduled.", lessons_learned: "Consider adjusting morning medication timing with prescriber.", linked_task_ids: ["task_004"] },
  { ...ib, id: "inc_003", reference: "INC-2026-0042", type: "complaint", severity: "medium", child_id: "yp_jordan", date: yesterday, time: "14:30", location: "Communal Area", description: "Jordan raised complaint about noise from communal area during study time. Felt staff did not respond quickly enough.", immediate_action: "Jordan listened to and validated. Quiet study space arranged in dining room. Staff spoken to about response times.", reported_by: "staff_chervelle", witnesses: [], body_map_required: false, body_map_completed: false, body_map_url: null, notifications: [], requires_oversight: true, oversight_note: null, oversight_by: null, oversight_at: null, status: "open", outcome: null, lessons_learned: null },
  { ...ib, id: "inc_004", reference: "INC-2026-0043", type: "safeguarding_concern", severity: "critical", child_id: "yp_alex", date: yesterday, time: "19:10", location: "Alex's Room", description: "Alex disclosed to key worker that an older peer in the community has been asking them to carry items. Context suggests potential criminal exploitation risk. Alex became distressed during disclosure.", immediate_action: "Immediate safeguarding response initiated. Alex supported with 1:1 time. Social worker contacted. Risk assessment review booked.", reported_by: "staff_edward", witnesses: [], body_map_required: false, body_map_completed: false, body_map_url: null, notifications: [{ role: "Social Worker", name: "Karen Holding", method: "Phone", notified_at: yesterday + "T19:25:00Z", acknowledged: true }, { role: "Registered Manager", name: "Darren Laville", method: "Phone", notified_at: yesterday + "T19:20:00Z", acknowledged: true }, { role: "Police", name: "MASH referral", method: "Phone", notified_at: yesterday + "T20:00:00Z", acknowledged: false }], requires_oversight: true, oversight_note: null, oversight_by: null, oversight_at: null, status: "open", outcome: null, lessons_learned: null, linked_task_ids: ["task_002", "task_010"] },
  // ── Physical intervention incidents (referenced in Reg 44 Visit 3 findings) ─
  { ...ib, id: "inc_005", reference: "INC-2026-0035", type: "physical_intervention", severity: "high", child_id: "yp_alex", date: daysFromNow(-35), time: "21:15", location: "Communal Lounge", description: "Alex became extremely agitated following a phone call with a family member. Began throwing items and directed verbal threats at staff. When a second staff member attempted to guide Alex away from the area, Alex struck out. A brief planned holding technique (Team Teach approved hold) was used for approximately 3 minutes to prevent injury. Alex de-escalated and was supported to their room.", immediate_action: "PI hold used. Alex supported post-incident with 1:1 time. Body map completed. Social worker notified same evening.", reported_by: "staff_edward", witnesses: ["staff_anna"], body_map_required: true, body_map_completed: true, body_map_url: null, notifications: [{ role: "Registered Manager", name: "Darren Laville", method: "Phone", notified_at: daysFromNow(-35) + "T21:30:00Z", acknowledged: true }, { role: "Social Worker", name: "Karen Holding", method: "Phone", notified_at: daysFromNow(-35) + "T21:45:00Z", acknowledged: true }], requires_oversight: true, oversight_note: "PI reviewed. Hold was proportionate and of minimum duration. Team Teach technique used correctly. Post-incident debrief with Alex and staff to be completed tomorrow.", oversight_by: "staff_darren", oversight_at: daysFromNow(-34) + "T09:00:00Z", status: "closed", outcome: "No injuries sustained. Alex settled. Trigger identified as distressing family contact.", lessons_learned: "Pre-call preparation may reduce escalation risk. Consider keyworker present during contact calls.", linked_task_ids: [] },
  { ...ib, id: "inc_006", reference: "INC-2026-0037", type: "physical_intervention", severity: "high", child_id: "yp_alex", date: daysFromNow(-22), time: "14:50", location: "Upstairs Corridor", description: "Alex ran towards the front door following a refused community trip request. Staff attempted de-escalation but Alex became physically threatening towards a staff member. Team Teach restrictive hold used in the corridor for approximately 2 minutes until Alex verbally agreed to engage with support. No injuries.", immediate_action: "Hold applied and released as soon as safe to do so. Alex supported to room. Body map completed. Notifications made.", reported_by: "staff_chervelle", witnesses: ["staff_ryan"], body_map_required: true, body_map_completed: true, body_map_url: null, notifications: [{ role: "Registered Manager", name: "Darren Laville", method: "Phone", notified_at: daysFromNow(-22) + "T15:05:00Z", acknowledged: true }, { role: "Social Worker", name: "Karen Holding", method: "Phone", notified_at: daysFromNow(-22) + "T15:30:00Z", acknowledged: true }], requires_oversight: true, oversight_note: null, oversight_by: null, oversight_at: null, status: "open", outcome: null, lessons_learned: null, linked_task_ids: [] },
  { ...ib, id: "inc_007", reference: "INC-2026-0039", type: "physical_intervention", severity: "critical", child_id: "yp_alex", date: daysFromNow(-10), time: "18:30", location: "Alex's Bedroom", description: "Alex became violent following a difficult conversation about upcoming court proceedings. Attempted to self-harm with a sharp object. Staff intervened to prevent serious injury — Team Teach wrap hold used. A second staff member called for support. Hold maintained for 7 minutes. Alex sustained a minor bruise to left forearm during the struggle (not caused by the hold). Ambulance called as precaution. Alex assessed and discharged.", immediate_action: "Hold applied, self-harm object secured. Ambulance called. Alex assessed — minor bruise noted on body map. Social worker, parents and RM notified. Post-incident debrief with Alex planned for following day.", reported_by: "staff_ryan", witnesses: ["staff_edward"], body_map_required: true, body_map_completed: true, body_map_url: null, notifications: [{ role: "Registered Manager", name: "Darren Laville", method: "Phone", notified_at: daysFromNow(-10) + "T18:35:00Z", acknowledged: true }, { role: "Social Worker", name: "Karen Holding", method: "Phone", notified_at: daysFromNow(-10) + "T18:40:00Z", acknowledged: true }, { role: "Parent / Carer", name: "Alex's mother", method: "Phone", notified_at: daysFromNow(-10) + "T19:00:00Z", acknowledged: true }, { role: "NHS Ambulance", name: "East Midlands Ambulance Service", method: "999", notified_at: daysFromNow(-10) + "T18:32:00Z", acknowledged: true }], requires_oversight: true, oversight_note: null, oversight_by: null, oversight_at: null, status: "open", outcome: null, lessons_learned: null, linked_task_ids: [] },
];

// ── Training Records ─────────────────────────────────────────────────────────

export const TRAINING_RECORDS: TrainingRecord[] = [
  { ...base, id: "tr_001", staff_id: "staff_edward", course_name: "Safeguarding Level 3", category: "safeguarding", provider: "NSPCC", completed_date: lastMonth, expiry_date: daysFromNow(335), certificate_url: null, status: "compliant", is_mandatory: true, notes: null },
  { ...base, id: "tr_002", staff_id: "staff_edward", course_name: "First Aid at Work", category: "first_aid", provider: "St John Ambulance", completed_date: twoMonthsAgo, expiry_date: daysFromNow(25), certificate_url: null, status: "expiring_soon", is_mandatory: true, notes: "Refresher booked" },
  { ...base, id: "tr_003", staff_id: "staff_anna", course_name: "GDPR Refresher", category: "data_protection", provider: "Online", completed_date: null, expiry_date: twoDaysAgo, certificate_url: null, status: "expired", is_mandatory: true, notes: null },
  { ...base, id: "tr_004", staff_id: "staff_anna", course_name: "First Aid at Work", category: "first_aid", provider: "St John Ambulance", completed_date: twoMonthsAgo, expiry_date: daysFromNow(25), certificate_url: null, status: "expiring_soon", is_mandatory: true, notes: "Refresher booked" },
  { ...base, id: "tr_005", staff_id: "staff_edward", course_name: "GDPR Refresher", category: "data_protection", provider: "Online", completed_date: null, expiry_date: twoDaysAgo, certificate_url: null, status: "expired", is_mandatory: true, notes: null },
  { ...base, id: "tr_006", staff_id: "staff_diane", course_name: "Restraint (PRICE)", category: "restraint", provider: "PRICE Training", completed_date: daysFromNow(-15), expiry_date: daysFromNow(350), certificate_url: null, status: "compliant", is_mandatory: true, notes: null },
  { ...base, id: "tr_007", staff_id: "staff_mirela", course_name: "Fire Safety", category: "fire_safety", provider: "Online", completed_date: null, expiry_date: null, certificate_url: null, status: "not_started", is_mandatory: true, notes: "New starter — due within 4 weeks" },
  { ...base, id: "tr_008", staff_id: "staff_chervelle", course_name: "Medication Administration", category: "medication", provider: "In-house", completed_date: daysFromNow(-90), expiry_date: daysFromNow(275), certificate_url: null, status: "compliant", is_mandatory: true, notes: null },
  { ...base, id: "tr_009", staff_id: "staff_ryan", course_name: "Safeguarding Level 3", category: "safeguarding", provider: "NSPCC", completed_date: daysFromNow(-180), expiry_date: daysFromNow(185), certificate_url: null, status: "compliant", is_mandatory: true, notes: null },
  { ...base, id: "tr_010", staff_id: "staff_darren", course_name: "Designated Safeguarding Lead", category: "safeguarding", provider: "Derby LSCB", completed_date: daysFromNow(-60), expiry_date: daysFromNow(305), certificate_url: null, status: "compliant", is_mandatory: true, notes: null },
  { ...base, id: "tr_011", staff_id: "staff_bianca", course_name: "GDPR Refresher", category: "data_protection", provider: "Online", completed_date: null, expiry_date: twoDaysAgo, certificate_url: null, status: "expired", is_mandatory: true, notes: "Bank staff — must complete before next shift" },
  { ...base, id: "tr_012", staff_id: "staff_alex", course_name: "Safeguarding Level 3", category: "safeguarding", provider: "NSPCC", completed_date: null, expiry_date: null, certificate_url: null, status: "not_started", is_mandatory: true, notes: "New starter — booked for next month" },
];

// ── Medications ──────────────────────────────────────────────────────────────

export const MEDICATIONS: Medication[] = [
  { ...base, id: "med_001", child_id: "yp_casey", name: "Melatonin", type: "regular", dosage: "3mg", frequency: "Once daily at bedtime", route: "Oral", prescriber: "Dr. L. Chen", pharmacy: "Boots Derby", start_date: "2026-01-15", end_date: null, is_active: true, stock_count: 18, stock_last_checked: yesterday, side_effects: "Drowsiness", special_instructions: "Take 30 minutes before bedtime" },
  { ...base, id: "med_002", child_id: "yp_casey", name: "Fluoxetine", type: "regular", dosage: "10mg", frequency: "Once daily in the morning", route: "Oral", prescriber: "Dr. L. Chen", pharmacy: "Boots Derby", start_date: "2026-02-01", end_date: null, is_active: true, stock_count: 22, stock_last_checked: yesterday, side_effects: "Nausea, headache", special_instructions: "Take with food. Monitor mood." },
  { ...base, id: "med_003", child_id: "yp_alex", name: "Ibuprofen 200mg", type: "prn", dosage: "200mg", frequency: "As required, max 3x daily", route: "Oral", prescriber: "Dr. S. Patel", pharmacy: "Boots Derby", start_date: "2025-10-01", end_date: null, is_active: true, stock_count: 30, stock_last_checked: threeDaysAgo, side_effects: null, special_instructions: "Take with food. Record reason for each administration." },
  { ...base, id: "med_004", child_id: "yp_jordan", name: "Piriton", type: "prn", dosage: "4mg", frequency: "As required for allergic reactions", route: "Oral", prescriber: "Dr. A. Khan", pharmacy: "Boots Derby", start_date: "2025-12-01", end_date: null, is_active: true, stock_count: 15, stock_last_checked: yesterday, side_effects: "Drowsiness", special_instructions: "Given Penicillin allergy — use for any allergic reaction." },
];

// ── Leave Requests ───────────────────────────────────────────────────────────

export const LEAVE_REQUESTS: LeaveRequest[] = [
  { ...base, id: "leave_001", staff_id: "staff_diane", leave_type: "sick", start_date: today, end_date: tomorrow, total_days: 2, reason: "Unwell — stomach bug", status: "approved", approved_by: "staff_ryan", approved_at: hoursAgo(6), return_to_work_required: true, return_to_work_completed: false, return_to_work_date: null, return_to_work_by: null, return_to_work_notes: null },
  { ...base, id: "leave_002", staff_id: "staff_lackson", leave_type: "annual_leave", start_date: daysFromNow(10), end_date: daysFromNow(14), total_days: 5, reason: "Family holiday", status: "approved", approved_by: "staff_darren", approved_at: daysFromNow(-7) + "T10:00:00Z", return_to_work_required: false, return_to_work_completed: false, return_to_work_date: null, return_to_work_by: null, return_to_work_notes: null },
  { ...base, id: "leave_003", staff_id: "staff_mirela", leave_type: "annual_leave", start_date: daysFromNow(20), end_date: daysFromNow(22), total_days: 3, reason: "Personal", status: "pending", approved_by: null, approved_at: null, return_to_work_required: false, return_to_work_completed: false, return_to_work_date: null, return_to_work_by: null, return_to_work_notes: null },
];

// ── Helper: get staff name by ID ─────────────────────────────────────────────

export function getStaffById(id: string): StaffMember | undefined {
  return STAFF.find((s) => s.id === id);
}

export function getStaffName(id: string): string {
  return getStaffById(id)?.full_name || "Unknown";
}

export function getYPById(id: string): YoungPerson | undefined {
  return YOUNG_PEOPLE.find((yp) => yp.id === id);
}

export function getYPName(id: string): string {
  const yp = getYPById(id);
  return yp?.preferred_name || yp?.first_name || "Unknown";
}

// ── Daily Log ────────────────────────────────────────────────────────────────

export const DAILY_LOG: DailyLogEntry[] = [
  { ...base, id: "log_001", child_id: "yp_alex", date: today, time: "09:15", entry_type: "general", content: "Alex had a good morning. Engaged well with breakfast and was cooperative during morning routine. Positive mood — chatted about football.", mood_score: 8, staff_id: "staff_darren", linked_incident_id: null, is_significant: false },
  { ...base, id: "log_002", child_id: "yp_jordan", date: today, time: "08:30", entry_type: "food", content: "Jordan ate a full breakfast — cereal and toast. No dietary concerns. Reminded about halal food preparation.", mood_score: 7, staff_id: "staff_ryan", linked_incident_id: null, is_significant: false },
  { ...base, id: "log_003", child_id: "yp_casey", date: today, time: "10:00", entry_type: "health", content: "Casey's morning medication administered as prescribed. Took willingly with water. No adverse effects noted.", mood_score: 6, staff_id: "staff_darren", linked_incident_id: null, is_significant: false },
  { ...base, id: "log_004", child_id: "yp_alex", date: today, time: "11:30", entry_type: "education", content: "Alex completed 45 minutes of schoolwork with key worker support. Worked on maths — showed good concentration. Will attend Derby AP tomorrow.", mood_score: 7, staff_id: "staff_ryan", linked_incident_id: null, is_significant: false },
  { ...base, id: "log_005", child_id: "yp_jordan", date: today, time: "14:00", entry_type: "activity", content: "Jordan went to football training with Lackson. Good engagement. Made positive connections with teammates. Returned in high spirits.", mood_score: 9, staff_id: "staff_lackson", linked_incident_id: null, is_significant: true },
  { ...base, id: "log_006", child_id: "yp_casey", date: today, time: "15:30", entry_type: "behaviour", content: "Casey became distressed about a phone call from her mother. Supported to regulate emotions. Settled after 20 minutes with Chervelle. Reviewed contact agreement — will discuss with social worker.", mood_score: 4, staff_id: "staff_chervelle", linked_incident_id: null, is_significant: true },
  { ...base, id: "log_007", child_id: "yp_alex", date: yesterday, time: "20:00", entry_type: "sleep", content: "Alex settled at 9:30pm. Some restlessness reported around midnight but self-settled. Sleep quality described as moderate.", mood_score: 5, staff_id: "staff_edward", linked_incident_id: null, is_significant: false },
];
