// ══════════════════════════════════════════════════════════════════════════════
// CORNERSTONE — CARE EVENT SEED DATA
// Realistic demo data for the care event routing pipeline.
// Populates: care events, routes, audit log, reg45 queue, annex A queue,
//            child daily summaries, filing cabinet, saved time metrics.
// ══════════════════════════════════════════════════════════════════════════════

import { daysFromNow, todayStr, generateId } from "@/lib/utils";
import type {
  CareEvent, CareEventRoute, CareEventAuditLog,
  Reg45EvidenceItem, AnnexAEvidenceItem, ChildDailySummary,
  FilingCabinetItem, SavedTimeMetric,
} from "@/types/care-events";

const today = todayStr();
const yesterday = daysFromNow(-1);
const twoDaysAgo = daysFromNow(-2);
const threeDaysAgo = daysFromNow(-3);
const fourDaysAgo = daysFromNow(-4);
const fiveDaysAgo = daysFromNow(-5);
const HOME_ID = "home_oak";

// ── Base Care Events ──────────────────────────────────────────────────────────

export const SEED_CARE_EVENTS: CareEvent[] = [
  {
    id: "ce_001",
    home_id: HOME_ID,
    child_id: "yp_alex",
    shift_id: "shift_001",
    staff_id: "staff_darren",
    verified_by: "staff_ryan",
    returned_by: null,
    locked_by: null,
    category: "behaviour",
    title: "Alex: Physical altercation with peer — restraint required",
    content: "Alex became agitated during the afternoon activity session. An argument with another young person escalated to a physical altercation. A planned physical intervention was required lasting approximately 4 minutes. Alex was safely guided to his bedroom. Post-incident debrief completed. Alex expressed remorse and was calm within 30 minutes. Incident report filed. Risk assessment review required. This incident contributes to evidence of ongoing behaviour challenges noted in previous Regulation 45 reports.",
    mood_score: 3,
    is_significant: true,
    status: "verified",
    event_date: today,
    event_time: "14:35",
    requires_manager_review: true,
    requires_reg40_triage: true,
    contributes_to_reg45: true,
    contributes_to_annex_a: true,
    is_safeguarding: false,
    evidence_prompts: [
      { id: "ep_001a", question: "Was a planned physical intervention used?", required: true, answer: "Yes", completed: true },
      { id: "ep_001b", question: "Was an incident report completed?", required: true, answer: "Yes", completed: true },
    ],
    evidence_prompts_completed: true,
    staff_signature: true,
    staff_signed_at: `${today}T15:10:00Z`,
    manager_id: "staff_ryan",
    manager_review_note: "Verified. Route to PI log and Reg 40 triage. Reg 45 suggestion approved.",
    manager_review_at: `${today}T16:00:00Z`,
    manager_review_completed: true,
    manager_signature: true,
    manager_notes: "Risk assessment review scheduled for this week.",
    return_reason: null,
    returned_at: null,
    submitted_at: `${today}T15:05:00Z`,
    submitted_by: "staff_darren",
    verified_at: `${today}T16:00:00Z`,
    locked_at: null,
    version: 1,
    previous_version_id: null,
    amendment_reason: null,
    amended_by: null,
    amended_at: null,
    is_current_version: true,
    aria_suggested_summary: "Physical altercation requiring planned intervention. Risk profile requires review.",
    aria_suggested_category: "physical_intervention",
    aria_suggested_routing: ["management_oversight", "reg40_triage", "reg45_evidence", "annex_a_evidence", "filing_cabinet"],
    aria_suggested_reg45: "A physical intervention was required on [date] following a peer altercation. Staff followed protocol. Debrief completed. Risk assessment review is scheduled.",
    aria_suggested_annex_a: "Physical intervention recorded — planned PI. Review of risk assessment undertaken.",
    aria_suggestions_reviewed: true,
    routing_summary: {
      records_updated: 5,
      tasks_created: 2,
      reg45_count: 1,
      annex_a_count: 1,
      areas_updated: ["Management oversight", "Regulation 40 triage", "Regulation 45 evidence", "Annex A evidence", "Filing cabinet"],
    },
    created_at: `${today}T14:35:00Z`,
    updated_at: `${today}T16:00:00Z`,
  },
  {
    id: "ce_002",
    home_id: HOME_ID,
    child_id: "yp_casey",
    shift_id: "shift_001",
    staff_id: "staff_chervelle",
    verified_by: null,
    returned_by: null,
    locked_by: null,
    category: "health",
    title: "Casey: GP appointment — medication review",
    content: "Casey attended GP appointment for routine medication review. Dr Smith adjusted the sertraline dose from 50mg to 75mg. New prescription collected and stored in medication cabinet (key held by Darren). Casey was cooperative throughout the appointment. Follow-up appointment booked for 6 weeks. Casey's current prescription has been updated in the medication chart.",
    mood_score: 6,
    is_significant: false,
    status: "manager_review_required",
    event_date: today,
    event_time: "10:15",
    requires_manager_review: true,
    requires_reg40_triage: false,
    contributes_to_reg45: false,
    contributes_to_annex_a: true,
    is_safeguarding: false,
    evidence_prompts: [
      { id: "ep_002a", question: "Was the prescription updated on the medication chart?", required: true, answer: "Yes", completed: true },
    ],
    evidence_prompts_completed: true,
    staff_signature: true,
    staff_signed_at: `${today}T11:00:00Z`,
    manager_id: null,
    manager_review_note: null,
    manager_review_at: null,
    manager_review_completed: false,
    manager_signature: false,
    manager_notes: null,
    return_reason: null,
    returned_at: null,
    submitted_at: `${today}T10:55:00Z`,
    submitted_by: "staff_chervelle",
    verified_at: null,
    locked_at: null,
    version: 1,
    previous_version_id: null,
    amendment_reason: null,
    amended_by: null,
    amended_at: null,
    is_current_version: true,
    aria_suggested_summary: "GP medication review — sertraline increased. Prescription updated. Follow-up in 6 weeks.",
    aria_suggested_category: "medication",
    aria_suggested_routing: ["health_record", "medication_record", "annex_a_evidence", "filing_cabinet"],
    aria_suggested_reg45: null,
    aria_suggested_annex_a: "Current medication details updated following GP review.",
    aria_suggestions_reviewed: false,
    routing_summary: {
      records_updated: 3,
      tasks_created: 1,
      reg45_count: 0,
      annex_a_count: 1,
      areas_updated: ["Health records", "Medication", "Management oversight", "Filing cabinet"],
    },
    created_at: `${today}T10:15:00Z`,
    updated_at: `${today}T11:00:00Z`,
  },
  {
    id: "ce_003",
    home_id: HOME_ID,
    child_id: "yp_jordan",
    shift_id: "shift_002",
    staff_id: "staff_lackson",
    verified_by: "staff_darren",
    returned_by: null,
    locked_by: null,
    category: "missing_episode",
    title: "Jordan: Missing from care — returned safely",
    content: "Jordan left the home without permission at 18:45. Staff unable to locate by 19:15 — police notified at 19:20 as per missing episode protocol. Jordan returned voluntarily at 21:30, appearing calm but unwilling to disclose whereabouts. Return to care interview conducted by Darren. Jordan disclosed she had been with friends — location confirmed. No safeguarding concerns identified at this time. Risk assessment to be reviewed. Social worker notified at 22:00.",
    mood_score: 4,
    is_significant: true,
    status: "verified",
    event_date: yesterday,
    event_time: "18:45",
    requires_manager_review: true,
    requires_reg40_triage: true,
    contributes_to_reg45: true,
    contributes_to_annex_a: true,
    is_safeguarding: false,
    evidence_prompts: [
      { id: "ep_003a", question: "Was police notified within 30 minutes?", required: true, answer: "Yes — within 35 minutes", completed: true },
      { id: "ep_003b", question: "Was a return to care interview completed?", required: true, answer: "Yes", completed: true },
      { id: "ep_003c", question: "Was social worker notified?", required: true, answer: "Yes", completed: true },
    ],
    evidence_prompts_completed: true,
    staff_signature: true,
    staff_signed_at: `${yesterday}T22:10:00Z`,
    manager_id: "staff_darren",
    manager_review_note: "Verified. Reg 40 triage required — duration over 2 hours. Reg 45 evidence added.",
    manager_review_at: `${yesterday}T22:45:00Z`,
    manager_review_completed: true,
    manager_signature: true,
    manager_notes: "Risk assessment review booked for tomorrow. Discuss with social worker at next CiC review.",
    return_reason: null,
    returned_at: null,
    submitted_at: `${yesterday}T22:05:00Z`,
    submitted_by: "staff_lackson",
    verified_at: `${yesterday}T22:45:00Z`,
    locked_at: null,
    version: 1,
    previous_version_id: null,
    amendment_reason: null,
    amended_by: null,
    amended_at: null,
    is_current_version: true,
    aria_suggested_summary: "Missing episode — Jordan absent 2h45m. Police notified. Returned safely. No safeguarding concerns.",
    aria_suggested_category: "missing_episode",
    aria_suggested_routing: ["management_oversight", "reg40_triage", "reg45_evidence", "annex_a_evidence", "filing_cabinet"],
    aria_suggested_reg45: "A missing episode was recorded on [date]. Jordan was absent for 2 hours 45 minutes. Police were notified within protocol timeframes. Jordan returned voluntarily and a return to care interview was completed. No immediate safeguarding concerns identified. Risk assessment reviewed.",
    aria_suggested_annex_a: "Missing episode recorded. Protocol followed. Return to care interview completed.",
    aria_suggestions_reviewed: true,
    routing_summary: {
      records_updated: 4,
      tasks_created: 2,
      reg45_count: 1,
      annex_a_count: 1,
      areas_updated: ["Management oversight", "Regulation 40 triage", "Regulation 45 evidence", "Annex A evidence", "Filing cabinet"],
    },
    created_at: `${yesterday}T22:00:00Z`,
    updated_at: `${yesterday}T22:45:00Z`,
  },
  {
    id: "ce_004",
    home_id: HOME_ID,
    child_id: "yp_alex",
    shift_id: null,
    staff_id: "staff_ryan",
    verified_by: null,
    returned_by: "staff_darren",
    locked_by: null,
    category: "safeguarding",
    title: "Alex: Disclosure — concerning contact from unknown adult",
    content: "Alex disclosed during a 1:1 session that an unknown adult male had been messaging him on social media offering money in exchange for meeting up. Alex showed staff the messages. Screenshots taken and saved. Alex appeared anxious but relieved to disclose. Immediate section 47 discussion with Darren. Social worker contacted. Safeguarding referral completed. Phone retained pending review. LADO notified.",
    mood_score: 2,
    is_significant: true,
    status: "returned",
    event_date: twoDaysAgo,
    event_time: "16:20",
    requires_manager_review: true,
    requires_reg40_triage: true,
    contributes_to_reg45: true,
    contributes_to_annex_a: false,
    is_safeguarding: true,
    evidence_prompts: [
      { id: "ep_004a", question: "Were screenshots secured?", required: true, answer: "Yes", completed: true },
      { id: "ep_004b", question: "Was safeguarding referral completed?", required: true, answer: "Yes", completed: true },
    ],
    evidence_prompts_completed: true,
    staff_signature: true,
    staff_signed_at: `${twoDaysAgo}T17:00:00Z`,
    manager_id: "staff_darren",
    manager_review_note: null,
    manager_review_at: null,
    manager_review_completed: false,
    manager_signature: false,
    manager_notes: null,
    return_reason: "Please add LADO reference number and confirm Section 47 outcome before verification.",
    returned_at: `${twoDaysAgo}T17:30:00Z`,
    submitted_at: `${twoDaysAgo}T16:55:00Z`,
    submitted_by: "staff_ryan",
    verified_at: null,
    locked_at: null,
    version: 1,
    previous_version_id: null,
    amendment_reason: null,
    amended_by: null,
    amended_at: null,
    is_current_version: true,
    aria_suggested_summary: "Safeguarding disclosure — online grooming concern. Referral completed. LADO notified.",
    aria_suggested_category: "safeguarding",
    aria_suggested_routing: ["safeguarding_record", "management_oversight", "reg40_triage", "reg45_evidence", "filing_cabinet"],
    aria_suggested_reg45: "A safeguarding disclosure was made on [date]. A referral was completed and LADO notified. The matter is under active investigation.",
    aria_suggested_annex_a: null,
    aria_suggestions_reviewed: false,
    routing_summary: null,
    created_at: `${twoDaysAgo}T16:20:00Z`,
    updated_at: `${twoDaysAgo}T17:30:00Z`,
  },
  {
    id: "ce_005",
    home_id: HOME_ID,
    child_id: "yp_casey",
    shift_id: null,
    staff_id: "staff_mirela",
    verified_by: "staff_darren",
    returned_by: null,
    locked_by: null,
    category: "family_contact",
    title: "Casey: Planned contact with mother — positive visit",
    content: "Casey had planned telephone contact with her mother today. The call lasted 45 minutes. Contact appeared positive — Casey was engaged and happy throughout. Mother enquired about the upcoming review meeting and was provided with information by Mirela. Casey appeared settled after the call. No safeguarding concerns. Contact agreed in line with contact agreement.",
    mood_score: 8,
    is_significant: false,
    status: "verified",
    event_date: threeDaysAgo,
    event_time: "14:00",
    requires_manager_review: false,
    requires_reg40_triage: false,
    contributes_to_reg45: false,
    contributes_to_annex_a: true,
    is_safeguarding: false,
    evidence_prompts: [],
    evidence_prompts_completed: true,
    staff_signature: true,
    staff_signed_at: `${threeDaysAgo}T14:55:00Z`,
    manager_id: "staff_darren",
    manager_review_note: "Verified. Positive contact noted for Annex A.",
    manager_review_at: `${threeDaysAgo}T15:30:00Z`,
    manager_review_completed: true,
    manager_signature: true,
    manager_notes: null,
    return_reason: null,
    returned_at: null,
    submitted_at: `${threeDaysAgo}T14:50:00Z`,
    submitted_by: "staff_mirela",
    verified_at: `${threeDaysAgo}T15:30:00Z`,
    locked_at: null,
    version: 1,
    previous_version_id: null,
    amendment_reason: null,
    amended_by: null,
    amended_at: null,
    is_current_version: true,
    aria_suggested_summary: null,
    aria_suggested_category: null,
    aria_suggested_routing: null,
    aria_suggested_reg45: null,
    aria_suggested_annex_a: "Family contact maintained as per contact agreement. Positive contact recorded.",
    aria_suggestions_reviewed: true,
    routing_summary: {
      records_updated: 2,
      tasks_created: 0,
      reg45_count: 0,
      annex_a_count: 1,
      areas_updated: ["Family contact", "Annex A evidence", "Filing cabinet"],
    },
    created_at: `${threeDaysAgo}T14:00:00Z`,
    updated_at: `${threeDaysAgo}T15:30:00Z`,
  },
  {
    id: "ce_006",
    home_id: HOME_ID,
    child_id: "yp_jordan",
    shift_id: null,
    staff_id: "staff_edward",
    verified_by: null,
    returned_by: null,
    locked_by: null,
    category: "education",
    title: "Jordan: Successful return to school — first full week",
    content: "Jordan completed her first full week back at school since the exclusion period. School reported positive engagement across all subjects. Jordan achieved a merit award for effort in English. School SENCO noted improved focus. Jordan appeared proud and positive when returning home. Liaison with school SENCO and Personal Education Plan to be updated with this progress. This marks a significant milestone for Jordan's educational journey.",
    mood_score: 9,
    is_significant: true,
    status: "submitted",
    event_date: fourDaysAgo,
    event_time: "15:30",
    requires_manager_review: false,
    requires_reg40_triage: false,
    contributes_to_reg45: true,
    contributes_to_annex_a: true,
    is_safeguarding: false,
    evidence_prompts: [],
    evidence_prompts_completed: true,
    staff_signature: true,
    staff_signed_at: `${fourDaysAgo}T15:45:00Z`,
    manager_id: null,
    manager_review_note: null,
    manager_review_at: null,
    manager_review_completed: false,
    manager_signature: false,
    manager_notes: null,
    return_reason: null,
    returned_at: null,
    submitted_at: `${fourDaysAgo}T15:45:00Z`,
    submitted_by: "staff_edward",
    verified_at: null,
    locked_at: null,
    version: 1,
    previous_version_id: null,
    amendment_reason: null,
    amended_by: null,
    amended_at: null,
    is_current_version: true,
    aria_suggested_summary: "Significant positive milestone — first full school week. Merit award. PEP to be updated.",
    aria_suggested_category: "education",
    aria_suggested_routing: ["education_record", "reg45_evidence", "annex_a_evidence", "filing_cabinet"],
    aria_suggested_reg45: "Positive educational milestone: Jordan completed a full week in school following a period of exclusion. School SENCO reports improved engagement. Merit award received.",
    aria_suggested_annex_a: "Education — positive engagement noted. First full school week completed. PEP to be updated.",
    aria_suggestions_reviewed: false,
    routing_summary: {
      records_updated: 2,
      tasks_created: 0,
      reg45_count: 1,
      annex_a_count: 1,
      areas_updated: ["Education records", "Regulation 45 evidence", "Annex A evidence", "Filing cabinet"],
    },
    created_at: `${fourDaysAgo}T15:30:00Z`,
    updated_at: `${fourDaysAgo}T15:45:00Z`,
  },
  {
    id: "ce_007",
    home_id: HOME_ID,
    child_id: null,
    shift_id: null,
    staff_id: "staff_darren",
    verified_by: null,
    returned_by: null,
    locked_by: null,
    category: "general",
    title: "General: Staff team briefing — new behaviour support plan rollout",
    content: "Full staff team briefing held to introduce the updated behaviour support plans for all three young people. All staff attended. Training on de-escalation approaches reviewed. Updated plans distributed and signed off by all staff. Key points: Alex's plan updated to include a cool-down protocol; Jordan's plan includes new school-home communication strategy; Casey's plan updated following medication review.",
    mood_score: null,
    is_significant: false,
    status: "draft",
    event_date: fiveDaysAgo,
    event_time: "09:00",
    requires_manager_review: false,
    requires_reg40_triage: false,
    contributes_to_reg45: false,
    contributes_to_annex_a: false,
    is_safeguarding: false,
    evidence_prompts: [],
    evidence_prompts_completed: true,
    staff_signature: false,
    staff_signed_at: null,
    manager_id: null,
    manager_review_note: null,
    manager_review_at: null,
    manager_review_completed: false,
    manager_signature: false,
    manager_notes: null,
    return_reason: null,
    returned_at: null,
    submitted_at: null,
    submitted_by: null,
    verified_at: null,
    locked_at: null,
    version: 1,
    previous_version_id: null,
    amendment_reason: null,
    amended_by: null,
    amended_at: null,
    is_current_version: true,
    aria_suggested_summary: null,
    aria_suggested_category: null,
    aria_suggested_routing: null,
    aria_suggested_reg45: null,
    aria_suggested_annex_a: null,
    aria_suggestions_reviewed: false,
    routing_summary: null,
    created_at: `${fiveDaysAgo}T09:00:00Z`,
    updated_at: `${fiveDaysAgo}T09:10:00Z`,
  },

  // ── Additional seed events for richer demo ────────────────────────────────

  {
    id: "ce_028",
    home_id: HOME_ID,
    child_id: "yp_alex",
    shift_id: "shift_001",
    staff_id: "staff_darren",
    verified_by: "staff_ryan",
    returned_by: null,
    locked_by: null,
    category: "health",
    title: "Alex: GP appointment — annual health review",
    content: "Accompanied Alex to GP for his LAC annual health review. Alex was cooperative and engaged well with Dr Patel. Weight and height recorded. Blood pressure normal. Alex reported low mood at times but said he is managing. GP referred to CAMHS for follow-up. Appointment letter secured and filed. Alex expressed relief that someone listened to him.",
    mood_score: 6,
    is_significant: true,
    event_date: daysFromNow(-6),
    event_time: "10:30",
    status: "verified",
    requires_manager_review: false,
    requires_reg40_triage: false,
    contributes_to_reg45: true,
    contributes_to_annex_a: true,
    is_safeguarding: false,
    evidence_prompts: [
      { id: "ep_028a", question: "Was the health passport updated?", required: true, answer: "Yes", completed: true },
      { id: "ep_028b", question: "Were outcomes filed with placing authority?", required: true, answer: "Yes — sent to Southwark IRO", completed: true },
    ],
    evidence_prompts_completed: true,
    staff_signature: true,
    staff_signed_at: `${daysFromNow(-6)}T11:30:00Z`,
    manager_review_note: null,
    manager_review_at: null,
    manager_review_completed: false,
    manager_signature: false,
    manager_notes: null,
    submitted_at: `${daysFromNow(-6)}T11:30:00Z`,
    submitted_by: "staff_darren",
    verified_at: `${daysFromNow(-5)}T09:00:00Z`,
    manager_id: "staff_ryan",
    return_reason: null,
    returned_at: null,
    locked_at: null,
    amended_at: null,
    amended_by: null,
    amendment_reason: null,
    previous_version_id: null,
    version: 1,
    is_current_version: true,
    aria_suggested_summary: null,
    aria_suggested_category: null,
    aria_suggested_routing: null,
    aria_suggested_reg45: null,
    aria_suggested_annex_a: null,
    aria_suggestions_reviewed: false,
    routing_summary: { records_updated: 3, tasks_created: 0, reg45_count: 1, annex_a_count: 1, areas_updated: ["health_record", "annex_a_evidence", "filing_cabinet"] },
    created_at: `${daysFromNow(-6)}T10:45:00Z`,
    updated_at: `${daysFromNow(-5)}T09:05:00Z`,
  },

  {
    id: "ce_029",
    home_id: HOME_ID,
    child_id: "yp_casey",
    shift_id: "shift_002",
    staff_id: "staff_chervelle",
    category: "education",
    title: "Casey: PEP meeting — spring term targets agreed",
    content: "Personal Education Plan meeting held at school with Miss Johnson (designated teacher), Casey's social worker (James Wright) and Casey. Casey has been making good progress in English and is on track for Grade 5. She expressed interest in film studies as an elective. Some concerns raised about maths — targeted support sessions to start next week. Casey said she enjoys school and feels settled. Next PEP review scheduled for July.",
    mood_score: 8,
    is_significant: true,
    event_date: daysFromNow(-7),
    event_time: "14:00",
    status: "verified",
    requires_manager_review: false,
    requires_reg40_triage: false,
    contributes_to_reg45: true,
    contributes_to_annex_a: true,
    is_safeguarding: false,
    evidence_prompts: [
      { id: "ep_029a", question: "Were PEP targets recorded on the system?", required: true, answer: "Yes", completed: true },
      { id: "ep_029b", question: "Was child's voice captured?", required: true, answer: "Yes — Casey stated goals in her own words", completed: true },
    ],
    evidence_prompts_completed: true,
    staff_signature: true,
    staff_signed_at: `${daysFromNow(-7)}T15:00:00Z`,
    manager_review_note: null,
    manager_review_at: null,
    manager_review_completed: false,
    manager_signature: false,
    manager_notes: null,
    submitted_at: `${daysFromNow(-7)}T15:00:00Z`,
    submitted_by: "staff_chervelle",
    verified_at: `${daysFromNow(-7)}T17:00:00Z`,
    verified_by: "staff_ryan",
    manager_id: "staff_ryan",
    returned_by: null,
    return_reason: null,
    returned_at: null,
    locked_at: null,
    locked_by: null,
    amended_at: null,
    amended_by: null,
    amendment_reason: null,
    previous_version_id: null,
    version: 1,
    is_current_version: true,
    aria_suggested_summary: null,
    aria_suggested_category: null,
    aria_suggested_routing: null,
    aria_suggested_reg45: null,
    aria_suggested_annex_a: null,
    aria_suggestions_reviewed: false,
    routing_summary: { records_updated: 3, tasks_created: 0, reg45_count: 1, annex_a_count: 1, areas_updated: ["education_record", "annex_a_evidence", "filing_cabinet"] },
    created_at: `${daysFromNow(-7)}T15:00:00Z`,
    updated_at: `${daysFromNow(-7)}T17:05:00Z`,
  },

  {
    id: "ce_030",
    home_id: HOME_ID,
    child_id: "yp_jordan",
    shift_id: "shift_003",
    staff_id: "staff_anna",
    category: "family_contact",
    title: "Jordan: Supervised family contact — mother visit",
    content: "Supervised contact with Jordan's mother (Sandra) took place at the contact centre. Jordan was nervous beforehand but settled quickly. Contact lasted 90 minutes. Sandra brought gifts and a birthday card for next week. Conversation was warm and appropriate. Jordan was quiet at times — staff noted he appeared emotional towards the end. Jordan said he felt 'mixed up' afterwards. Post-contact debrief completed. No safeguarding concerns noted during contact.",
    mood_score: 5,
    is_significant: false,
    event_date: daysFromNow(-4),
    event_time: "13:00",
    status: "verified",
    requires_manager_review: false,
    requires_reg40_triage: false,
    contributes_to_reg45: false,
    contributes_to_annex_a: true,
    is_safeguarding: false,
    evidence_prompts: [
      { id: "ep_030a", question: "Was the contact log completed?", required: true, answer: "Yes", completed: true },
      { id: "ep_030b", question: "Was Jordan's voice/wellbeing after contact noted?", required: true, answer: "Yes — post-contact debrief completed", completed: true },
    ],
    evidence_prompts_completed: true,
    staff_signature: true,
    staff_signed_at: `${daysFromNow(-4)}T15:00:00Z`,
    manager_review_note: null,
    manager_review_at: null,
    manager_review_completed: false,
    manager_signature: false,
    manager_notes: null,
    submitted_at: `${daysFromNow(-4)}T15:00:00Z`,
    submitted_by: "staff_anna",
    verified_at: `${daysFromNow(-4)}T17:30:00Z`,
    verified_by: "staff_darren",
    manager_id: "staff_darren",
    returned_by: null,
    return_reason: null,
    returned_at: null,
    locked_at: null,
    locked_by: null,
    amended_at: null,
    amended_by: null,
    amendment_reason: null,
    previous_version_id: null,
    version: 1,
    is_current_version: true,
    aria_suggested_summary: null,
    aria_suggested_category: null,
    aria_suggested_routing: null,
    aria_suggested_reg45: null,
    aria_suggested_annex_a: null,
    aria_suggestions_reviewed: false,
    routing_summary: { records_updated: 3, tasks_created: 0, reg45_count: 0, annex_a_count: 1, areas_updated: ["family_contact_record", "annex_a_evidence", "filing_cabinet"] },
    created_at: `${daysFromNow(-4)}T15:00:00Z`,
    updated_at: `${daysFromNow(-4)}T17:35:00Z`,
  },

  {
    id: "ce_031",
    home_id: HOME_ID,
    child_id: "yp_alex",
    shift_id: "shift_001",
    staff_id: "staff_mirela",
    category: "wellbeing",
    title: "Alex: Positive engagement — cooking session, expressed pride",
    content: "Alex joined the cooking session this afternoon and made chicken curry from scratch with minimal support. He was clearly proud of the result and asked if he could cook again next week. He talked openly about wanting to learn to cook for himself when he moves on. Staff reflected on his progress — six months ago Alex would refuse to engage in any group activities. He is building real confidence. Mood was notably positive throughout. No concerns.",
    mood_score: 9,
    is_significant: false,
    event_date: today,
    event_time: "16:00",
    status: "submitted",
    requires_manager_review: false,
    requires_reg40_triage: false,
    contributes_to_reg45: true,
    contributes_to_annex_a: true,
    is_safeguarding: false,
    evidence_prompts: [],
    evidence_prompts_completed: true,
    staff_signature: true,
    staff_signed_at: `${today}T16:30:00Z`,
    manager_review_note: null,
    manager_review_at: null,
    manager_review_completed: false,
    manager_signature: false,
    manager_notes: null,
    submitted_at: `${today}T16:30:00Z`,
    submitted_by: "staff_mirela",
    verified_at: null,
    verified_by: null,
    manager_id: null,
    returned_by: null,
    return_reason: null,
    returned_at: null,
    locked_at: null,
    locked_by: null,
    amended_at: null,
    amended_by: null,
    amendment_reason: null,
    previous_version_id: null,
    version: 1,
    is_current_version: true,
    aria_suggested_summary: null,
    aria_suggested_category: null,
    aria_suggested_routing: null,
    aria_suggested_reg45: null,
    aria_suggested_annex_a: null,
    aria_suggestions_reviewed: false,
    routing_summary: { records_updated: 1, tasks_created: 0, reg45_count: 1, annex_a_count: 1, areas_updated: ["child_daily_summary", "reg45_evidence", "annex_a_evidence"] },
    created_at: `${today}T16:30:00Z`,
    updated_at: `${today}T16:30:00Z`,
  },

  {
    id: "ce_032",
    home_id: HOME_ID,
    child_id: "yp_casey",
    shift_id: "shift_001",
    staff_id: "staff_edward",
    category: "general",
    title: "Casey: General update — settled day, positive mood",
    content: "Casey had a settled and positive day. She completed her homework without prompting, helped set the table for dinner, and joined the movie night in the lounge. She was chatty and sociable with peers. No incidents or concerns. Casey mentioned she is looking forward to her birthday next week. Staff noted she has been consistently more engaged and open over the past two weeks. Bedtime routine completed without issue.",
    mood_score: 8,
    is_significant: false,
    event_date: today,
    event_time: "20:30",
    status: "draft",
    requires_manager_review: false,
    requires_reg40_triage: false,
    contributes_to_reg45: false,
    contributes_to_annex_a: false,
    is_safeguarding: false,
    evidence_prompts: [],
    evidence_prompts_completed: false,
    staff_signature: false,
    staff_signed_at: null,
    manager_review_note: null,
    manager_review_at: null,
    manager_review_completed: false,
    manager_signature: false,
    manager_notes: null,
    submitted_at: null,
    submitted_by: null,
    verified_at: null,
    verified_by: null,
    manager_id: null,
    returned_by: null,
    return_reason: null,
    returned_at: null,
    locked_at: null,
    locked_by: null,
    amended_at: null,
    amended_by: null,
    amendment_reason: null,
    previous_version_id: null,
    version: 1,
    is_current_version: true,
    aria_suggested_summary: null,
    aria_suggested_category: null,
    aria_suggested_routing: null,
    aria_suggested_reg45: null,
    aria_suggested_annex_a: null,
    aria_suggestions_reviewed: false,
    routing_summary: null,
    created_at: `${today}T20:30:00Z`,
    updated_at: `${today}T20:30:00Z`,
  },
];

// ── Care Event Routes ─────────────────────────────────────────────────────────

export const SEED_CARE_EVENT_ROUTES: CareEventRoute[] = [
  // ce_001 (behaviour/restraint) routes
  { id: "cer_001a", care_event_id: "ce_001", home_id: HOME_ID, route_type: "management_oversight", status: "completed", linked_record_id: "task_oversight_001", linked_record_table: "tasks", processing_notes: "Oversight task created.", error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 5, created_at: `${today}T15:10:00Z`, updated_at: `${today}T15:10:00Z` },
  { id: "cer_001b", care_event_id: "ce_001", home_id: HOME_ID, route_type: "reg40_triage", status: "completed", linked_record_id: "task_reg40_001", linked_record_table: "tasks", processing_notes: "Reg 40 triage task created.", error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 10, created_at: `${today}T15:10:00Z`, updated_at: `${today}T15:10:00Z` },
  { id: "cer_001c", care_event_id: "ce_001", home_id: HOME_ID, route_type: "reg45_evidence", status: "completed", linked_record_id: "r45_001", linked_record_table: "reg45_evidence_queue", processing_notes: "Evidence added to Reg 45 queue.", error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 10, created_at: `${today}T15:10:00Z`, updated_at: `${today}T15:10:00Z` },
  { id: "cer_001d", care_event_id: "ce_001", home_id: HOME_ID, route_type: "annex_a_evidence", status: "completed", linked_record_id: "aae_001", linked_record_table: "annex_a_evidence_queue", processing_notes: "Evidence added to Annex A queue.", error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 8, created_at: `${today}T15:10:00Z`, updated_at: `${today}T15:10:00Z` },
  { id: "cer_001e", care_event_id: "ce_001", home_id: HOME_ID, route_type: "filing_cabinet", status: "completed", linked_record_id: "fil_001", linked_record_table: "filing_cabinet", processing_notes: "Auto-filed under 'physical_intervention'.", error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 6, created_at: `${today}T15:10:00Z`, updated_at: `${today}T15:10:00Z` },

  // ce_002 (health/medication) routes
  { id: "cer_002a", care_event_id: "ce_002", home_id: HOME_ID, route_type: "management_oversight", status: "completed", linked_record_id: "task_oversight_002", linked_record_table: "tasks", processing_notes: null, error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 5, created_at: `${today}T11:00:00Z`, updated_at: `${today}T11:00:00Z` },
  { id: "cer_002b", care_event_id: "ce_002", home_id: HOME_ID, route_type: "annex_a_evidence", status: "completed", linked_record_id: "aae_002", linked_record_table: "annex_a_evidence_queue", processing_notes: null, error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 8, created_at: `${today}T11:00:00Z`, updated_at: `${today}T11:00:00Z` },
  { id: "cer_002c", care_event_id: "ce_002", home_id: HOME_ID, route_type: "filing_cabinet", status: "completed", linked_record_id: "fil_002", linked_record_table: "filing_cabinet", processing_notes: null, error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 6, created_at: `${today}T11:00:00Z`, updated_at: `${today}T11:00:00Z` },

  // ce_003 (missing episode) routes
  { id: "cer_003a", care_event_id: "ce_003", home_id: HOME_ID, route_type: "management_oversight", status: "completed", linked_record_id: "task_oversight_003", linked_record_table: "tasks", processing_notes: null, error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 5, created_at: `${yesterday}T22:10:00Z`, updated_at: `${yesterday}T22:10:00Z` },
  { id: "cer_003b", care_event_id: "ce_003", home_id: HOME_ID, route_type: "reg40_triage", status: "completed", linked_record_id: "task_reg40_002", linked_record_table: "tasks", processing_notes: null, error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 10, created_at: `${yesterday}T22:10:00Z`, updated_at: `${yesterday}T22:10:00Z` },
  { id: "cer_003c", care_event_id: "ce_003", home_id: HOME_ID, route_type: "reg45_evidence", status: "completed", linked_record_id: "r45_002", linked_record_table: "reg45_evidence_queue", processing_notes: null, error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 10, created_at: `${yesterday}T22:10:00Z`, updated_at: `${yesterday}T22:10:00Z` },
  { id: "cer_003d", care_event_id: "ce_003", home_id: HOME_ID, route_type: "annex_a_evidence", status: "completed", linked_record_id: "aae_003", linked_record_table: "annex_a_evidence_queue", processing_notes: null, error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 8, created_at: `${yesterday}T22:10:00Z`, updated_at: `${yesterday}T22:10:00Z` },
  { id: "cer_003e", care_event_id: "ce_003", home_id: HOME_ID, route_type: "filing_cabinet", status: "completed", linked_record_id: "fil_003", linked_record_table: "filing_cabinet", processing_notes: null, error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 6, created_at: `${yesterday}T22:10:00Z`, updated_at: `${yesterday}T22:10:00Z` },

  // ce_005 (family contact) routes
  { id: "cer_005a", care_event_id: "ce_005", home_id: HOME_ID, route_type: "annex_a_evidence", status: "completed", linked_record_id: "aae_004", linked_record_table: "annex_a_evidence_queue", processing_notes: null, error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 8, created_at: `${threeDaysAgo}T14:55:00Z`, updated_at: `${threeDaysAgo}T14:55:00Z` },
  { id: "cer_005b", care_event_id: "ce_005", home_id: HOME_ID, route_type: "filing_cabinet", status: "completed", linked_record_id: "fil_004", linked_record_table: "filing_cabinet", processing_notes: null, error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 6, created_at: `${threeDaysAgo}T14:55:00Z`, updated_at: `${threeDaysAgo}T14:55:00Z` },

  // ce_006 (education milestone) routes
  { id: "cer_006a", care_event_id: "ce_006", home_id: HOME_ID, route_type: "reg45_evidence", status: "completed", linked_record_id: "r45_003", linked_record_table: "reg45_evidence_queue", processing_notes: null, error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 10, created_at: `${fourDaysAgo}T15:45:00Z`, updated_at: `${fourDaysAgo}T15:45:00Z` },
  { id: "cer_006b", care_event_id: "ce_006", home_id: HOME_ID, route_type: "annex_a_evidence", status: "completed", linked_record_id: "aae_005", linked_record_table: "annex_a_evidence_queue", processing_notes: null, error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 8, created_at: `${fourDaysAgo}T15:45:00Z`, updated_at: `${fourDaysAgo}T15:45:00Z` },
  { id: "cer_006c", care_event_id: "ce_006", home_id: HOME_ID, route_type: "filing_cabinet", status: "completed", linked_record_id: "fil_005", linked_record_table: "filing_cabinet", processing_notes: null, error_message: null, retry_count: 0, last_retried_at: null, time_saved_minutes: 6, created_at: `${fourDaysAgo}T15:45:00Z`, updated_at: `${fourDaysAgo}T15:45:00Z` },
];

// ── Audit Log ─────────────────────────────────────────────────────────────────

export const SEED_CARE_EVENT_AUDIT: CareEventAuditLog[] = [
  { id: "ceal_001", care_event_id: "ce_001", home_id: HOME_ID, action: "care_event_created", actor_staff_id: "staff_darren", actor_role: "manager", detail: { category: "behaviour", child_id: "yp_alex" }, ip_address: null, created_at: `${today}T14:35:00Z` },
  { id: "ceal_002", care_event_id: "ce_001", home_id: HOME_ID, action: "care_event_submitted", actor_staff_id: "staff_darren", actor_role: "manager", detail: { staff_signature: true, evidence_prompts_completed: true }, ip_address: null, created_at: `${today}T15:05:00Z` },
  { id: "ceal_003", care_event_id: "ce_001", home_id: HOME_ID, action: "care_event_routed", actor_staff_id: "staff_darren", actor_role: "manager", detail: { routes_completed: 5, routes_failed: 0, routes_skipped: 0 }, ip_address: null, created_at: `${today}T15:10:00Z` },
  { id: "ceal_004", care_event_id: "ce_001", home_id: HOME_ID, action: "reg45_evidence_suggested", actor_staff_id: "staff_darren", actor_role: "manager", detail: { evidence_id: "r45_001", theme: "behaviour" }, ip_address: null, created_at: `${today}T15:10:00Z` },
  { id: "ceal_005", care_event_id: "ce_001", home_id: HOME_ID, action: "care_event_verified", actor_staff_id: "staff_ryan", actor_role: "manager", detail: { manager_notes: "Verified. Route to PI log and Reg 40 triage." }, ip_address: null, created_at: `${today}T16:00:00Z` },
  { id: "ceal_006", care_event_id: "ce_001", home_id: HOME_ID, action: "reg45_evidence_accepted", actor_staff_id: "staff_ryan", actor_role: "manager", detail: { evidence_id: "r45_001", decision: "approved" }, ip_address: null, created_at: `${today}T16:05:00Z` },

  { id: "ceal_007", care_event_id: "ce_002", home_id: HOME_ID, action: "care_event_created", actor_staff_id: "staff_chervelle", actor_role: "residential_care_worker", detail: { category: "health", child_id: "yp_casey" }, ip_address: null, created_at: `${today}T10:15:00Z` },
  { id: "ceal_008", care_event_id: "ce_002", home_id: HOME_ID, action: "care_event_submitted", actor_staff_id: "staff_chervelle", actor_role: "residential_care_worker", detail: { staff_signature: true }, ip_address: null, created_at: `${today}T10:55:00Z` },
  { id: "ceal_009", care_event_id: "ce_002", home_id: HOME_ID, action: "care_event_routed", actor_staff_id: "staff_chervelle", actor_role: "residential_care_worker", detail: { routes_completed: 3, routes_failed: 0 }, ip_address: null, created_at: `${today}T11:00:00Z` },

  { id: "ceal_010", care_event_id: "ce_003", home_id: HOME_ID, action: "care_event_created", actor_staff_id: "staff_lackson", actor_role: "residential_care_worker", detail: { category: "missing_episode", child_id: "yp_jordan" }, ip_address: null, created_at: `${yesterday}T22:00:00Z` },
  { id: "ceal_011", care_event_id: "ce_003", home_id: HOME_ID, action: "care_event_submitted", actor_staff_id: "staff_lackson", actor_role: "residential_care_worker", detail: { staff_signature: true, evidence_prompts_completed: true }, ip_address: null, created_at: `${yesterday}T22:05:00Z` },
  { id: "ceal_012", care_event_id: "ce_003", home_id: HOME_ID, action: "care_event_routed", actor_staff_id: "staff_lackson", actor_role: "residential_care_worker", detail: { routes_completed: 5, routes_failed: 0 }, ip_address: null, created_at: `${yesterday}T22:10:00Z` },
  { id: "ceal_013", care_event_id: "ce_003", home_id: HOME_ID, action: "care_event_verified", actor_staff_id: "staff_darren", actor_role: "manager", detail: { manager_notes: "Verified. Reg 40 triage required." }, ip_address: null, created_at: `${yesterday}T22:45:00Z` },

  { id: "ceal_014", care_event_id: "ce_004", home_id: HOME_ID, action: "care_event_created", actor_staff_id: "staff_ryan", actor_role: "senior_care_worker", detail: { category: "safeguarding", child_id: "yp_alex" }, ip_address: null, created_at: `${twoDaysAgo}T16:20:00Z` },
  { id: "ceal_015", care_event_id: "ce_004", home_id: HOME_ID, action: "care_event_submitted", actor_staff_id: "staff_ryan", actor_role: "senior_care_worker", detail: { staff_signature: true }, ip_address: null, created_at: `${twoDaysAgo}T16:55:00Z` },
  { id: "ceal_016", care_event_id: "ce_004", home_id: HOME_ID, action: "care_event_returned", actor_staff_id: "staff_darren", actor_role: "manager", detail: { return_reason: "Please add LADO reference number." }, ip_address: null, created_at: `${twoDaysAgo}T17:30:00Z` },

  { id: "ceal_017", care_event_id: "ce_005", home_id: HOME_ID, action: "care_event_created", actor_staff_id: "staff_mirela", actor_role: "residential_care_worker", detail: { category: "family_contact", child_id: "yp_casey" }, ip_address: null, created_at: `${threeDaysAgo}T14:00:00Z` },
  { id: "ceal_018", care_event_id: "ce_005", home_id: HOME_ID, action: "care_event_verified", actor_staff_id: "staff_darren", actor_role: "manager", detail: {}, ip_address: null, created_at: `${threeDaysAgo}T15:30:00Z` },

  { id: "ceal_019", care_event_id: "ce_006", home_id: HOME_ID, action: "care_event_created", actor_staff_id: "staff_edward", actor_role: "residential_care_worker", detail: { category: "education", child_id: "yp_jordan" }, ip_address: null, created_at: `${fourDaysAgo}T15:30:00Z` },
  { id: "ceal_020", care_event_id: "ce_006", home_id: HOME_ID, action: "care_event_submitted", actor_staff_id: "staff_edward", actor_role: "residential_care_worker", detail: { staff_signature: true }, ip_address: null, created_at: `${fourDaysAgo}T15:45:00Z` },
  { id: "ceal_021", care_event_id: "ce_006", home_id: HOME_ID, action: "reg45_evidence_suggested", actor_staff_id: "staff_edward", actor_role: "residential_care_worker", detail: { evidence_id: "r45_003", theme: "education" }, ip_address: null, created_at: `${fourDaysAgo}T15:45:00Z` },
];

// ── Reg 45 Evidence Queue ─────────────────────────────────────────────────────

export const SEED_REG45_EVIDENCE: Reg45EvidenceItem[] = [
  {
    id: "r45_001",
    care_event_id: "ce_001",
    home_id: HOME_ID,
    suggested_text: "A planned physical intervention was required on [date] following a peer altercation involving a young person. Staff followed all protocol requirements. A post-incident debrief was completed with the young person. A risk assessment review has been scheduled. This incident is consistent with the young person's known behaviour profile and existing risk management strategies.",
    suggested_theme: "physical intervention",
    suggested_section: "Quality of care — challenging behaviour",
    manager_decision: "approved",
    manager_approved_text: "A planned physical intervention was required following a peer altercation. Staff responded proportionately and followed all protocol requirements. Post-incident debrief completed. Risk assessment reviewed.",
    reviewed_by: "staff_ryan",
    reviewed_at: `${today}T16:05:00Z`,
    review_notes: "Approved for Reg 45 — wording updated for clarity.",
    created_at: `${today}T15:10:00Z`,
    updated_at: `${today}T16:05:00Z`,
  },
  {
    id: "r45_002",
    care_event_id: "ce_003",
    home_id: HOME_ID,
    suggested_text: "A missing episode was recorded. The young person was absent for 2 hours 45 minutes. Police were notified within protocol timeframes. The young person returned voluntarily and a return to care interview was completed by a manager. No immediate safeguarding concerns were identified. The risk assessment has been reviewed and updated.",
    suggested_theme: "missing episode",
    suggested_section: "Safeguarding and risk management",
    manager_decision: "pending",
    manager_approved_text: null,
    reviewed_by: null,
    reviewed_at: null,
    review_notes: null,
    created_at: `${yesterday}T22:10:00Z`,
    updated_at: `${yesterday}T22:10:00Z`,
  },
  {
    id: "r45_003",
    care_event_id: "ce_006",
    home_id: HOME_ID,
    suggested_text: "A significant positive educational milestone was achieved. A young person completed their first full week back in school following a period of exclusion. The school SENCO reported marked improvements in engagement and focus. A merit award was received. The Personal Education Plan is being updated to reflect this progress.",
    suggested_theme: "education",
    suggested_section: "Outcomes for children — education",
    manager_decision: "pending",
    manager_approved_text: null,
    reviewed_by: null,
    reviewed_at: null,
    review_notes: null,
    created_at: `${fourDaysAgo}T15:45:00Z`,
    updated_at: `${fourDaysAgo}T15:45:00Z`,
  },
  {
    id: "r45_004",
    care_event_id: "ce_004",
    home_id: HOME_ID,
    suggested_text: "A safeguarding concern was identified and reported. A child protection referral was made and the LADO was notified. The matter is currently under active investigation. Staff responded promptly and followed the home's safeguarding procedures.",
    suggested_theme: "safeguarding",
    suggested_section: "Safeguarding and child protection",
    manager_decision: "deferred",
    manager_approved_text: null,
    reviewed_by: "staff_darren",
    reviewed_at: `${twoDaysAgo}T18:00:00Z`,
    review_notes: "Deferred pending completion of investigation and LADO outcome.",
    created_at: `${twoDaysAgo}T17:00:00Z`,
    updated_at: `${twoDaysAgo}T18:00:00Z`,
  },
];

// ── Annex A Evidence Queue ────────────────────────────────────────────────────

export const SEED_ANNEX_A_EVIDENCE: AnnexAEvidenceItem[] = [
  {
    id: "aae_001",
    care_event_id: "ce_001",
    home_id: HOME_ID,
    annex_section: "section_5",
    suggested_text: "Physical intervention recorded — planned PI used following peer altercation. Staff response was proportionate. Post-incident debrief completed. Risk assessment review scheduled.",
    manager_decision: "approved",
    manager_approved_text: "Physical intervention recorded and reviewed. Staff followed protocol. PI debrief completed.",
    reviewed_by: "staff_ryan",
    reviewed_at: `${today}T16:05:00Z`,
    created_at: `${today}T15:10:00Z`,
    updated_at: `${today}T16:05:00Z`,
  },
  {
    id: "aae_002",
    care_event_id: "ce_002",
    home_id: HOME_ID,
    annex_section: "section_3",
    suggested_text: "Current medication details updated following GP review on [date]. Sertraline dose increased from 50mg to 75mg as prescribed. Medication chart updated. Follow-up appointment booked.",
    manager_decision: "pending",
    manager_approved_text: null,
    reviewed_by: null,
    reviewed_at: null,
    created_at: `${today}T11:00:00Z`,
    updated_at: `${today}T11:00:00Z`,
  },
  {
    id: "aae_003",
    care_event_id: "ce_003",
    home_id: HOME_ID,
    annex_section: "section_5",
    suggested_text: "Missing episode recorded. Young person absent for 2h45m. Protocol followed — police notified, return to care interview completed. Risk assessment reviewed.",
    manager_decision: "approved",
    manager_approved_text: "Missing episode — protocol followed. Return to care interview completed. Risk assessment reviewed and updated.",
    reviewed_by: "staff_darren",
    reviewed_at: `${yesterday}T23:00:00Z`,
    created_at: `${yesterday}T22:10:00Z`,
    updated_at: `${yesterday}T23:00:00Z`,
  },
  {
    id: "aae_004",
    care_event_id: "ce_005",
    home_id: HOME_ID,
    annex_section: "section_4",
    suggested_text: "Family contact maintained as per contact agreement. Planned telephone contact with mother completed. Contact described as positive. Young person settled following contact.",
    manager_decision: "approved",
    manager_approved_text: "Family contact — positive contact maintained as per contact agreement.",
    reviewed_by: "staff_darren",
    reviewed_at: `${threeDaysAgo}T16:00:00Z`,
    created_at: `${threeDaysAgo}T14:55:00Z`,
    updated_at: `${threeDaysAgo}T16:00:00Z`,
  },
  {
    id: "aae_005",
    care_event_id: "ce_006",
    home_id: HOME_ID,
    annex_section: "section_2",
    suggested_text: "Education — young person completed first full school week following exclusion period. School reports positive engagement. Merit award received. PEP to be updated.",
    manager_decision: "pending",
    manager_approved_text: null,
    reviewed_by: null,
    reviewed_at: null,
    created_at: `${fourDaysAgo}T15:45:00Z`,
    updated_at: `${fourDaysAgo}T15:45:00Z`,
  },
];

// ── Child Daily Summaries ─────────────────────────────────────────────────────

export const SEED_CHILD_DAILY_SUMMARIES: ChildDailySummary[] = [
  {
    id: "cds_001",
    home_id: HOME_ID,
    child_id: "yp_alex",
    summary_date: today,
    event_count: 2,
    significant_count: 1,
    avg_mood_score: 5.5,
    categories: ["behaviour", "health"],
    summary_text: "2 care events recorded. 1 significant. Average mood: 5.5/10. Categories: behaviour, health.",
    requires_followup: true,
    generated_at: `${today}T15:15:00Z`,
    updated_at: `${today}T15:15:00Z`,
  },
  {
    id: "cds_002",
    home_id: HOME_ID,
    child_id: "yp_casey",
    summary_date: today,
    event_count: 1,
    significant_count: 0,
    avg_mood_score: 6,
    categories: ["health"],
    summary_text: "1 care event recorded. Average mood: 6/10. Categories: health.",
    requires_followup: true,
    generated_at: `${today}T11:05:00Z`,
    updated_at: `${today}T11:05:00Z`,
  },
  {
    id: "cds_003",
    home_id: HOME_ID,
    child_id: "yp_jordan",
    summary_date: yesterday,
    event_count: 1,
    significant_count: 1,
    avg_mood_score: 4,
    categories: ["missing_episode"],
    summary_text: "1 care event recorded. 1 significant. Average mood: 4/10. Categories: missing_episode.",
    requires_followup: true,
    generated_at: `${yesterday}T22:15:00Z`,
    updated_at: `${yesterday}T22:15:00Z`,
  },
  {
    id: "cds_004",
    home_id: HOME_ID,
    child_id: "yp_casey",
    summary_date: threeDaysAgo,
    event_count: 1,
    significant_count: 0,
    avg_mood_score: 8,
    categories: ["family_contact"],
    summary_text: "1 care event recorded. Average mood: 8/10. Positive family contact. Categories: family_contact.",
    requires_followup: false,
    generated_at: `${threeDaysAgo}T15:00:00Z`,
    updated_at: `${threeDaysAgo}T15:00:00Z`,
  },
  {
    id: "cds_005",
    home_id: HOME_ID,
    child_id: "yp_jordan",
    summary_date: fourDaysAgo,
    event_count: 1,
    significant_count: 1,
    avg_mood_score: 9,
    categories: ["education"],
    summary_text: "1 care event recorded. 1 significant — educational milestone. Average mood: 9/10. Categories: education.",
    requires_followup: false,
    generated_at: `${fourDaysAgo}T15:50:00Z`,
    updated_at: `${fourDaysAgo}T15:50:00Z`,
  },
];

// ── Filing Cabinet ────────────────────────────────────────────────────────────

export const SEED_FILING_CABINET: FilingCabinetItem[] = [
  {
    id: "fil_001",
    care_event_id: "ce_001",
    home_id: HOME_ID,
    child_id: "yp_alex",
    category: "physical_intervention",
    sub_category: "behaviour",
    title: "Alex: Physical altercation with peer — restraint required",
    description: "Physical intervention event. Staff followed protocol. Post-incident debrief completed. Risk assessment review scheduled.",
    source_type: "care_event",
    linked_record_id: "ce_001",
    linked_record_table: "care_events",
    is_verified: true,
    verified_at: `${today}T16:00:00Z`,
    verified_by: "staff_ryan",
    tags: ["physical_intervention", "significant", "manager_review"],
    filed_at: `${today}T15:10:00Z`,
    created_at: `${today}T15:10:00Z`,
    updated_at: `${today}T16:00:00Z`,
  },
  {
    id: "fil_002",
    care_event_id: "ce_002",
    home_id: HOME_ID,
    child_id: "yp_casey",
    category: "health",
    sub_category: "medication",
    title: "Casey: GP appointment — medication review",
    description: "GP medication review. Sertraline dose updated 50mg → 75mg. Prescription secured. Follow-up in 6 weeks.",
    source_type: "care_event",
    linked_record_id: "ce_002",
    linked_record_table: "care_events",
    is_verified: false,
    verified_at: null,
    verified_by: null,
    tags: ["health", "medication"],
    filed_at: `${today}T11:00:00Z`,
    created_at: `${today}T11:00:00Z`,
    updated_at: `${today}T11:00:00Z`,
  },
  {
    id: "fil_003",
    care_event_id: "ce_003",
    home_id: HOME_ID,
    child_id: "yp_jordan",
    category: "missing_episode",
    sub_category: null,
    title: "Jordan: Missing from care — returned safely",
    description: "Missing episode. Jordan absent 2h45m. Police notified. Returned safely. Return to care interview completed.",
    source_type: "care_event",
    linked_record_id: "ce_003",
    linked_record_table: "care_events",
    is_verified: true,
    verified_at: `${yesterday}T22:45:00Z`,
    verified_by: "staff_darren",
    tags: ["missing_episode", "significant", "manager_review"],
    filed_at: `${yesterday}T22:10:00Z`,
    created_at: `${yesterday}T22:10:00Z`,
    updated_at: `${yesterday}T22:45:00Z`,
  },
  {
    id: "fil_004",
    care_event_id: "ce_005",
    home_id: HOME_ID,
    child_id: "yp_casey",
    category: "family_contact",
    sub_category: null,
    title: "Casey: Planned contact with mother — positive visit",
    description: "Positive family contact. 45-minute telephone call with mother. Young person settled after contact.",
    source_type: "care_event",
    linked_record_id: "ce_005",
    linked_record_table: "care_events",
    is_verified: true,
    verified_at: `${threeDaysAgo}T15:30:00Z`,
    verified_by: "staff_darren",
    tags: ["family_contact"],
    filed_at: `${threeDaysAgo}T14:55:00Z`,
    created_at: `${threeDaysAgo}T14:55:00Z`,
    updated_at: `${threeDaysAgo}T15:30:00Z`,
  },
  {
    id: "fil_005",
    care_event_id: "ce_006",
    home_id: HOME_ID,
    child_id: "yp_jordan",
    category: "education",
    sub_category: null,
    title: "Jordan: Successful return to school — first full week",
    description: "Significant educational milestone. First full school week completed. Merit award received. PEP to be updated.",
    source_type: "care_event",
    linked_record_id: "ce_006",
    linked_record_table: "care_events",
    is_verified: false,
    verified_at: null,
    verified_by: null,
    tags: ["education", "significant"],
    filed_at: `${fourDaysAgo}T15:45:00Z`,
    created_at: `${fourDaysAgo}T15:45:00Z`,
    updated_at: `${fourDaysAgo}T15:45:00Z`,
  },
  {
    id: "fil_006",
    care_event_id: "ce_004",
    home_id: HOME_ID,
    child_id: "yp_alex",
    category: "safeguarding",
    sub_category: null,
    title: "Alex: Disclosure — concerning contact from unknown adult",
    description: "Safeguarding disclosure. Online contact referral made. LADO notified. Matter under investigation. Record returned pending LADO reference.",
    source_type: "care_event",
    linked_record_id: "ce_004",
    linked_record_table: "care_events",
    is_verified: false,
    verified_at: null,
    verified_by: null,
    tags: ["safeguarding", "significant", "manager_review"],
    filed_at: `${twoDaysAgo}T16:55:00Z`,
    created_at: `${twoDaysAgo}T16:55:00Z`,
    updated_at: `${twoDaysAgo}T16:55:00Z`,
  },
];

// ── Saved Time Metrics ────────────────────────────────────────────────────────

export const SEED_SAVED_TIME_METRICS: SavedTimeMetric[] = [
  // ce_001 routes
  { id: "stm_001", care_event_id: "ce_001", home_id: HOME_ID, route_type: "management_oversight", minutes_saved: 5, activity_description: "Auto-routing to management oversight from care event", staff_id: "staff_darren", recorded_at: `${today}T15:10:00Z`, created_at: `${today}T15:10:00Z` },
  { id: "stm_002", care_event_id: "ce_001", home_id: HOME_ID, route_type: "reg40_triage", minutes_saved: 10, activity_description: "Auto-routing to reg40 triage from care event", staff_id: "staff_darren", recorded_at: `${today}T15:10:00Z`, created_at: `${today}T15:10:00Z` },
  { id: "stm_003", care_event_id: "ce_001", home_id: HOME_ID, route_type: "reg45_evidence", minutes_saved: 10, activity_description: "Auto-routing to reg45 evidence from care event", staff_id: "staff_darren", recorded_at: `${today}T15:10:00Z`, created_at: `${today}T15:10:00Z` },
  { id: "stm_004", care_event_id: "ce_001", home_id: HOME_ID, route_type: "annex_a_evidence", minutes_saved: 8, activity_description: "Auto-routing to annex A evidence from care event", staff_id: "staff_darren", recorded_at: `${today}T15:10:00Z`, created_at: `${today}T15:10:00Z` },
  { id: "stm_005", care_event_id: "ce_001", home_id: HOME_ID, route_type: "filing_cabinet", minutes_saved: 6, activity_description: "Auto-routing to filing cabinet from care event", staff_id: "staff_darren", recorded_at: `${today}T15:10:00Z`, created_at: `${today}T15:10:00Z` },
  // ce_002 routes
  { id: "stm_006", care_event_id: "ce_002", home_id: HOME_ID, route_type: "management_oversight", minutes_saved: 5, activity_description: "Auto-routing to management oversight from care event", staff_id: "staff_chervelle", recorded_at: `${today}T11:00:00Z`, created_at: `${today}T11:00:00Z` },
  { id: "stm_007", care_event_id: "ce_002", home_id: HOME_ID, route_type: "annex_a_evidence", minutes_saved: 8, activity_description: "Auto-routing to annex A evidence from care event", staff_id: "staff_chervelle", recorded_at: `${today}T11:00:00Z`, created_at: `${today}T11:00:00Z` },
  { id: "stm_008", care_event_id: "ce_002", home_id: HOME_ID, route_type: "filing_cabinet", minutes_saved: 6, activity_description: "Auto-routing to filing cabinet from care event", staff_id: "staff_chervelle", recorded_at: `${today}T11:00:00Z`, created_at: `${today}T11:00:00Z` },
  // ce_003 routes
  { id: "stm_009", care_event_id: "ce_003", home_id: HOME_ID, route_type: "management_oversight", minutes_saved: 5, activity_description: "Auto-routing to management oversight from care event", staff_id: "staff_lackson", recorded_at: `${yesterday}T22:10:00Z`, created_at: `${yesterday}T22:10:00Z` },
  { id: "stm_010", care_event_id: "ce_003", home_id: HOME_ID, route_type: "reg40_triage", minutes_saved: 10, activity_description: "Auto-routing to reg40 triage from care event", staff_id: "staff_lackson", recorded_at: `${yesterday}T22:10:00Z`, created_at: `${yesterday}T22:10:00Z` },
  { id: "stm_011", care_event_id: "ce_003", home_id: HOME_ID, route_type: "reg45_evidence", minutes_saved: 10, activity_description: "Auto-routing to reg45 evidence from care event", staff_id: "staff_lackson", recorded_at: `${yesterday}T22:10:00Z`, created_at: `${yesterday}T22:10:00Z` },
  { id: "stm_012", care_event_id: "ce_003", home_id: HOME_ID, route_type: "annex_a_evidence", minutes_saved: 8, activity_description: "Auto-routing to annex A evidence from care event", staff_id: "staff_lackson", recorded_at: `${yesterday}T22:10:00Z`, created_at: `${yesterday}T22:10:00Z` },
  { id: "stm_013", care_event_id: "ce_003", home_id: HOME_ID, route_type: "filing_cabinet", minutes_saved: 6, activity_description: "Auto-routing to filing cabinet from care event", staff_id: "staff_lackson", recorded_at: `${yesterday}T22:10:00Z`, created_at: `${yesterday}T22:10:00Z` },
  // ce_005 routes
  { id: "stm_014", care_event_id: "ce_005", home_id: HOME_ID, route_type: "annex_a_evidence", minutes_saved: 8, activity_description: "Auto-routing to annex A evidence from care event", staff_id: "staff_mirela", recorded_at: `${threeDaysAgo}T14:55:00Z`, created_at: `${threeDaysAgo}T14:55:00Z` },
  { id: "stm_015", care_event_id: "ce_005", home_id: HOME_ID, route_type: "filing_cabinet", minutes_saved: 6, activity_description: "Auto-routing to filing cabinet from care event", staff_id: "staff_mirela", recorded_at: `${threeDaysAgo}T14:55:00Z`, created_at: `${threeDaysAgo}T14:55:00Z` },
  // ce_006 routes
  { id: "stm_016", care_event_id: "ce_006", home_id: HOME_ID, route_type: "reg45_evidence", minutes_saved: 10, activity_description: "Auto-routing to reg45 evidence from care event", staff_id: "staff_edward", recorded_at: `${fourDaysAgo}T15:45:00Z`, created_at: `${fourDaysAgo}T15:45:00Z` },
  { id: "stm_017", care_event_id: "ce_006", home_id: HOME_ID, route_type: "annex_a_evidence", minutes_saved: 8, activity_description: "Auto-routing to annex A evidence from care event", staff_id: "staff_edward", recorded_at: `${fourDaysAgo}T15:45:00Z`, created_at: `${fourDaysAgo}T15:45:00Z` },
  { id: "stm_018", care_event_id: "ce_006", home_id: HOME_ID, route_type: "filing_cabinet", minutes_saved: 6, activity_description: "Auto-routing to filing cabinet from care event", staff_id: "staff_edward", recorded_at: `${fourDaysAgo}T15:45:00Z`, created_at: `${fourDaysAgo}T15:45:00Z` },
];
