// ══════════════════════════════════════════════════════════════════════════════
// CARA — RECRUITMENT REMINDER ENGINE
//
// Turns the Safer Recruitment Command Centre's computed chase ladder and
// next-actions into concrete, deduplicated task specs for the task system
// (the spec's AUTOMATED_REMINDERS: reference chasing 48h/5d/7d/10d, urgent
// manager reviews, final sign-off, exceptional-start daily review).
//
// Pure: derives specs from an already-computed command result; the route layer
// owns store reads/writes. Idempotency: every spec carries a deterministic key
// embedded in the task description as "[auto:<key>]" — syncing twice creates
// nothing new while the matching task is still open.
//
// The engine creates REMINDERS to act — never decisions. Sign-off tasks say
// the decision is the manager's; nothing here can clear a candidate.
// ══════════════════════════════════════════════════════════════════════════════

import type { TaskCategory, TaskPriority } from "@/lib/constants";
import type {
  SaferRecruitmentCommandResult,
  CommandCandidate,
} from "@/lib/engines/safer-recruitment-command-engine";

export interface ReminderSpec {
  key: string;
  title: string;
  description: string;
  category: TaskCategory;
  priority: TaskPriority;
  due_date: string; // YYYY-MM-DD
  candidate_id: string;
  reference_id: string | null;
  assigned_role: "registered_manager" | null;
}

const AUTO_MARKER = /\[auto:([a-z0-9:_-]+)\]/i;

export function reminderMarker(key: string): string {
  return `[auto:${key}]`;
}

export function extractReminderKey(description: string | null | undefined): string | null {
  if (!description) return null;
  const m = description.match(AUTO_MARKER);
  return m ? m[1].toLowerCase() : null;
}

function spec(
  key: string,
  title: string,
  body: string,
  priority: TaskPriority,
  due: string,
  candidateId: string,
  referenceId: string | null = null,
  assignManager = false,
): ReminderSpec {
  return {
    key,
    title: title.slice(0, 120),
    description: `${body}\n\nGenerated by the Safer Recruitment Command Centre. ${reminderMarker(key)}`,
    category: "compliance",
    priority,
    due_date: due,
    candidate_id: candidateId,
    reference_id: referenceId,
    assigned_role: assignManager ? "registered_manager" : null,
  };
}

const CHASE_TASKS: Record<string, { title: (ref: string, cand: string) => string; priority: TaskPriority; manager: boolean }> = {
  remind_48h: { title: (r, c) => `Send first reference reminder — ${r} (${c})`, priority: "medium", manager: false },
  second_reminder: { title: (r, c) => `Send second reference reminder — ${r} (${c})`, priority: "high", manager: false },
  escalate_manager: { title: (r, c) => `Phone referee ${r} — reference overdue (${c})`, priority: "urgent", manager: true },
  suggest_alternative: { title: (r, c) => `Request alternative referee for ${c} (re ${r})`, priority: "urgent", manager: true },
};

function candidateSpecs(c: CommandCandidate, today: string): ReminderSpec[] {
  if (c.start_eligibility === "cleared") return [];
  const out: ReminderSpec[] = [];

  // ── Reference chase ladder ──
  for (const chase of c.reference_chases) {
    const rule = CHASE_TASKS[chase.state];
    if (!rule) continue; // "awaiting" needs no task yet
    out.push(
      spec(
        `srcmd:ref:${chase.reference_id}:${chase.state}`,
        rule.title(chase.referee_name, c.name),
        `${chase.action}\nReference outstanding ${chase.days_waiting} days for ${c.name} (${c.role_applied}).`,
        rule.priority,
        today,
        c.candidate_id,
        chase.reference_id,
        rule.manager,
      ),
    );
  }

  // ── Urgent next actions (DBS concern, unsatisfactory reference,
  //    exceptional-start controls missing, …) ──
  if (c.next_action.urgency === "urgent") {
    const slug = c.next_action.label.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 40);
    out.push(
      spec(
        `srcmd:cand:${c.candidate_id}:urgent:${slug}`,
        `${c.next_action.label} (${c.name})`,
        `${c.next_action.detail}\nThis is a manager review — the decision and its rationale must be recorded by a person.`,
        "urgent",
        today,
        c.candidate_id,
        null,
        true,
      ),
    );
  }

  // ── Final suitability sign-off (pack complete, decision outstanding) ──
  if (c.next_action.label.toLowerCase().includes("final suitability sign-off")) {
    out.push(
      spec(
        `srcmd:cand:${c.candidate_id}:signoff`,
        `Final suitability sign-off — ${c.name}`,
        `The safer-recruitment pack for ${c.name} is complete. The final suitability decision belongs to the Registered Manager and must be recorded before any start.`,
        "high",
        today,
        c.candidate_id,
        null,
        true,
      ),
    );
  }

  // ── Exceptional start: a fresh review task every day until checks complete ──
  if (c.exceptional_start?.active) {
    out.push(
      spec(
        `srcmd:cand:${c.candidate_id}:exceptional:${today}`,
        `Daily exceptional-start review — ${c.name}`,
        `${c.name} is working under an exceptional start (supervised only, never sole charge, outside staffing ratios). Review today that supervision is in place and chase the outstanding checks.`,
        "urgent",
        today,
        c.candidate_id,
        null,
        true,
      ),
    );
  }

  return out;
}

export function deriveReminderSpecs(command: SaferRecruitmentCommandResult): ReminderSpec[] {
  const specs = command.candidates.flatMap((c) => candidateSpecs(c, command.generated_for));
  // Defensive de-dupe inside a single run (keys are unique by construction).
  const seen = new Set<string>();
  return specs.filter((s) => (seen.has(s.key) ? false : (seen.add(s.key), true)));
}

export interface ReminderSyncPlan {
  to_create: ReminderSpec[];
  skipped_existing: ReminderSpec[];
}

/** Compare derived specs against the keys of currently-open auto tasks. */
export function planReminderSync(
  specs: ReminderSpec[],
  openTaskDescriptions: Array<string | null | undefined>,
): ReminderSyncPlan {
  const existing = new Set<string>();
  for (const d of openTaskDescriptions) {
    const key = extractReminderKey(d);
    if (key) existing.add(key);
  }
  const to_create: ReminderSpec[] = [];
  const skipped_existing: ReminderSpec[] = [];
  for (const s of specs) (existing.has(s.key.toLowerCase()) ? skipped_existing : to_create).push(s);
  return { to_create, skipped_existing };
}
