"use client";

// ══════════════════════════════════════════════════════════════════════════════
// Cara — CHILD REPORTS LIST
//
// Shows all Cara-generated reports for a specific child. Provides quick
// access to generate a new report or view existing drafts and locked reports.
// ══════════════════════════════════════════════════════════════════════════════

import React, { use } from "react";
import Link from "next/link";
import { PageShell } from "@/components/layout/page-shell";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import {
  REPORT_TYPE_LABELS,
  REPORT_STATUS_LABELS,
} from "@/types/cara-reports";
import type { ChildReport, ReportStatus } from "@/types/cara-reports";
import {
  Sparkles,
  Plus,
  FileText,
  ArrowLeft,
  Calendar,
  ShieldCheck,
  Quote,
  AlertTriangle,
} from "lucide-react";

// ── Child name lookup ───────────────────────────────────────────────────────

const CHILD_NAMES: Record<string, string> = {
  "child_1": "Jayden Mitchell",
  "child_2": "Amara Osei",
  "child_3": "Reuben Walsh",
  "demo-child-1": "Jayden Mitchell",
  "demo-child-2": "Amara Osei",
  "demo-child-3": "Reuben Walsh",
};

// ── Status badge variant ────────────────────────────────────────────────────

function statusVariant(status: ReportStatus) {
  switch (status) {
    case "draft": return "warning" as const;
    case "pending_review": return "info" as const;
    case "approved": return "success" as const;
    case "rejected": return "destructive" as const;
    case "locked": return "purple" as const;
    case "archived": return "secondary" as const;
    default: return "secondary" as const;
  }
}

// ── Demo reports ────────────────────────────────────────────────────────────

function getDemoReports(childId: string): Partial<ChildReport>[] {
  return [
    {
      id: `rpt-${childId}-1`,
      report_type: "weekly_child_report",
      status: "locked",
      date_range_start: "2026-05-05",
      date_range_end: "2026-05-11",
      overall_confidence_score: 82,
      child_voice_included: true,
      evidence_gap_count: 1,
      risk_tier: "low",
      created_at: "2026-05-11T14:00:00Z",
    },
    {
      id: `rpt-${childId}-2`,
      report_type: "weekly_child_report",
      status: "approved",
      date_range_start: "2026-04-28",
      date_range_end: "2026-05-04",
      overall_confidence_score: 76,
      child_voice_included: true,
      evidence_gap_count: 2,
      risk_tier: "low",
      created_at: "2026-05-04T16:00:00Z",
    },
    {
      id: `rpt-${childId}-3`,
      report_type: "monthly_progress_summary",
      status: "pending_review",
      date_range_start: "2026-04-01",
      date_range_end: "2026-04-30",
      overall_confidence_score: 68,
      child_voice_included: true,
      evidence_gap_count: 3,
      risk_tier: "medium",
      created_at: "2026-05-01T10:00:00Z",
    },
    {
      id: `rpt-${childId}-4`,
      report_type: "social_worker_update",
      status: "draft",
      date_range_start: "2026-05-01",
      date_range_end: "2026-05-11",
      overall_confidence_score: 55,
      child_voice_included: false,
      evidence_gap_count: 5,
      risk_tier: "low",
      created_at: "2026-05-10T09:00:00Z",
    },
    {
      id: `rpt-${childId}-5`,
      report_type: "keywork_progress_report",
      status: "locked",
      date_range_start: "2026-03-01",
      date_range_end: "2026-04-30",
      overall_confidence_score: 88,
      child_voice_included: true,
      evidence_gap_count: 0,
      risk_tier: "low",
      created_at: "2026-05-02T11:00:00Z",
    },
  ];
}

// ── Component ───────────────────────────────────────────────────────────────

export default function ChildReportsPage({
  params,
}: {
  params: Promise<{ childId: string }>;
}) {
  const { childId } = use(params);
  const childName = CHILD_NAMES[childId] ?? childId;
  const reports = getDemoReports(childId);

  return (
    <PageShell title={`Reports — ${childName}`}>
      {/* Header */}
      <div className="mb-6 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div
            className="flex h-10 w-10 items-center justify-center rounded-lg"
            style={{ backgroundColor: "var(--cs-cara-gold-bg)" }}
          >
            <Sparkles className="h-5 w-5" style={{ color: "var(--cs-cara-gold)" }} />
          </div>
          <div>
            <h1 className="text-xl font-semibold" style={{ color: "var(--cs-navy)" }}>
              Reports for {childName}
            </h1>
            <p className="text-sm" style={{ color: "var(--cs-text-muted)" }}>
              {reports.length} reports generated by Cara
            </p>
          </div>
        </div>
        <div className="flex gap-2">
          <Link href={`/children/${childId}/intelligence`}>
            <Button variant="outline" size="sm" className="gap-1">
              <ArrowLeft className="h-4 w-4" /> Intelligence
            </Button>
          </Link>
          <Link href={`/children/${childId}/reports/new`}>
            <Button size="sm" className="gap-1" style={{ backgroundColor: "var(--cs-cara-gold)" }}>
              <Plus className="h-4 w-4" /> New Report
            </Button>
          </Link>
        </div>
      </div>

      {/* Reports List */}
      <div className="space-y-3">
        {reports.map((report) => (
          <Link key={report.id} href={`/cara/reports/${report.id}`}>
            <Card className="transition-shadow hover:shadow-md cursor-pointer mb-3">
              <CardContent className="py-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3 flex-1 min-w-0">
                    <FileText className="h-5 w-5 shrink-0" style={{ color: "var(--cs-cara-gold)" }} />
                    <div className="min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="font-medium text-sm" style={{ color: "var(--cs-navy)" }}>
                          {REPORT_TYPE_LABELS[report.report_type!]}
                        </span>
                        <Badge variant={statusVariant(report.status as ReportStatus)} className="text-xs">
                          {REPORT_STATUS_LABELS[report.status as ReportStatus]}
                        </Badge>
                      </div>
                      <div className="flex items-center gap-3 mt-1 text-xs" style={{ color: "var(--cs-text-muted)" }}>
                        <span className="flex items-center gap-1">
                          <Calendar className="h-3 w-3" />
                          {report.date_range_start} — {report.date_range_end}
                        </span>
                        {report.child_voice_included && (
                          <span className="flex items-center gap-1 text-blue-600">
                            <Quote className="h-3 w-3" /> Voice included
                          </span>
                        )}
                        {(report.evidence_gap_count ?? 0) > 0 && (
                          <span className="flex items-center gap-1 text-amber-600">
                            <AlertTriangle className="h-3 w-3" /> {report.evidence_gap_count} gaps
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                  <div className="text-right ml-4">
                    <p className="text-lg font-semibold" style={{ color: "var(--cs-navy)" }}>
                      {report.overall_confidence_score}%
                    </p>
                    <p className="text-xs" style={{ color: "var(--cs-text-muted)" }}>Confidence</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </Link>
        ))}
      </div>
    </PageShell>
  );
}
