// ══════════════════════════════════════════════════════════════════════════════
// Cara — REPORT FILING INTEGRATION
//
// Bridges Cara Reports to the existing Filing Cabinet system. When a report
// is locked, this service creates a filing record in the correct location
// within Cara's filing cabinet hierarchy.
//
// Filing paths follow the pattern:
//   young-people/{child_id}/cara-reports/{report_type}/{date}
//
// Server-side only — never import in client components.
// ══════════════════════════════════════════════════════════════════════════════

import { createServerClient } from "@/lib/supabase/server";
import type { ChildReport, ReportType } from "@/types/cara-reports";
import { REPORT_TYPE_LABELS } from "@/types/cara-reports";
import { writeCaraAudit } from "@/lib/cara/audit/cara-audit";

// ── Filing Path Templates ──────────────────────────────────────────────────

const REPORT_FILING_PATHS: Record<ReportType, string> = {
  weekly_child_report: "young-people/{child_id}/cara-reports/weekly/{date}",
  child_review_report: "young-people/{child_id}/cara-reports/reviews/{date}",
  social_worker_update: "young-people/{child_id}/social-worker-updates/{date}",
  monthly_progress_summary: "young-people/{child_id}/cara-reports/monthly/{date}",
  risk_review_report: "young-people/{child_id}/risk-assessments/{date}",
  keywork_progress_report: "young-people/{child_id}/cara-reports/keywork/{date}",
  placement_stability_report: "young-people/{child_id}/cara-reports/placement/{date}",
  education_health_summary: "young-people/{child_id}/cara-reports/education-health/{date}",
  end_of_placement_transition_report: "young-people/{child_id}/cara-reports/transition/{date}",
};

// ── Build Filing Path ──────────────────────────────────────────────────────

export function buildReportFilingPath(report: ChildReport): string {
  const template = REPORT_FILING_PATHS[report.report_type]
    ?? "young-people/{child_id}/cara-reports/other/{date}";

  const date = (report.locked_at ?? report.created_at).slice(0, 10);

  return template
    .replace("{child_id}", report.child_id)
    .replace("{date}", date);
}

// ── File a Locked Report ───────────────────────────────────────────────────

export interface ReportFilingResult {
  success: boolean;
  filingPath: string | null;
  documentId: string | null;
}

export async function fileLockedReport(
  reportId: string,
): Promise<ReportFilingResult> {
  const sb = createServerClient();

  if (!sb) {
    // Demo mode — return a simulated filing result
    return {
      success: true,
      filingPath: `young-people/demo-child/cara-reports/weekly/${new Date().toISOString().slice(0, 10)}`,
      documentId: `doc-demo-${Date.now()}`,
    };
  }

  // Fetch the report
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: report, error: fetchErr } = await (sb.from("child_reports") as any)
    .select("*")
    .eq("id", reportId)
    .single();

  if (fetchErr || !report) {
    console.error("[cara-filing] Failed to fetch report:", fetchErr);
    return { success: false, filingPath: null, documentId: null };
  }

  // Only file locked or archived reports
  if (report.status !== "locked" && report.status !== "archived") {
    console.warn(`[cara-filing] Report ${reportId} is not locked (status: ${report.status})`);
    return { success: false, filingPath: null, documentId: null };
  }

  const typedReport = report as ChildReport;
  const filingPath = buildReportFilingPath(typedReport);

  // Create a document record in the filing cabinet
  const typeLabel = REPORT_TYPE_LABELS[typedReport.report_type] ?? typedReport.report_type;
  const dateRange = `${typedReport.date_range_start} to ${typedReport.date_range_end}`;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: doc, error: insertErr } = await (sb.from("documents") as any)
    .insert({
      home_id: typedReport.home_id,
      title: typedReport.title,
      description: `${typeLabel} covering ${dateRange}. Generated by Cara and approved by ${typedReport.approved_by ?? "manager"}.`,
      file_path: filingPath,
      category: "aria_report",
      child_id: typedReport.child_id,
      source_module: "aria_reports",
      source_record_id: reportId,
      status: "filed",
      created_by: typedReport.locked_by ?? typedReport.requested_by,
    })
    .select("id")
    .single();

  if (insertErr || !doc) {
    console.error("[cara-filing] Failed to create document record:", insertErr);
    return { success: false, filingPath, documentId: null };
  }

  // Update the report with the filing reference
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  await (sb.from("child_reports") as any)
    .update({ filed_document_id: doc.id })
    .eq("id", reportId);

  // Audit log
  await writeCaraAudit({
    organisationId: typedReport.organisation_id,
    homeId: typedReport.home_id,
    childId: typedReport.child_id,
    actorId: typedReport.locked_by ?? "system",
    eventType: "report_filed",
    entityType: "report",
    entityId: reportId,
    summary: `Report "${typedReport.title}" filed to ${filingPath}`,
    metadata: { documentId: doc.id, filingPath },
  });

  return { success: true, filingPath, documentId: doc.id };
}

// ── Get Filing Path (preview) ──────────────────────────────────────────────

export function previewFilingPath(report: ChildReport): string {
  return buildReportFilingPath(report);
}
