import { chromium } from "playwright";
const URL = "https://cornerstone-v2-fresh.vercel.app";
const b = await chromium.launch();
const pg = await b.newPage();
const errs = [];
pg.on("pageerror", e => errs.push("PAGEERROR: " + (e.message||e)));
pg.on("console", m => { if (m.type()==="error") errs.push("CONSOLE.ERR: " + m.text().slice(0,160)); });
await pg.goto(URL + "/dashboard", { waitUntil: "networkidle", timeout: 45000 }).catch(e=>errs.push("GOTO: "+e.message));
await pg.waitForTimeout(2500);
const bodyLen = (await pg.content()).length;
console.log("loaded /dashboard, html length:", bodyLen);
console.log("errors captured:", errs.length);
errs.slice(0,12).forEach(e=>console.log("  "+e));
await b.close();
