// ══════════════════════════════════════════════════════════════════════════════
// CORNERSTONE — NAVIGATION CONFIG
// Single source of truth for all navigation structure.
// Maps to existing page routes — reorganised under 8 top-level categories.
// ══════════════════════════════════════════════════════════════════════════════

export interface NavChild {
  label:     string;
  href:      string;
  icon?:     string;
  module?:   string;
  badgeKey?: "tasks" | "incidents" | "forms";
  badge?:    number;
}

export interface NavGroup {
  id:       string;
  label:    string;
  icon:     string;
  href:     string;
  module?:  string;
  children: NavChild[];
}

export const NAV_GROUPS: NavGroup[] = [
  // ── 1. Today ──────────────────────────────────────────────────────────────
  {
    id:     "today",
    label:  "Today",
    icon:   "LayoutDashboard",
    href:   "/dashboard",
    module: "dashboard",
    children: [
      { label: "Command Centre",  href: "/dashboard",       icon: "LayoutDashboard", module: "dashboard"  },
      { label: "My Day",          href: "/dashboard/my-day",icon: "Target",          module: "my-day"     },
      { label: "Staff Dashboard", href: "/dashboard/staff", icon: "User",            module: "dashboard"  },
      { label: "Handover",        href: "/handover",        icon: "ArrowRightLeft",  module: "handover"   },
      { label: "My Tasks",        href: "/tasks",           icon: "CheckSquare",     module: "tasks",     badgeKey: "tasks" },
      { label: "Notifications",  href: "/notifications",   icon: "Bell",            module: "dashboard"  },
      { label: "Shift Notes",    href: "/shift-notes",     icon: "FileText",        module: "dashboard"  },
      { label: "Duty Log",       href: "/duty-log",        icon: "BookOpen",        module: "dashboard"  },
      { label: "Sleep Log",       href: "/sleep-log",       icon: "Moon",            module: "dashboard"  },
      { label: "Activity Log",    href: "/activity-log",    icon: "Activity",        module: "dashboard"  },
      { label: "Risk Briefing",  href: "/daily-risk-briefing",icon: "ShieldAlert",    module: "dashboard"  },
      { label: "Night Log",      href: "/night-log",          icon: "Moon",           module: "dashboard"  },
    ],
  },

  // ── 2. Children ───────────────────────────────────────────────────────────
  {
    id:     "children",
    label:  "Children",
    icon:   "HeartHandshake",
    href:   "/young-people",
    module: "young-people",
    children: [
      { label: "Child Profiles",   href: "/young-people",              icon: "Heart",          module: "young-people"  },
      { label: "Care Plans",       href: "/care-plans",                icon: "ClipboardList",  module: "young-people"  },
      { label: "Daily Records",    href: "/daily-log",                 icon: "BookOpen",       module: "daily-log"     },
      { label: "Incidents",        href: "/incidents",                 icon: "AlertTriangle",  module: "incidents",    badgeKey: "incidents" },
      { label: "PI Debriefs",      href: "/incidents/pi-debriefs",     icon: "ShieldAlert",    module: "incidents"     },
      { label: "Complaints",       href: "/complaints",                icon: "MessageCircle",  module: "incidents"     },
      { label: "Missing from Care",href: "/missing-from-care",         icon: "MapPin",         module: "safeguarding"  },
      { label: "Safeguarding",     href: "/safeguarding",              icon: "Shield",         module: "safeguarding"  },
      { label: "Risk Register",   href: "/risk-register",             icon: "ShieldAlert",    module: "safeguarding"  },
      { label: "Welfare Checks",  href: "/welfare-checks",            icon: "Moon",           module: "safeguarding"  },
      { label: "Night Checks",   href: "/night-checks",              icon: "CloudMoon",      module: "safeguarding"  },
      { label: "Outcomes",        href: "/outcomes",                  icon: "Target",         module: "young-people"  },
      { label: "Interventions",  href: "/interventions",             icon: "Activity",       module: "young-people"  },
      { label: "Activities",     href: "/activities",                icon: "Palette",        module: "young-people"  },
      { label: "Voice of Child", href: "/voice",                     icon: "Mic",            module: "young-people"  },
      { label: "Relational",    href: "/relational",                icon: "Heart",          module: "young-people"  },
      { label: "Medication",       href: "/medication",                icon: "Pill",           module: "medication"    },
      { label: "Family Contact",   href: "/family-contact",            icon: "PhoneCall",      module: "young-people"  },
      { label: "Pocket Money",    href: "/pocket-money",              icon: "Wallet",         module: "young-people"  },
      { label: "Body Map",        href: "/body-map",                  icon: "PersonStanding", module: "safeguarding"  },
      { label: "Education",       href: "/education",                 icon: "GraduationCap",  module: "young-people"  },
      { label: "Appointments",    href: "/appointments",              icon: "CalendarDays",   module: "young-people"  },
      { label: "Health Records",  href: "/health-records",           icon: "Stethoscope",    module: "young-people"  },
      { label: "Sanctions & Rewards", href: "/sanctions-rewards",     icon: "Award",          module: "young-people"  },
      { label: "Correspondence",  href: "/correspondence",           icon: "Mail",           module: "young-people"  },
      { label: "Placement Plan",  href: "/placement-plan",           icon: "ListChecks",     module: "young-people"  },
      { label: "Transition Plan", href: "/transition-planning",     icon: "ArrowRightLeft", module: "young-people"  },
      { label: "Key Working",     href: "/key-working",              icon: "MessageSquare",  module: "young-people"  },
      { label: "Behaviour Log",   href: "/behaviour-log",            icon: "Activity",       module: "young-people"  },
      { label: "Contact Directory",href: "/contact-directory",        icon: "Phone",          module: "young-people"  },
      { label: "Consent Records", href: "/consent-records",           icon: "FileCheck",      module: "young-people"  },
      { label: "Significant Events",href: "/significant-events",      icon: "Flag",           module: "young-people"  },
      { label: "LAC Reviews",    href: "/lac-reviews",              icon: "Gavel",          module: "young-people"  },
      { label: "Admissions",     href: "/admissions",               icon: "UserPlus",       module: "young-people"  },
      { label: "Risk Assessments",href: "/risk-assessments",         icon: "ShieldAlert",    module: "safeguarding"  },
      { label: "Consultations", href: "/professional-consultations",icon: "Stethoscope",   module: "young-people"  },
      { label: "Debriefs",      href: "/debriefs",                  icon: "RefreshCw",     module: "young-people"  },
      { label: "Restraint Log", href: "/restraint-log",             icon: "ShieldAlert",   module: "safeguarding"  },
      { label: "Grab Bags",    href: "/grab-bag",                  icon: "Briefcase",     module: "safeguarding"  },
      { label: "Absence Tracking",href: "/absence-tracking",         icon: "CalendarX",     module: "young-people"  },
      { label: "Placement Stability",href: "/placement-stability",   icon: "Home",          module: "young-people"  },
      { label: "Impact Assessments",href: "/impact-assessments",    icon: "Scale",         module: "young-people"  },
      { label: "Delegated Authority",href: "/delegated-authority",  icon: "KeyRound",      module: "young-people"  },
      { label: "Positive Handling",href: "/positive-handling",     icon: "HandMetal",     module: "safeguarding"  },
      { label: "Cultural Identity",href: "/cultural-identity",   icon: "Globe",         module: "young-people"  },
      { label: "Independence Skills",href: "/independence-skills",icon: "Star",          module: "young-people"  },
      { label: "Matching & Referrals",href: "/matching-referrals",icon: "Scale",        module: "young-people"  },
      { label: "Multi-Agency Meetings",href: "/multi-agency-meetings",icon: "Users",    module: "young-people"  },
      { label: "Therapeutic Input",href: "/therapeutic-input",    icon: "Heart",         module: "young-people"  },
      { label: "Clothing & Allowances",href: "/clothing-allowances",icon: "Shirt",     module: "young-people"  },
      { label: "Online Safety",    href: "/online-safety",          icon: "Shield",        module: "safeguarding"  },
      { label: "Restrictions Log", href: "/restrictions-log",       icon: "Lock",          module: "safeguarding"  },
      { label: "YP Savings",       href: "/yp-savings",             icon: "PiggyBank",     module: "young-people"  },
      { label: "Advocacy",         href: "/advocacy",               icon: "Scale",         module: "young-people"  },
      { label: "Health Assessments",href: "/health-assessments",    icon: "Stethoscope",   module: "young-people"  },
      { label: "Personal Belongings",href: "/personal-belongings",  icon: "Package",       module: "young-people"  },
      { label: "Discharge",        href: "/discharge",              icon: "LogOut",        module: "young-people"  },
      { label: "Sensory Profiles", href: "/sensory-profiles",       icon: "Ear",           module: "young-people"  },
      { label: "Peer Relationships",href: "/peer-relationships",   icon: "Users",         module: "young-people"  },
      { label: "Contact Supervision",href: "/contact-supervision", icon: "Eye",           module: "young-people"  },
      { label: "Attachment Profiles",href: "/attachment-profiles",  icon: "Heart",         module: "young-people"  },
      { label: "Children's Meetings",href: "/childrens-meetings",  icon: "MessageCircle", module: "young-people"  },
      { label: "YP Feedback",      href: "/yp-feedback",            icon: "MessageSquare", module: "young-people"  },
      { label: "Medication Errors",href: "/medication-errors",    icon: "Pill",          module: "young-people"  },
      { label: "Room Searches",   href: "/room-searches",         icon: "Search",        module: "safeguarding"  },
      { label: "Behaviour Support",href: "/behaviour-support-plans",icon: "Shield",       module: "young-people"  },
      { label: "SW Contact Log",  href: "/social-worker-contact",icon: "Phone",         module: "young-people"  },
      { label: "After-Care",      href: "/after-care",            icon: "Heart",         module: "young-people"  },
      { label: "Device Policy",    href: "/device-policy",         icon: "Smartphone",    module: "young-people"  },
      { label: "Health Monitoring",href: "/health-monitoring",     icon: "Stethoscope",   module: "young-people"  },
      { label: "Risk Mgmt Plans", href: "/risk-management-plans", icon: "ShieldAlert",   module: "safeguarding"  },
      { label: "Exploitation Screening",href: "/exploitation-screening",icon: "Shield",       module: "safeguarding"  },
      { label: "Medication Audit", href: "/medication-audit",      icon: "Pill",          module: "young-people"  },
      { label: "Photo Consent",    href: "/photo-consent",         icon: "Camera",        module: "young-people"  },
      { label: "Gifts Register",   href: "/gifts-register",        icon: "Gift",          module: "young-people"  },
      { label: "YP Agreements",    href: "/service-user-agreements",icon: "FileText",      module: "young-people"  },
      { label: "Contextual Safeguarding",href: "/contextual-safeguarding",icon: "MapPin",    module: "safeguarding"  },
      { label: "Pocket Money Accounts",href: "/pocket-money-accounts",icon: "Wallet",        module: "young-people"  },
      { label: "Missing Education",href: "/children-missing-education",icon: "GraduationCap", module: "young-people"  },
      { label: "Parent Partnership",href: "/parent-partnership",       icon: "Heart",         module: "young-people"  },
      { label: "Outcome Star",    href: "/outcome-star",              icon: "Star",          module: "young-people"  },
      { label: "PEP Tracker",    href: "/pep-tracker",               icon: "GraduationCap", module: "young-people"  },
      { label: "Children's Rights",href: "/childrens-rights",         icon: "Shield",        module: "young-people"  },
      { label: "Referral Tracker",href: "/referral-tracker",          icon: "UserPlus",      module: "young-people"  },
      { label: "Language & Comms",href: "/language-communication",    icon: "MessageCircle", module: "young-people"  },
      { label: "Health Passports",href: "/health-passports",          icon: "Stethoscope",   module: "young-people"  },
      { label: "Emergency Placements",href: "/emergency-placements",  icon: "AlertTriangle", module: "young-people"  },
      { label: "Behaviour Mapping",href: "/behaviour-mapping",        icon: "Activity",      module: "young-people"  },
      { label: "Positive Achievements",href: "/positive-achievements",icon: "Award",         module: "young-people"  },
      { label: "Sleep Assessments",href: "/sleep-assessments",        icon: "Moon",          module: "young-people"  },
      { label: "Return Interviews",href: "/missing-return-interviews", icon: "MapPin",        module: "young-people"  },
      { label: "Contact Plans",    href: "/contact-plans",             icon: "Phone",         module: "young-people"  },
      { label: "Participation Log",href: "/child-participation-log",   icon: "MessageCircle", module: "young-people"  },
      { label: "Placement Impact", href: "/placement-impact-assessment",icon: "Scale",         module: "young-people"  },
      { label: "Independence Pathway",href: "/independence-pathway",   icon: "TrendingUp",    module: "young-people"  },
      { label: "Daily Routines",    href: "/daily-routine-plans",       icon: "Clock",          module: "young-people"  },
      { label: "Stability Meetings",href: "/placement-stability-meetings",icon: "Users",        module: "young-people"  },
      { label: "Trauma Timeline",   href: "/trauma-informed-timeline",  icon: "Heart",          module: "young-people"  },
      { label: "Professional Network",href: "/professional-network-map",icon: "Network",       module: "young-people"  },
      { label: "Children's Pledges",href: "/children-pledges",          icon: "Heart",          module: "young-people"  },
      { label: "Pre-Admission",    href: "/pre-admission-checklist",   icon: "FileCheck",      module: "young-people"  },
      { label: "Community Engagement",href: "/community-engagement-log",icon: "Globe",         module: "young-people"  },
      { label: "Placement End Summary",href: "/placement-end-summary",  icon: "Heart",         module: "young-people"  },
      { label: "CP Conferences",   href: "/child-protection-conferences",icon: "Shield",       module: "safeguarding"  },
      { label: "MAR Sheet",        href: "/mar-sheet",                 icon: "Pill",           module: "medication"    },
      { label: "Child-Friendly Policies",href: "/child-friendly-policies",icon: "BookOpen",   module: "young-people"  },
      { label: "Education Attendance",href: "/education-attendance-tracker",icon: "GraduationCap",module: "young-people"  },
      { label: "Bedtime Routines", href: "/bedtime-routines",          icon: "Moon",           module: "young-people"  },
      { label: "Wake-Up Routines", href: "/wake-up-routines",          icon: "Sun",            module: "young-people"  },
      { label: "Statutory Visits", href: "/statutory-visit-log",       icon: "Calendar",       module: "young-people"  },
      { label: "MDT Formulations", href: "/multi-disciplinary-formulation",icon: "Brain",     module: "young-people"  },
      { label: "Injury Log",       href: "/child-injuries-log",        icon: "PersonStanding", module: "young-people"  },
      { label: "Placement Meetings",href: "/placement-meeting-minutes", icon: "Users",         module: "young-people"  },
      { label: "Safe Touch",       href: "/safe-touch-protocol",       icon: "HandMetal",      module: "young-people"  },
      { label: "Adoption Support", href: "/adoption-support-records",  icon: "Heart",          module: "young-people"  },
      { label: "Pathway Plan (16+)",href: "/pathway-plan-16plus",      icon: "Milestone",      module: "young-people"  },
      { label: "Family Time",      href: "/family-time-supervision",   icon: "PhoneCall",      module: "young-people"  },
      { label: "Outcome Measures", href: "/therapeutic-outcome-measures",icon: "Activity",     module: "young-people"  },
      { label: "Healthcare Plans", href: "/healthcare-plans",          icon: "Stethoscope",    module: "young-people"  },
      { label: "EHCP Tracker",     href: "/ehcp-tracker",              icon: "GraduationCap",  module: "young-people"  },
      { label: "Hate Incidents",   href: "/hate-incident-log",         icon: "ShieldAlert",    module: "safeguarding"  },
      { label: "IRO Correspondence",href: "/iro-correspondence",       icon: "Mail",           module: "young-people"  },
      { label: "Personal Passport",href: "/personal-passport",         icon: "Sparkles",       module: "young-people"  },
      { label: "Life Story",        href: "/life-story",                icon: "BookHeart",      module: "young-people"  },
      { label: "Chronology",       href: "/intelligence/chronology",   icon: "ScrollText",     module: "young-people"  },
      { label: "Documents",        href: "/documents",                 icon: "FileText",       module: "documents"     },
      { label: "Care Forms",       href: "/forms",                     icon: "FileCheck",      module: "forms",        badgeKey: "forms" },
    ],
  },

  // ── 3. Team ───────────────────────────────────────────────────────────────
  {
    id:     "team",
    label:  "Team",
    icon:   "Users",
    href:   "/staff",
    module: "staff",
    children: [
      { label: "Staff Profiles",       href: "/staff",                       icon: "Users",         module: "staff"        },
      { label: "Rota",                 href: "/rota",                        icon: "Calendar",      module: "rota"         },
      { label: "Supervision",          href: "/supervision",                 icon: "MessageSquare", module: "supervision"  },
      { label: "Training",             href: "/training",                    icon: "GraduationCap", module: "training"     },
      { label: "Safer Recruitment",    href: "/recruitment",                 icon: "UserCheck",     module: "recruitment"  },
      { label: "DBS & Checks",         href: "/recruitment/safer-recruitment/dbs", icon: "Fingerprint", module: "recruitment" },
      { label: "Development Hub",      href: "/staff-development",           icon: "TrendingUp",    module: "staff"        },
      { label: "Workforce Intel",      href: "/workforce",                   icon: "Network",       module: "staff"        },
      { label: "Career Pathways",      href: "/workforce/pathway",           icon: "Milestone",     module: "staff"        },
      { label: "Appraisals",           href: "/workforce/appraisals",        icon: "UserCheck",     module: "staff"        },
      { label: "Leave & Absence",      href: "/leave",                       icon: "CalendarDays",  module: "leave"        },
      { label: "Timesheets",           href: "/timesheets",                  icon: "Clock",         module: "timesheets"   },
      { label: "Staff Meetings",       href: "/staff-meetings",              icon: "MessageSquare", module: "staff"        },
      { label: "Staff Wellbeing",     href: "/staff-wellbeing",             icon: "HeartPulse",    module: "staff"        },
      { label: "Staff Induction",    href: "/staff-induction",             icon: "UserCheck",     module: "staff"        },
      { label: "Staff Grievances", href: "/staff-grievances",            icon: "FileWarning",   module: "staff"        },
      { label: "Staff Disciplinary",href: "/staff-disciplinary",        icon: "Gavel",         module: "staff"        },
      { label: "Sleep-In Log",    href: "/sleep-in-log",              icon: "Moon",          module: "staff"        },
      { label: "Staff Reflections",href: "/staff-reflections",        icon: "Heart",         module: "staff"        },
      { label: "Supervision Tracker",href: "/supervision-tracker",    icon: "Calendar",      module: "staff"        },
      { label: "Medication Training",href: "/medication-training",    icon: "GraduationCap", module: "training"     },
      { label: "Night Staff Guide",href: "/night-staff-guidance",    icon: "Moon",          module: "staff"        },
      { label: "Lone Working",   href: "/lone-working",           icon: "UserCheck",     module: "staff"        },
      { label: "Agency Staff Log",href: "/agency-staff-log",      icon: "Users",         module: "staff"        },
      { label: "Staff Sickness",href: "/staff-sickness",          icon: "UserMinus",     module: "staff"        },
      { label: "Staff Handbook",href: "/staff-handbook",            icon: "BookOpen",      module: "staff"        },
      { label: "Annual Reviews",href: "/annual-development-reviews",icon: "TrendingUp",    module: "staff"        },
      { label: "Exit Interviews",href: "/staff-exit-interviews",     icon: "LogOut",        module: "staff"        },
      { label: "Supervision Matrix",href: "/supervision-matrix",     icon: "Network",       module: "staff"        },
      { label: "Staff Debriefs",href: "/staff-debrief-log",          icon: "Heart",         module: "staff"        },
      { label: "Staff Competency",href: "/staff-competency",          icon: "CheckSquare",   module: "staff"        },
      { label: "Professional Development",href: "/professional-development",icon: "BookOpen",      module: "staff"        },
      { label: "Staffing Plan (Reg 40)",href: "/reg40-staffing-plan",    icon: "Users",         module: "staff"        },
      { label: "Handbook Sign-Off",href: "/staff-handbook-acknowledgements",icon: "FileCheck",    module: "staff"        },
      { label: "Safer Caring",  href: "/staff-safer-caring",          icon: "Shield",        module: "staff"        },
      { label: "Care Model",    href: "/therapeutic-care-model",      icon: "Heart",         module: "staff"        },
      { label: "Comms Preferences",href: "/staff-communication-preferences",icon: "MessageSquare",module: "staff"      },
      { label: "Supervision Themes",href: "/staff-supervision-themes",  icon: "Network",       module: "staff"        },
      { label: "Safeguarding Supervision",href: "/safeguarding-supervision",icon: "Shield",   module: "staff"        },
      { label: "Night Handover",  href: "/night-staff-handover",        icon: "Moon",          module: "staff"        },
      { label: "Recruitment Tracker",href: "/safer-recruitment-tracker",icon: "UserCheck",    module: "recruitment"  },
      { label: "Shadow Shifts",   href: "/staff-shadowing-log",         icon: "Eye",           module: "staff"        },
      { label: "Lone Working RA", href: "/lone-working-risk-assessment",icon: "UserCheck",     module: "staff"        },
      { label: "Training Matrix", href: "/mandatory-training-matrix",  icon: "GraduationCap", module: "training"     },
    ],
  },

  // ── 4. Home ───────────────────────────────────────────────────────────────
  {
    id:     "home",
    label:  "Home",
    icon:   "Building2",
    href:   "/buildings",
    module: "buildings",
    children: [
      { label: "Buildings & H&S",  href: "/buildings",   icon: "Building2", module: "buildings"  },
      { label: "Vehicles",         href: "/vehicles",    icon: "Car",        module: "vehicles"   },
      { label: "Maintenance",      href: "/maintenance", icon: "Wrench",     module: "maintenance"},
      { label: "Expenses",         href: "/expenses",    icon: "Receipt",    module: "expenses"   },
      { label: "Visitor Log",      href: "/visitor-log", icon: "ClipboardList", module: "buildings"},
      { label: "Fire Drills",     href: "/fire-drills", icon: "Flame",         module: "buildings"},
      { label: "House Meetings",  href: "/house-meetings", icon: "Users",      module: "buildings"},
      { label: "Menu Planning",   href: "/menu-planning",  icon: "UtensilsCrossed", module: "buildings"},
      { label: "Petty Cash",     href: "/petty-cash",     icon: "Wallet",          module: "expenses"},
      { label: "Inventory",     href: "/inventory",      icon: "Package",         module: "buildings"},
      { label: "Children's Guide",href: "/childrens-guide",icon: "BookOpen",        module: "buildings"},
      { label: "Emergency Plans",href: "/emergency-planning",icon: "AlertOctagon",   module: "buildings"},
      { label: "Secure Storage",href: "/secure-storage",    icon: "Lock",            module: "buildings"},
      { label: "CCTV Log",     href: "/cctv-log",          icon: "Video",           module: "buildings"},
      { label: "Comms Book",   href: "/communication-book",icon: "MessageSquare",   module: "buildings"},
      { label: "Environmental Risk",href: "/environmental-risk",icon: "TreePine",       module: "buildings"},
      { label: "Transport Log",   href: "/transport-log",      icon: "Car",            module: "buildings"},
      { label: "Holiday Planning",href: "/holiday-planning",   icon: "MapPin",         module: "buildings"},
      { label: "Keyholding Register",href: "/keyholding-register",icon: "Key",          module: "buildings"},
      { label: "Accident Book",  href: "/accident-book",        icon: "HardHat",         module: "buildings"},
      { label: "Water Hygiene",  href: "/water-hygiene",        icon: "Droplets",        module: "buildings"},
      { label: "Food Hygiene",  href: "/food-hygiene",         icon: "UtensilsCrossed", module: "buildings"},
      { label: "Property Damage",href: "/property-damage",     icon: "Hammer",          module: "buildings"},
      { label: "Emergency Contacts",href: "/emergency-contacts",icon: "Phone",           module: "buildings"},
      { label: "Infection Control",href: "/infection-control",  icon: "Bug",             module: "buildings"},
      { label: "Business Continuity",href: "/business-continuity",icon: "AlertOctagon",    module: "buildings"},
      { label: "Utility Monitoring",href: "/utility-monitoring",   icon: "Zap",             module: "buildings"},
      { label: "Medication Stock",href: "/medication-stock-check", icon: "Pill",            module: "buildings"},
      { label: "Diversity Calendar",href: "/diversity-calendar",   icon: "Globe",           module: "buildings"},
      { label: "Visitors Feedback",href: "/visitors-feedback",    icon: "MessageSquare",   module: "buildings"},
      { label: "Local Offer",     href: "/local-offer",           icon: "Home",            module: "buildings"},
      { label: "House Rules",    href: "/house-rules",            icon: "BookOpen",        module: "buildings"},
      { label: "Welcome Packs", href: "/warm-welcome-packs",      icon: "Gift",            module: "buildings"},
      { label: "Consequence Framework",href: "/consequence-framework", icon: "Heart",           module: "buildings"},
      { label: "Protocol Drills",href: "/emergency-protocol-drills",   icon: "AlertOctagon",    module: "buildings"},
      { label: "Fire Risk Assessment",href: "/fire-risk-assessment",   icon: "Flame",           module: "buildings"},
      { label: "External Visitors",href: "/external-visitor-log",      icon: "Users",           module: "buildings"},
    ],
  },

  // ── 5. Compliance ─────────────────────────────────────────────────────────
  {
    id:     "compliance",
    label:  "Compliance",
    icon:   "ShieldCheck",
    href:   "/ri",
    module: "ri",
    children: [
      { label: "RI Command Centre",   href: "/ri",                   icon: "Gavel",         module: "ri"         },
      { label: "Key Dates",           href: "/key-dates",            icon: "CalendarDays",  module: "ri"         },
      { label: "Governance Scorecard",href: "/ri/scorecard",         icon: "BarChart3",     module: "ri"         },
      { label: "Reg 44 Visits",       href: "/ri/reg44",             icon: "Eye",           module: "ri"         },
      { label: "Reg 45 Engine",       href: "/ri/reg45",             icon: "FileText",      module: "ri"         },
      { label: "Ofsted Readiness",    href: "/ri/ofsted",            icon: "Award",         module: "ri"         },
      { label: "Challenge Log",       href: "/ri/challenge-log",     icon: "Flag",          module: "ri"         },
      { label: "Policies",             href: "/policies",             icon: "FileText",      module: "ri"         },
      { label: "Audits",              href: "/audits",               icon: "ClipboardCheck",module: "audits"     },
      { label: "Inspection",          href: "/inspection",           icon: "Award",         module: "inspection" },
      { label: "RI Alerts",           href: "/ri/alerts",            icon: "AlertTriangle", module: "ri"         },
      { label: "Governance Reports", href: "/ri/governance",        icon: "ScrollText",    module: "ri"         },
      { label: "Quality of Care",  href: "/quality-of-care",      icon: "Star",          module: "ri"         },
      { label: "Feedback",         href: "/stakeholder-feedback", icon: "MessageSquare", module: "ri"         },
      { label: "Notifiable Events",href: "/notifiable-events",    icon: "Bell",          module: "ri"         },
      { label: "Compliments",      href: "/compliments",          icon: "Award",         module: "ri"         },
      { label: "Locality Risk",    href: "/locality-risk",        icon: "MapPin",        module: "ri"         },
      { label: "Statement of Purpose",href: "/statement-of-purpose",icon: "FileText",     module: "ri"         },
      { label: "Location Assessment",href: "/location-assessment",  icon: "MapPin",        module: "ri"         },
      { label: "Visitor Reports",  href: "/independent-visitor",  icon: "Eye",           module: "ri"         },
      { label: "Whistleblowing",  href: "/whistleblowing",       icon: "ShieldAlert",   module: "ri"         },
      { label: "Equality & Diversity",href: "/equality-diversity",icon: "Equal",         module: "ri"         },
      { label: "Data Protection",  href: "/data-protection",    icon: "Lock",          module: "ri"         },
      { label: "Serious Incident Reviews",href: "/serious-incident-reviews",icon: "FileSearch",  module: "ri"         },
      { label: "LADO Referrals",href: "/lado-referrals",          icon: "UserX",           module: "ri"         },
      { label: "Reg 44 Actions",href: "/reg44-actions",          icon: "ListChecks",      module: "ri"         },
      { label: "Prevent Duty",  href: "/prevent-duty",           icon: "Shield",          module: "ri"         },
      { label: "Complaints Outcomes",href: "/complaints-outcomes",icon: "MessageSquare",  module: "ri"         },
      { label: "Reg 35 Notifications",href: "/reg35-notifications",icon: "Bell",          module: "ri"         },
      { label: "Subject Access Requests",href: "/subject-access-requests",icon: "Lock",   module: "ri"         },
      { label: "Incident Debriefs",href: "/critical-incident-debrief",icon: "Brain",         module: "ri"         },
      { label: "Deprivation of Liberty",href: "/deprivation-of-liberty",icon: "Lock",         module: "ri"         },
      { label: "Improvement Plan",href: "/home-improvement-plan",     icon: "TrendingUp",    module: "ri"         },
      { label: "Ofsted Action Plan",href: "/ofsted-action-plan",     icon: "Award",         module: "ri"         },
      { label: "Reg 22 Records",href: "/reg22-records",              icon: "FileText",      module: "ri"         },
      { label: "QA Audit",      href: "/qa-audit",                   icon: "ClipboardCheck",module: "ri"         },
      { label: "Quality Review (Reg 46)",href: "/quality-review-cycle",  icon: "Star",          module: "ri"         },
      { label: "Document Expiry",href: "/document-expiry-tracker",      icon: "Clock",         module: "ri"         },
      { label: "Policy Reviews", href: "/policy-review-tracker",        icon: "FileText",      module: "ri"         },
      { label: "Reg 44 Reports",href: "/reg44-visitor-reports",        icon: "Eye",           module: "ri"         },
      { label: "Escalation Tracker",href: "/escalation-tracker",       icon: "ArrowUp",       module: "ri"         },
      { label: "Notification Log",href: "/notification-log",           icon: "Bell",          module: "ri"         },
      { label: "Risk Appetite",   href: "/risk-appetite-statement",    icon: "Shield",        module: "ri"         },
      { label: "Ofsted Self-Eval",href: "/ofsted-self-evaluation",     icon: "Award",         module: "ri"         },
      { label: "Governance Minutes",href: "/governance-meeting-minutes", icon: "ScrollText",    module: "ri"         },
      { label: "Unannounced Visits",href: "/unannounced-visits-log",    icon: "Eye",           module: "ri"         },
      { label: "Commissioning Feedback",href: "/commissioning-feedback",icon: "MessageSquare", module: "ri"         },
      { label: "Incident Trends",href: "/incident-trend-analysis",     icon: "BarChart3",     module: "ri"         },
      { label: "Complaint Trends",href: "/complaints-trend-analysis",  icon: "TrendingUp",    module: "ri"         },
      { label: "Case File Audit", href: "/case-file-audit",            icon: "ClipboardCheck",module: "ri"         },
      { label: "WB Investigations",href: "/whistleblowing-investigations",icon: "ShieldAlert",module: "ri"         },
      { label: "Lessons Learned",  href: "/lessons-learned-register",   icon: "Lightbulb",     module: "ri"         },
      { label: "Improvement Board",href: "/service-improvement-board", icon: "Target",        module: "ri"         },
      { label: "Resolution Meetings",href: "/complaint-resolution-meetings",icon: "MessageCircle",module: "ri"      },
    ],
  },

  // ── 6. Reports ────────────────────────────────────────────────────────────
  {
    id:     "reports",
    label:  "Reports",
    icon:   "BarChart3",
    href:   "/reports",
    module: "reports",
    children: [
      { label: "Reports Hub",       href: "/reports",                        icon: "BarChart3",  module: "reports"   },
      { label: "Weekly Overview",   href: "/intelligence/weekly-overview",   icon: "BarChart2",  module: "dashboard" },
      { label: "Document Intel",    href: "/documents/intelligence",         icon: "Sparkles",   module: "documents" },
      { label: "KPI Dashboard",    href: "/kpi-dashboard",                  icon: "Target",     module: "reports"   },
      { label: "Annual Outcomes",  href: "/annual-outcomes-report",         icon: "TrendingUp", module: "reports"   },
      { label: "Success Factors",  href: "/placement-success-factors",      icon: "Star",       module: "reports"   },
    ],
  },

  // ── 7. Aria ───────────────────────────────────────────────────────────────
  {
    id:     "aria",
    label:  "Aria",
    icon:   "Sparkles",
    href:   "/intelligence",
    module: "dashboard",
    children: [
      { label: "Intelligence Hub",    href: "/intelligence",                         icon: "Brain",       module: "dashboard"    },
      { label: "Pattern Alerts",     href: "/patterns",                             icon: "Radar",       module: "dashboard"    },
      { label: "Situation Review",    href: "/intelligence/aria/situation",          icon: "Eye",         module: "dashboard"    },
      { label: "Oversight Radar",     href: "/intelligence/aria/oversight-radar",    icon: "Radar",       module: "dashboard"    },
      { label: "Oversight Writer",    href: "/intelligence/aria/oversight",          icon: "ScrollText",  module: "dashboard"    },
      { label: "Key Work Builder",    href: "/intelligence/aria/keywork",            icon: "ListChecks",  module: "young-people" },
      { label: "L.I.V.E.R.S. Planner",href: "/intelligence/aria/livers",            icon: "Layers",      module: "young-people" },
      { label: "Child Resources",     href: "/intelligence/aria/resources",          icon: "Puzzle",      module: "young-people" },
      { label: "Interactive Sessions",href: "/intelligence/aria/interactive",        icon: "PlayCircle",  module: "young-people" },
      { label: "Reflective Practice", href: "/intelligence/aria/reflective",         icon: "Heart",       module: "dashboard"    },
      { label: "Safeguarding Flags",  href: "/intelligence/aria/safeguarding",       icon: "Flag",        module: "dashboard"    },
      { label: "Recommendations",     href: "/intelligence/aria/recommendations",    icon: "Lightbulb",   module: "dashboard"    },
      { label: "Document Wizard",     href: "/intelligence/document-wizard",         icon: "Wand2",       module: "documents"    },
      { label: "Practice Bank",       href: "/intelligence/practice-bank",           icon: "BookOpen",    module: "young-people" },
      { label: "Learning Studio",     href: "/learning",                             icon: "GraduationCap",module: "learning"   },
      { label: "Audit Trail",         href: "/intelligence/aria/audit",              icon: "Activity",    module: "dashboard"    },
    ],
  },

  // ── 8. Settings ───────────────────────────────────────────────────────────
  {
    id:     "settings",
    label:  "Settings",
    icon:   "Settings",
    href:   "/settings",
    module: "dashboard",
    children: [
      { label: "Settings", href: "/settings", icon: "Settings", module: "dashboard" },
    ],
  },
];

// ── Global Create menu items ───────────────────────────────────────────────────

export interface CreateMenuItem {
  label:    string;
  icon:     string;
  href:     string;
  group:    string;
  module?:  string;
}

export const GLOBAL_CREATE_ITEMS: CreateMenuItem[] = [
  // Care
  { label: "Daily Log Entry",       icon: "BookOpen",       href: "/daily-log",          group: "Care",       module: "daily-log"    },
  { label: "Incident",              icon: "AlertTriangle",  href: "/incidents",          group: "Care",       module: "incidents"    },
  { label: "Missing from Care",     icon: "MapPin",         href: "/missing-from-care",  group: "Care",       module: "safeguarding" },
  { label: "Medication Entry",      icon: "Pill",           href: "/medication",         group: "Care",       module: "medication"   },
  { label: "Contact Log",           icon: "PhoneCall",      href: "/family-contact",     group: "Care",       module: "young-people" },
  { label: "Welfare Check",         icon: "Moon",           href: "/welfare-checks",     group: "Care",       module: "safeguarding" },
  { label: "Night Check",          icon: "CloudMoon",      href: "/night-checks",       group: "Care",       module: "safeguarding" },
  { label: "Outcome Target",       icon: "Target",         href: "/outcomes",           group: "Care",       module: "young-people" },
  { label: "Intervention",          icon: "Activity",       href: "/interventions",      group: "Care",       module: "young-people" },
  { label: "Activity Log",          icon: "Palette",        href: "/activities",         group: "Care",       module: "young-people" },
  { label: "Pocket Money",          icon: "Wallet",         href: "/pocket-money",       group: "Care",       module: "young-people" },
  { label: "Body Map",              icon: "PersonStanding", href: "/body-map",           group: "Care",       module: "safeguarding" },
  { label: "Education Entry",      icon: "GraduationCap",  href: "/education",          group: "Care",       module: "young-people" },
  { label: "Appointment",          icon: "CalendarDays",   href: "/appointments",       group: "Care",       module: "young-people" },
  { label: "Sanction / Reward",    icon: "Award",          href: "/sanctions-rewards",  group: "Care",       module: "young-people" },
  // Workflow
  { label: "Task",                  icon: "CheckSquare",    href: "/tasks",              group: "Workflow",   module: "tasks"        },
  { label: "Care Form",             icon: "FileCheck",      href: "/forms",              group: "Workflow",   module: "forms"        },
  { label: "Upload Document",       icon: "Upload",         href: "/documents",          group: "Workflow",   module: "documents"    },
  // Compliance
  { label: "Reg 45 Evidence",       icon: "ShieldCheck",    href: "/ri/reg45",           group: "Compliance", module: "ri"           },
  { label: "Complaint",             icon: "MessageCircle",  href: "/complaints",         group: "Compliance", module: "incidents"    },
  { label: "Risk Entry",            icon: "ShieldAlert",    href: "/risk-register",      group: "Compliance", module: "safeguarding" },
  // Team
  { label: "Supervision Record",    icon: "MessageSquare",  href: "/supervision",        group: "Team",       module: "supervision"  },
  { label: "Life Story Entry",       icon: "BookHeart",      href: "/life-story",         group: "Care",       module: "young-people" },
  { label: "Transition Goal",       icon: "ArrowRightLeft", href: "/transition-planning",group: "Care",       module: "young-people" },
  { label: "Key Work Session",       icon: "MessageSquare",  href: "/key-working",        group: "Care",       module: "young-people" },
  { label: "House Meeting",          icon: "Users",          href: "/house-meetings",     group: "Team",       module: "buildings"    },
  { label: "Significant Event",      icon: "Flag",           href: "/significant-events", group: "Care",       module: "young-people" },
  { label: "Consent Record",         icon: "FileCheck",      href: "/consent-records",    group: "Compliance", module: "young-people" },
  { label: "Meal Plan",              icon: "UtensilsCrossed",href: "/menu-planning",      group: "Team",       module: "buildings"    },
  { label: "Maintenance Issue",     icon: "Wrench",         href: "/maintenance",        group: "Team",       module: "maintenance"  },
  { label: "Vehicle Check",         icon: "Car",            href: "/vehicles",           group: "Team",       module: "vehicles"     },
  { label: "Visitor Entry",         icon: "ClipboardList",  href: "/visitor-log",        group: "Team",       module: "buildings"    },
  { label: "Fire Drill Record",     icon: "Flame",          href: "/fire-drills",        group: "Team",       module: "buildings"    },
  // Intelligence
  { label: "Management Oversight",  icon: "Sparkles",       href: "/intelligence/aria/oversight", group: "Aria", module: "dashboard" },
  { label: "Key Work Session",      icon: "ListChecks",     href: "/intelligence/aria/keywork",   group: "Aria", module: "young-people" },
  { label: "Consultation",          icon: "Stethoscope",    href: "/professional-consultations",  group: "Care", module: "young-people" },
  { label: "Debrief",               icon: "RefreshCw",      href: "/debriefs",                    group: "Care", module: "young-people" },
  { label: "Restraint Record",      icon: "ShieldAlert",    href: "/restraint-log",               group: "Compliance", module: "safeguarding" },
  { label: "Inventory Item",        icon: "Package",        href: "/inventory",                   group: "Team",       module: "buildings"    },
  { label: "Sleep Log Entry",       icon: "Moon",           href: "/sleep-log",                   group: "Care",       module: "dashboard"    },
  { label: "Feedback Record",       icon: "MessageSquare",  href: "/stakeholder-feedback",        group: "Compliance", module: "ri"           },
  { label: "Cultural Identity Plan",icon: "Globe",          href: "/cultural-identity",           group: "Care",       module: "young-people" },
  { label: "Independence Skill",  icon: "Star",           href: "/independence-skills",         group: "Care",       module: "young-people" },
  { label: "New Referral",        icon: "Scale",          href: "/matching-referrals",          group: "Care",       module: "young-people" },
  { label: "Secure Storage Item", icon: "Lock",           href: "/secure-storage",              group: "Team",       module: "buildings"    },
  { label: "Whistleblowing Concern",icon: "ShieldAlert",   href: "/whistleblowing",              group: "Compliance", module: "ri"           },
  { label: "Multi-Agency Meeting",icon: "Users",          href: "/multi-agency-meetings",       group: "Care",       module: "young-people" },
  { label: "Therapy Referral",    icon: "Heart",          href: "/therapeutic-input",            group: "Care",       module: "young-people" },
  { label: "Clothing Purchase",   icon: "Shirt",          href: "/clothing-allowances",          group: "Care",       module: "young-people" },
  { label: "Online Safety Incident",icon: "Shield",       href: "/online-safety",               group: "Care",       module: "safeguarding" },
  { label: "Restriction",         icon: "Lock",           href: "/restrictions-log",            group: "Care",       module: "safeguarding" },
  { label: "Savings Transaction", icon: "PiggyBank",      href: "/yp-savings",                  group: "Care",       module: "young-people" },
  { label: "CCTV Access Entry",   icon: "Video",          href: "/cctv-log",                    group: "Team",       module: "buildings"    },
  { label: "Comms Book Entry",    icon: "MessageSquare",  href: "/communication-book",          group: "Team",       module: "buildings"    },
  { label: "Advocacy Record",    icon: "Scale",          href: "/advocacy",                    group: "Care",       module: "young-people" },
  { label: "Health Assessment",  icon: "Stethoscope",    href: "/health-assessments",          group: "Care",       module: "young-people" },
  { label: "Belonging Item",     icon: "Package",        href: "/personal-belongings",         group: "Care",       module: "young-people" },
  { label: "Discharge Plan",     icon: "LogOut",         href: "/discharge",                   group: "Care",       module: "young-people" },
  { label: "Sensory Profile",    icon: "Ear",            href: "/sensory-profiles",            group: "Care",       module: "young-people" },
  { label: "Staff Grievance",    icon: "FileWarning",    href: "/staff-grievances",            group: "Team",       module: "staff"        },
  { label: "Peer Relationship Entry",icon: "Users",      href: "/peer-relationships",          group: "Care",       module: "young-people" },
  { label: "Contact Session",    icon: "Eye",            href: "/contact-supervision",         group: "Care",       module: "young-people" },
  { label: "Attachment Profile", icon: "Heart",          href: "/attachment-profiles",          group: "Care",       module: "young-people" },
  { label: "Children's Meeting", icon: "MessageCircle",  href: "/childrens-meetings",          group: "Care",       module: "young-people" },
  { label: "Staff Disciplinary Case",icon: "Gavel",       href: "/staff-disciplinary",          group: "Team",       module: "staff"        },
  { label: "Equality Initiative",icon: "Equal",          href: "/equality-diversity",           group: "Compliance", module: "ri"           },
  { label: "Data Protection Record",icon: "Lock",        href: "/data-protection",              group: "Compliance", module: "ri"           },
  { label: "Environmental Risk Assessment",icon: "TreePine",href: "/environmental-risk",        group: "Team",       module: "buildings"    },
  { label: "YP Feedback Entry", icon: "MessageSquare",  href: "/yp-feedback",                  group: "Care",       module: "young-people" },
  { label: "Medication Error Report",icon: "Pill",       href: "/medication-errors",             group: "Care",       module: "young-people" },
  { label: "Room Search Record",icon: "Search",         href: "/room-searches",                group: "Care",       module: "safeguarding" },
  { label: "Transport Journey", icon: "Car",            href: "/transport-log",                 group: "Team",       module: "buildings"    },
  { label: "Trip / Holiday Plan",icon: "MapPin",        href: "/holiday-planning",              group: "Team",       module: "buildings"    },
  { label: "Behaviour Support Plan",icon: "Shield",     href: "/behaviour-support-plans",       group: "Care",       module: "young-people" },
  { label: "SW Contact Log",   icon: "Phone",          href: "/social-worker-contact",         group: "Care",       module: "young-people" },
  { label: "Duty Log Entry",   icon: "BookOpen",       href: "/duty-log",                      group: "Workflow",   module: "dashboard"    },
  { label: "Key Record",       icon: "Key",            href: "/keyholding-register",            group: "Team",       module: "buildings"    },
  { label: "After-Care Contact",icon: "Heart",         href: "/after-care",                     group: "Care",       module: "young-people" },
  { label: "Sleep-In Entry",   icon: "Moon",           href: "/sleep-in-log",                   group: "Team",       module: "staff"        },
  { label: "Device Agreement",icon: "Smartphone",     href: "/device-policy",                  group: "Care",       module: "young-people" },
  { label: "Health Check",    icon: "Stethoscope",    href: "/health-monitoring",              group: "Care",       module: "young-people" },
  { label: "Staff Reflection",icon: "Heart",          href: "/staff-reflections",              group: "Team",       module: "staff"        },
  { label: "Risk Mgmt Plan",  icon: "ShieldAlert",    href: "/risk-management-plans",          group: "Care",       module: "safeguarding" },
  { label: "Incident Review", icon: "FileSearch",     href: "/serious-incident-reviews",       group: "Compliance", module: "ri"           },
  { label: "Accident Record",icon: "HardHat",        href: "/accident-book",                  group: "Team",       module: "buildings"    },
  { label: "LADO Referral",  icon: "UserX",          href: "/lado-referrals",                 group: "Compliance", module: "ri"           },
  { label: "Water Hygiene Check",icon: "Droplets",   href: "/water-hygiene",                  group: "Team",       module: "buildings"    },
  { label: "Medication Audit",icon: "Pill",          href: "/medication-audit",               group: "Care",       module: "young-people" },
  { label: "Exploitation Screening",icon: "Shield",  href: "/exploitation-screening",         group: "Care",       module: "safeguarding" },
  { label: "Food Hygiene Check",icon: "UtensilsCrossed",href: "/food-hygiene",                group: "Team",       module: "buildings"    },
  { label: "Gift Record",     icon: "Gift",           href: "/gifts-register",                 group: "Care",       module: "young-people" },
  { label: "Photo Consent Review",icon: "Camera",     href: "/photo-consent",                  group: "Care",       module: "young-people" },
  { label: "Reg 44 Action",   icon: "ListChecks",     href: "/reg44-actions",                   group: "Compliance", module: "ri"           },
  { label: "Damage Report",   icon: "Hammer",         href: "/property-damage",                group: "Team",       module: "buildings"    },
  { label: "Med Competency",  icon: "GraduationCap",  href: "/medication-training",             group: "Team",       module: "training"     },
  { label: "Contextual Risk", icon: "MapPin",         href: "/contextual-safeguarding",         group: "Care",       module: "safeguarding" },
  { label: "YP Agreement",    icon: "FileText",       href: "/service-user-agreements",         group: "Care",       module: "young-people" },
  { label: "Lone Working Assessment",icon: "UserCheck",href: "/lone-working",                    group: "Team",       module: "staff"        },
  { label: "Prevent Referral",icon: "Shield",         href: "/prevent-duty",                    group: "Compliance", module: "ri"           },
  { label: "PM Transaction",  icon: "Wallet",         href: "/pocket-money-accounts",           group: "Care",       module: "young-people" },
  { label: "Complaint Outcome",icon: "MessageSquare", href: "/complaints-outcomes",             group: "Compliance", module: "ri"           },
  { label: "Emergency Contact",icon: "Phone",         href: "/emergency-contacts",              group: "Team",       module: "buildings"    },
  { label: "Infection Record",icon: "Bug",           href: "/infection-control",               group: "Team",       module: "buildings"    },
  { label: "Agency Shift",    icon: "Users",         href: "/agency-staff-log",                group: "Team",       module: "staff"        },
  { label: "Reg 35 Notification",icon: "Bell",       href: "/reg35-notifications",             group: "Compliance", module: "ri"           },
  { label: "Sickness Absence",icon: "UserMinus",     href: "/staff-sickness",                  group: "Team",       module: "staff"        },
  { label: "SAR / Data Request",icon: "Lock",        href: "/subject-access-requests",         group: "Compliance", module: "ri"           },
  { label: "Incident Debrief",icon: "Brain",        href: "/critical-incident-debrief",       group: "Compliance", module: "ri"           },
  { label: "CME Record",      icon: "GraduationCap",href: "/children-missing-education",      group: "Care",       module: "young-people" },
  { label: "Parent Contact",  icon: "Heart",        href: "/parent-partnership",              group: "Care",       module: "young-people" },
  { label: "Outcome Star",   icon: "Star",         href: "/outcome-star",                    group: "Care",       module: "young-people" },
  { label: "DoL Record",     icon: "Lock",         href: "/deprivation-of-liberty",          group: "Compliance", module: "ri"           },
  { label: "Utility Reading",icon: "Zap",          href: "/utility-monitoring",              group: "Team",       module: "buildings"    },
  { label: "Annual Review",  icon: "TrendingUp",   href: "/annual-development-reviews",      group: "Team",       module: "staff"        },
  { label: "PEP Entry",      icon: "GraduationCap",href: "/pep-tracker",                     group: "Care",       module: "young-people" },
  { label: "Exit Interview",icon: "LogOut",        href: "/staff-exit-interviews",            group: "Team",       module: "staff"        },
  { label: "Stock Check",   icon: "Pill",          href: "/medication-stock-check",           group: "Team",       module: "buildings"    },
  { label: "Improvement Objective",icon: "TrendingUp",href: "/home-improvement-plan",         group: "Compliance", module: "ri"           },
  { label: "Referral",       icon: "UserPlus",     href: "/referral-tracker",                 group: "Care",       module: "young-people" },
  { label: "Night Log Entry",icon: "Moon",          href: "/night-log",                        group: "Workflow",   module: "dashboard"    },
  { label: "Supervision Record",icon: "Network",   href: "/supervision-matrix",               group: "Team",       module: "staff"        },
  { label: "Staff Debrief",  icon: "Heart",        href: "/staff-debrief-log",                group: "Team",       module: "staff"        },
  { label: "Emergency Request",icon: "AlertTriangle",href: "/emergency-placements",            group: "Care",       module: "young-people" },
  { label: "Ofsted Action",  icon: "Award",        href: "/ofsted-action-plan",                group: "Compliance", module: "ri"           },
  { label: "Behaviour Entry",icon: "Activity",     href: "/behaviour-mapping",                 group: "Care",       module: "young-people" },
  { label: "Visitor Feedback",icon: "MessageSquare",href: "/visitors-feedback",                 group: "Team",       module: "buildings"    },
  { label: "Achievement",   icon: "Award",        href: "/positive-achievements",             group: "Care",       module: "young-people" },
  { label: "QA Audit Entry",icon: "ClipboardCheck",href: "/qa-audit",                          group: "Compliance", module: "ri"           },
  { label: "House Rule Amendment",icon: "BookOpen",href: "/house-rules",                       group: "Team",       module: "buildings"    },
  { label: "CPD Record",   icon: "BookOpen",      href: "/professional-development",           group: "Team",       module: "staff"        },
  { label: "Sleep Assessment",icon: "Moon",        href: "/sleep-assessments",                  group: "Care",       module: "young-people" },
  { label: "Return Interview",icon: "MapPin",     href: "/missing-return-interviews",          group: "Care",       module: "young-people" },
  { label: "Contact Plan",   icon: "Phone",       href: "/contact-plans",                      group: "Care",       module: "young-people" },
  { label: "Staffing Plan",  icon: "Users",       href: "/reg40-staffing-plan",                group: "Team",       module: "staff"        },
  { label: "Quality Review", icon: "Star",        href: "/quality-review-cycle",               group: "Compliance", module: "ri"           },
  { label: "Expiry Check",   icon: "Clock",       href: "/document-expiry-tracker",            group: "Compliance", module: "ri"           },
  { label: "Placement Impact",icon: "Scale",      href: "/placement-impact-assessment",        group: "Care",       module: "young-people" },
  { label: "Participation Entry",icon: "MessageCircle",href: "/child-participation-log",       group: "Care",       module: "young-people" },
  { label: "Policy Review",  icon: "FileText",    href: "/policy-review-tracker",              group: "Compliance", module: "ri"           },
  { label: "Handbook Sign-Off",icon: "FileCheck", href: "/staff-handbook-acknowledgements",    group: "Team",       module: "staff"        },
  { label: "Independence Review",icon: "TrendingUp",href: "/independence-pathway",             group: "Care",       module: "young-people" },
  { label: "Reg 44 Report",  icon: "Eye",         href: "/reg44-visitor-reports",              group: "Compliance", module: "ri"           },
  { label: "Welcome Pack",   icon: "Gift",        href: "/warm-welcome-packs",                group: "Team",       module: "buildings"    },
  { label: "Escalation",     icon: "ArrowUp",     href: "/escalation-tracker",                group: "Compliance", module: "ri"           },
  { label: "Safer Caring Plan",icon: "Shield",    href: "/staff-safer-caring",                group: "Team",       module: "staff"        },
  { label: "Care Model Review",icon: "Heart",     href: "/therapeutic-care-model",            group: "Team",       module: "staff"        },
  { label: "Notification",    icon: "Bell",      href: "/notification-log",                  group: "Compliance", module: "ri"           },
  { label: "Daily Routine",   icon: "Clock",     href: "/daily-routine-plans",               group: "Care",       module: "young-people" },
  { label: "Risk Appetite Review",icon: "Shield",href: "/risk-appetite-statement",           group: "Compliance", module: "ri"           },
  { label: "Stability Meeting",icon: "Users",    href: "/placement-stability-meetings",      group: "Care",       module: "young-people" },
  { label: "Self-Evaluation",  icon: "Award",    href: "/ofsted-self-evaluation",            group: "Compliance", module: "ri"           },
  { label: "Governance Meeting",icon: "ScrollText",href: "/governance-meeting-minutes",       group: "Compliance", module: "ri"           },
  { label: "Trauma Event",    icon: "Heart",     href: "/trauma-informed-timeline",           group: "Care",       module: "young-people" },
  { label: "Consequence Record",icon: "Heart",   href: "/consequence-framework",              group: "Care",       module: "young-people" },
  { label: "Network Contact", icon: "Network",   href: "/professional-network-map",           group: "Care",       module: "young-people" },
  { label: "Protocol Drill",  icon: "AlertOctagon",href: "/emergency-protocol-drills",        group: "Team",       module: "buildings"    },
  { label: "Comms Preference",icon: "MessageSquare",href: "/staff-communication-preferences",  group: "Team",       module: "staff"        },
  { label: "Pledge Review",   icon: "Heart",     href: "/children-pledges",                   group: "Care",       module: "young-people" },
  { label: "Unannounced Visit",icon: "Eye",      href: "/unannounced-visits-log",             group: "Compliance", module: "ri"           },
  { label: "Pre-Admission Checklist",icon: "FileCheck",href: "/pre-admission-checklist",      group: "Care",       module: "young-people" },
  { label: "Annual Outcome",  icon: "TrendingUp",href: "/annual-outcomes-report",             group: "Care",       module: "young-people" },
  { label: "Commissioner Feedback",icon: "MessageSquare",href: "/commissioning-feedback",       group: "Compliance", module: "ri"           },
  { label: "Community Activity",icon: "Globe",   href: "/community-engagement-log",            group: "Care",       module: "young-people" },
  { label: "Supervision Theme",icon: "Network", href: "/staff-supervision-themes",            group: "Team",       module: "staff"        },
  { label: "Safeguarding Supervision",icon: "Shield",href: "/safeguarding-supervision",         group: "Team",       module: "staff"        },
  { label: "Placement End Summary",icon: "Heart",href: "/placement-end-summary",                group: "Care",       module: "young-people" },
  { label: "CP Conference Record",icon: "Shield",href: "/child-protection-conferences",         group: "Care",       module: "safeguarding" },
  { label: "MAR Entry",       icon: "Pill",      href: "/mar-sheet",                             group: "Care",       module: "medication"   },
  { label: "Night Handover",  icon: "Moon",      href: "/night-staff-handover",                  group: "Workflow",   module: "staff"        },
  { label: "Trend Analysis",  icon: "BarChart3", href: "/incident-trend-analysis",               group: "Compliance", module: "ri"           },
  { label: "Child-Friendly Policy",icon: "BookOpen",href: "/child-friendly-policies",            group: "Care",       module: "young-people" },
  { label: "Attendance Entry",icon: "GraduationCap",href: "/education-attendance-tracker",        group: "Care",       module: "young-people" },
  { label: "Bedtime Routine", icon: "Moon",      href: "/bedtime-routines",                      group: "Care",       module: "young-people" },
  { label: "Recruitment Candidate",icon: "UserCheck",href: "/safer-recruitment-tracker",          group: "Team",       module: "recruitment"  },
  { label: "Fire Risk Item",  icon: "Flame",     href: "/fire-risk-assessment",                  group: "Team",       module: "buildings"    },
  { label: "Complaint Trend", icon: "TrendingUp",href: "/complaints-trend-analysis",              group: "Compliance", module: "ri"           },
  { label: "Wake-Up Plan",    icon: "Sun",       href: "/wake-up-routines",                      group: "Care",       module: "young-people" },
  { label: "Statutory Visit", icon: "Calendar",  href: "/statutory-visit-log",                   group: "Care",       module: "young-people" },
  { label: "Case File Audit", icon: "ClipboardCheck",href: "/case-file-audit",                    group: "Compliance", module: "ri"           },
  { label: "Shadow Shift",    icon: "Eye",       href: "/staff-shadowing-log",                   group: "Team",       module: "staff"        },
  { label: "Formulation",     icon: "Brain",     href: "/multi-disciplinary-formulation",         group: "Care",       module: "young-people" },
  { label: "Injury Record",   icon: "PersonStanding",href: "/child-injuries-log",                 group: "Care",       module: "young-people" },
  { label: "Placement Meeting",icon: "Users",     href: "/placement-meeting-minutes",             group: "Care",       module: "young-people" },
  { label: "WB Investigation",icon: "ShieldAlert",href: "/whistleblowing-investigations",          group: "Compliance", module: "ri"           },
  { label: "Safe Touch Plan", icon: "HandMetal", href: "/safe-touch-protocol",                   group: "Care",       module: "young-people" },
  { label: "Adoption Update", icon: "Heart",     href: "/adoption-support-records",              group: "Care",       module: "young-people" },
  { label: "Pathway Plan",    icon: "Milestone", href: "/pathway-plan-16plus",                    group: "Care",       module: "young-people" },
  { label: "Family Time Session",icon: "PhoneCall",href: "/family-time-supervision",              group: "Care",       module: "young-people" },
  { label: "Lone Working RA", icon: "UserCheck", href: "/lone-working-risk-assessment",          group: "Team",       module: "staff"        },
  { label: "Lesson Learned",  icon: "Lightbulb", href: "/lessons-learned-register",               group: "Compliance", module: "ri"           },
  { label: "Outcome Measure", icon: "Activity",  href: "/therapeutic-outcome-measures",          group: "Care",       module: "young-people" },
  { label: "Healthcare Plan", icon: "Stethoscope",href: "/healthcare-plans",                      group: "Care",       module: "young-people" },
  { label: "EHCP Update",     icon: "GraduationCap",href: "/ehcp-tracker",                         group: "Care",       module: "young-people" },
  { label: "Hate Incident",   icon: "ShieldAlert",href: "/hate-incident-log",                     group: "Compliance", module: "safeguarding" },
  { label: "External Visitor",icon: "Users",     href: "/external-visitor-log",                  group: "Team",       module: "buildings"    },
  { label: "Improvement Initiative",icon: "Target",href: "/service-improvement-board",            group: "Compliance", module: "ri"           },
  { label: "IRO Letter",      icon: "Mail",      href: "/iro-correspondence",                    group: "Care",       module: "young-people" },
  { label: "Passport Update", icon: "Sparkles",  href: "/personal-passport",                     group: "Care",       module: "young-people" },
  { label: "Resolution Meeting",icon: "MessageCircle",href: "/complaint-resolution-meetings",     group: "Compliance", module: "ri"           },
  { label: "Training Update", icon: "GraduationCap",href: "/mandatory-training-matrix",            group: "Team",       module: "training"     },
  { label: "Success Factor",  icon: "Star",      href: "/placement-success-factors",              group: "Compliance", module: "ri"           },
];
