export {
  generateDentalHealthMonitoringIntelligence,
  evaluateAppointmentCompliance,
  evaluateOralHygieneSupport,
  evaluateTreatmentCompliance,
  evaluateStaffDentalReadiness,
  buildChildDentalSummaries,
  pct,
  getRating,
  getAppointmentTypeLabel,
  getAppointmentOutcomeLabel,
  getOralHygieneRatingLabel,
  getTreatmentStatusLabel,
  getBrushingFrequencyLabel,
  getRatingLabel,
} from "./dental-health-monitoring-engine";

export type {
  AppointmentType,
  AppointmentOutcome,
  OralHygieneRating,
  TreatmentStatus,
  BrushingFrequency,
  Rating,
  DentalAppointment,
  OralHygieneRecord,
  DentalTreatmentPlan,
  StaffDentalTraining,
  AppointmentComplianceResult,
  OralHygieneSupportResult,
  TreatmentComplianceResult,
  StaffDentalReadinessResult,
  ChildDentalSummary,
  DentalHealthMonitoringIntelligence,
} from "./dental-health-monitoring-engine";
