-- ══════════════════════════════════════════════════════════════════════════════
-- CORNERSTONE — ARIA UNIVERSAL LAYER
-- Migration 013: aria_requests, aria_outputs, aria_approvals, aria_audit_events,
--                aria_transcriptions, aria_task_links
--
-- The universal Aria layer sits underneath every Aria-driven feature. The
-- domain-specific tables (oversight_reviews, voice_summaries, hr_process_
-- guardian_reviews, hr_letters) keep their own state, but every Aria request,
-- response, transcription and approval also writes here, so audit logs and
-- inspection reports can be assembled from one place.
--
-- All tables are RLS-enabled and append-only where audit integrity matters.
-- Service role has full access. Authenticated users can read their own
-- drafts and any record where the application layer grants visibility via
-- src/lib/aria/aria-permissions.ts.
-- ══════════════════════════════════════════════════════════════════════════════

create or replace function set_updated_at_aria()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- ── aria_requests ────────────────────────────────────────────────────────────
-- Every Aria invocation writes one row here. This is the front door.

create table if not exists aria_requests (
  id                  text primary key,
  organisation_id     text,
  home_id             text,
  child_id            text,
  staff_id            text,
  source_module       text,
  source_record_type  text,
  source_record_id    text,
  command_id          text not null,
  user_id             text not null,
  user_role           text,
  input_text          text,
  input_metadata      jsonb not null default '{}',
  status              text not null default 'created' check (status in (
                        'created','context_built','provider_called','provider_failed',
                        'permission_denied','complete'
                      )),
  llm_used            boolean not null default false,
  provider_id         text,
  model_id            text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists idx_aria_requests_command on aria_requests(command_id);
create index if not exists idx_aria_requests_user on aria_requests(user_id);
create index if not exists idx_aria_requests_home on aria_requests(home_id);
create index if not exists idx_aria_requests_child on aria_requests(child_id);
create index if not exists idx_aria_requests_status on aria_requests(status);
create index if not exists idx_aria_requests_source on aria_requests(source_module, source_record_id);
drop trigger if exists trg_aria_requests_updated_at on aria_requests;
create trigger trg_aria_requests_updated_at
  before update on aria_requests
  for each row execute function set_updated_at_aria();

-- ── aria_outputs ─────────────────────────────────────────────────────────────
-- The draft generated by Aria for the request, plus the manager's edits.

create table if not exists aria_outputs (
  id                      text primary key,
  request_id              text not null references aria_requests(id) on delete cascade,
  generated_text          text not null,
  structured_output       jsonb not null default '{}',
  edited_text             text,
  approval_required       boolean not null default true,
  status                  text not null default 'draft' check (status in (
                            'draft','edited','submitted_for_approval','approved',
                            'committed','rejected','archived'
                          )),
  confidence              text not null default 'medium' check (confidence in ('low','medium','high')),
  approved_by             text,
  approved_at             timestamptz,
  rejected_by             text,
  rejected_at             timestamptz,
  rejection_reason        text,
  committed_record_type   text,
  committed_record_id     text,
  redacted_context_summary text,
  context_record_ids      jsonb not null default '[]',
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

create index if not exists idx_aria_outputs_request on aria_outputs(request_id);
create index if not exists idx_aria_outputs_status on aria_outputs(status);
drop trigger if exists trg_aria_outputs_updated_at on aria_outputs;
create trigger trg_aria_outputs_updated_at
  before update on aria_outputs
  for each row execute function set_updated_at_aria();

-- ── aria_approvals ───────────────────────────────────────────────────────────
-- Append-only approval / rejection trail per output. One row per decision.

create table if not exists aria_approvals (
  id              text primary key,
  output_id       text not null references aria_outputs(id) on delete cascade,
  decision        text not null check (decision in (
                    'approve','reject','request_changes','commit','withdraw'
                  )),
  decided_by      text not null,
  decided_role    text,
  decision_text   text,
  decided_at      timestamptz not null default now()
);

create index if not exists idx_aria_approvals_output on aria_approvals(output_id);
create index if not exists idx_aria_approvals_decided_by on aria_approvals(decided_by);

-- ── aria_audit_events ───────────────────────────────────────────────────────
-- Append-only event stream covering everything Aria touches.

create table if not exists aria_audit_events (
  id              text primary key,
  request_id      text references aria_requests(id) on delete cascade,
  output_id       text references aria_outputs(id) on delete cascade,
  actor_user_id   text,
  actor_role      text,
  event_type      text not null check (event_type in (
                    'generated','edited','submitted_for_approval','approved','rejected',
                    'committed','transcribed','copied_to_field','task_created',
                    'context_viewed','failed','permission_denied','withdrawn'
                  )),
  event_detail    jsonb not null default '{}',
  ip_address      text,
  user_agent      text,
  created_at      timestamptz not null default now()
);

create index if not exists idx_aria_audit_request on aria_audit_events(request_id);
create index if not exists idx_aria_audit_output on aria_audit_events(output_id);
create index if not exists idx_aria_audit_actor on aria_audit_events(actor_user_id);
create index if not exists idx_aria_audit_event on aria_audit_events(event_type);
create index if not exists idx_aria_audit_created on aria_audit_events(created_at);

-- ── aria_transcriptions ──────────────────────────────────────────────────────
-- Voice dictation transcripts. Audio is discarded after transcription unless
-- a lawful audio-storage pattern is configured at deployment.

create table if not exists aria_transcriptions (
  id              text primary key,
  user_id         text not null,
  organisation_id text,
  home_id         text,
  source_module   text,
  source_field    text,
  duration_ms     integer,
  bytes           integer,
  mime_type       text,
  transcript_text text not null,
  provider_id     text,
  model_id        text,
  status          text not null default 'complete' check (status in ('complete','failed')),
  error_detail    text,
  inserted_into_field boolean not null default false,
  used_in_request_id text references aria_requests(id) on delete set null,
  created_at      timestamptz not null default now()
);

create index if not exists idx_aria_transcriptions_user on aria_transcriptions(user_id);
create index if not exists idx_aria_transcriptions_request on aria_transcriptions(used_in_request_id);

-- ── aria_task_links ──────────────────────────────────────────────────────────
-- Maps an Aria output to any tasks created from it across the platform.

create table if not exists aria_task_links (
  id              text primary key,
  output_id       text not null references aria_outputs(id) on delete cascade,
  task_module     text not null,
  task_id         text not null,
  origin          text not null default 'aria_suggested' check (origin in (
                    'aria_suggested','aria_approved','manual_promotion'
                  )),
  created_by      text,
  created_at      timestamptz not null default now()
);

create index if not exists idx_aria_task_links_output on aria_task_links(output_id);
create index if not exists idx_aria_task_links_task on aria_task_links(task_module, task_id);

-- ══════════════════════════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY
-- ══════════════════════════════════════════════════════════════════════════════

do $$
declare t text;
begin
  for t in select unnest(array[
    'aria_requests','aria_outputs','aria_approvals','aria_audit_events',
    'aria_transcriptions','aria_task_links'
  ]) loop
    execute format('alter table %I enable row level security', t);
    execute format(
      'create policy %I on %I for all to service_role using (true) with check (true)',
      'service_role_full_access_' || t, t
    );
    execute format(
      'create policy %I on %I for select to authenticated using (true)',
      'authenticated_read_' || t, t
    );
  end loop;
exception when duplicate_object then
  null;
end $$;

-- ══════════════════════════════════════════════════════════════════════════════
-- COMMENTS
-- ══════════════════════════════════════════════════════════════════════════════

comment on table aria_requests is 'Every Aria invocation. The front door for the universal Aria layer.';
comment on table aria_outputs is 'Drafts generated by Aria. Always require approval before commit. Edited text is stored separately from generated text.';
comment on table aria_approvals is 'Append-only decision trail per output. One row per approve / reject / request_changes / commit / withdraw.';
comment on table aria_audit_events is 'Append-only audit stream across the universal Aria layer. Inspector-ready.';
comment on table aria_transcriptions is 'Voice dictation transcripts. Audio is discarded after transcription unless explicitly configured for storage.';
comment on table aria_task_links is 'Links an Aria output to any tasks promoted from it across the platform.';
comment on column aria_outputs.confidence is 'low / medium / high. Engine and Aria service must not declare high confidence on safeguarding-, HR-, or legal-sensitive material unless source evidence is unambiguous.';
