-- ══════════════════════════════════════════════════════════════════════════════
-- CORNERSTONE — ARIA V1 SUGGESTIONS
-- Migration 014: aria_suggestions, aria_suggestion_links, aria_suggestion_audit
--
-- The proactive suggestion layer. Unlike aria_outputs (which are request-
-- response), suggestions are generated by Aria when it identifies something
-- a manager should review — an incident needing oversight, a risk assessment
-- that may be out of date, a child whose voice is missing from the records.
--
-- Every suggestion requires human review before any action is taken.
-- ══════════════════════════════════════════════════════════════════════════════

-- ── aria_suggestions ────────────────────────────────────────────────────────

create table if not exists aria_suggestions (
  id                    text primary key,
  organisation_id       text,
  home_id               text,
  child_id              text,
  staff_id              text,
  related_record_type   text not null,
  related_record_id     text,
  suggestion_type       text not null check (suggestion_type in (
                          'management_oversight','risk_review','plan_review',
                          'behaviour_support_review','key_work','safeguarding_review',
                          'staff_debrief','notification','task',
                          'linked_record_review','handover_update','incident_analysis'
                        )),
  title                 text not null,
  summary               text,
  reason                text,
  suggested_action      text,
  draft_text            text,
  final_text            text,
  risk_level            text not null default 'medium' check (risk_level in (
                          'urgent','high','medium','low'
                        )),
  confidence_level      text not null default 'medium' check (confidence_level in (
                          'low','medium','high'
                        )),
  status                text not null default 'awaiting_review' check (status in (
                          'draft','awaiting_review','approved','amended_and_approved',
                          'rejected','no_action_required','committed','archived'
                        )),
  requires_approval     boolean not null default true,
  reviewer_role         text,
  created_by            text,
  reviewed_by           text,
  approved_by           text,
  rejected_by           text,
  committed_by          text,
  rejection_reason      text,
  ai_provider           text,
  mock_mode             boolean not null default false,
  created_at            timestamptz not null default now(),
  reviewed_at           timestamptz,
  approved_at           timestamptz,
  rejected_at           timestamptz,
  committed_at          timestamptz,
  updated_at            timestamptz not null default now()
);

create index if not exists idx_aria_suggestions_status on aria_suggestions(status);
create index if not exists idx_aria_suggestions_record_type on aria_suggestions(related_record_type);
create index if not exists idx_aria_suggestions_record_id on aria_suggestions(related_record_id);
create index if not exists idx_aria_suggestions_child on aria_suggestions(child_id);
create index if not exists idx_aria_suggestions_home on aria_suggestions(home_id);
create index if not exists idx_aria_suggestions_risk on aria_suggestions(risk_level);
create index if not exists idx_aria_suggestions_type on aria_suggestions(suggestion_type);
create index if not exists idx_aria_suggestions_created on aria_suggestions(created_at);

drop trigger if exists trg_aria_suggestions_updated_at on aria_suggestions;
create trigger trg_aria_suggestions_updated_at
  before update on aria_suggestions
  for each row execute function set_updated_at_aria();

-- ── aria_suggestion_links ───────────────────────────────────────────────────

create table if not exists aria_suggestion_links (
  id                    text primary key,
  suggestion_id         text not null references aria_suggestions(id) on delete cascade,
  linked_record_type    text not null,
  linked_record_id      text,
  relationship_type     text,
  reason                text,
  suggested_action      text,
  risk_level            text,
  requires_approval     boolean default true,
  created_at            timestamptz not null default now()
);

create index if not exists idx_aria_suggestion_links_suggestion on aria_suggestion_links(suggestion_id);
create index if not exists idx_aria_suggestion_links_type on aria_suggestion_links(linked_record_type);

-- ── aria_suggestion_audit ───────────────────────────────────────────────────

create table if not exists aria_suggestion_audit (
  id                    text primary key,
  organisation_id       text,
  home_id               text,
  suggestion_id         text references aria_suggestions(id) on delete set null,
  actor_user_id         text,
  actor_role            text,
  action                text not null check (action in (
                          'suggestion_created','suggestion_viewed','draft_generated',
                          'draft_edited','suggestion_approved','suggestion_rejected',
                          'suggestion_no_action','suggestion_committed','task_created',
                          'linked_records_suggested','ai_provider_called',
                          'mock_mode_used','error'
                        )),
  before_state          jsonb,
  after_state           jsonb,
  metadata              jsonb,
  created_at            timestamptz not null default now()
);

create index if not exists idx_aria_suggestion_audit_suggestion on aria_suggestion_audit(suggestion_id);
create index if not exists idx_aria_suggestion_audit_created on aria_suggestion_audit(created_at);
create index if not exists idx_aria_suggestion_audit_action on aria_suggestion_audit(action);
create index if not exists idx_aria_suggestion_audit_actor on aria_suggestion_audit(actor_user_id);

-- ══════════════════════════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY
-- ══════════════════════════════════════════════════════════════════════════════

do $$
declare t text;
begin
  for t in select unnest(array[
    'aria_suggestions','aria_suggestion_links','aria_suggestion_audit'
  ]) loop
    execute format('alter table %I enable row level security', t);

    execute format(
      'create policy if not exists %I on %I for all to service_role using (true) with check (true)',
      t || '_service_all', t
    );

    execute format(
      'create policy if not exists %I on %I for select to authenticated using (true)',
      t || '_auth_read', t
    );
  end loop;
end
$$;
