-- ══════════════════════════════════════════════════════════════════════════════
-- CORNERSTONE INTELLIGENCE LAYER — SEED DATA
-- Migration 017
--
-- Seeds the intelligence tables with realistic demo data for Oak House.
-- Matches the UI demo data so that when Supabase is enabled the pages
-- display the same content.
-- ══════════════════════════════════════════════════════════════════════════════

\set HOME_ID         'a0000000-0000-0000-0000-000000000001'
\set CHILD_A         'c0000000-0000-0000-0000-000000000001'
\set CHILD_B         'c0000000-0000-0000-0000-000000000002'
\set CHILD_C         'c0000000-0000-0000-0000-000000000003'
\set STAFF_DARREN    'b0000000-0000-0000-0000-000000000001'
\set STAFF_SARAH     'b0000000-0000-0000-0000-000000000010'
\set STAFF_TOM       'b0000000-0000-0000-0000-000000000011'
\set STAFF_JAMES     'b0000000-0000-0000-0000-000000000012'

-- ── 1. Manager Attention Items ────────────────────────────────────────────────

INSERT INTO manager_attention_items (id, home_id, title, category, urgency, child_id, source_record_type, reason, suggested_action, due_date, status, created_by, created_at) VALUES
  ('d0000001-0000-0000-0000-000000000001', :'HOME_ID', 'Incident: Physical intervention — Child A', 'incident_oversight', 'high', :'CHILD_A', 'incident', 'A physical intervention was recorded yesterday involving Child A. Manager oversight and sign-off required within 24 hours.', 'Review the incident record, ensure body map completed, check debrief planned, sign off or escalate.', current_date, 'open', :'STAFF_DARREN', now() - interval '6 hours'),
  ('d0000001-0000-0000-0000-000000000002', :'HOME_ID', 'Missing from Care: Child B — Return interview overdue', 'missing_from_care', 'critical', :'CHILD_B', 'missing_episode', 'Child B returned from a missing episode 48 hours ago. The independent return interview has not been completed.', 'Arrange independent return interview within 72 hours. Notify placing authority if not completed.', current_date - 1, 'open', :'STAFF_DARREN', now() - interval '48 hours'),
  ('d0000001-0000-0000-0000-000000000003', :'HOME_ID', 'Medication discrepancy — Child A controlled drug count', 'medication_check', 'critical', :'CHILD_A', 'medication_audit', 'The weekly medication count for Child A shows a discrepancy of 2 tablets of prescribed medication.', 'Investigate immediately. Check MAR sheet, stock records, and staff on duty during period.', current_date, 'open', :'STAFF_DARREN', now() - interval '3 hours'),
  ('d0000001-0000-0000-0000-000000000004', :'HOME_ID', 'Supervision overdue: Staff Member B — 7 weeks', 'supervision_overdue', 'high', NULL, 'supervision_tracker', 'Staff Member B has not had formal supervision for 7 weeks. The home commits to supervision every 4 weeks.', 'Schedule supervision within this week. Document reason for delay.', current_date + 3, 'open', :'STAFF_DARREN', now() - interval '2 days'),
  ('d0000001-0000-0000-0000-000000000005', :'HOME_ID', 'Reg 44 Action: Fire drill frequency not met', 'reg44_action_overdue', 'medium', NULL, 'reg44_action', 'The Reg 44 visitor noted that only 1 fire drill was conducted in the last quarter (requirement is monthly).', 'Schedule 2 fire drills this month. Update fire drill log.', current_date + 7, 'in_progress', :'STAFF_DARREN', now() - interval '5 days'),
  ('d0000001-0000-0000-0000-000000000006', :'HOME_ID', 'Training gap: Safeguarding Level 3 renewal — 3 staff', 'training_gap', 'medium', NULL, 'training_matrix', 'Three staff members have safeguarding Level 3 training expiring within 30 days.', 'Book refresher training. Check available dates with training provider.', current_date + 14, 'open', :'STAFF_DARREN', now() - interval '7 days');

-- ── 2. Child Voice Entries ────────────────────────────────────────────────────

INSERT INTO child_voice_entries (id, child_id, home_id, entry_date, category, child_words, summary, action_taken, staff_response, created_by, created_at) VALUES
  ('e0000001-0000-0000-0000-000000000001', :'CHILD_A', :'HOME_ID', current_date - 1, 'wishes_and_feelings', 'I want to see my nan more. She always makes me feel calm and I miss her Sunday dinners.', 'Child expressed wish for increased contact with maternal grandmother.', 'Contact schedule reviewed. Additional fortnightly face-to-face visit arranged alongside weekly video calls.', 'We hear you. We have arranged an extra visit with your nan every two weeks. Would you like to help plan what you do together?', :'STAFF_SARAH', now() - interval '1 day'),
  ('e0000001-0000-0000-0000-000000000002', :'CHILD_A', :'HOME_ID', current_date - 3, 'food', 'The food has been really good this week. I loved the pasta bake on Tuesday.', 'Positive feedback about meals this week.', 'Recipe added to regular rotation. Child invited to help cook next week.', 'That is great to hear! We will make sure we have pasta bake regularly. Would you like to help make it next Tuesday?', :'STAFF_TOM', now() - interval '3 days'),
  ('e0000001-0000-0000-0000-000000000003', :'CHILD_B', :'HOME_ID', current_date - 5, 'safety', 'I feel safe here now. I did not feel safe at my last place but here the staff actually listen.', 'Child expressed feeling safe at current placement. Positive comparison to previous placement.', 'Recorded as positive outcome. Shared with social worker (with consent). Discussed what makes them feel safe to inform practice.', 'We are so glad you feel safe here. That is really important to us. We will always listen to you.', :'STAFF_SARAH', now() - interval '5 days'),
  ('e0000001-0000-0000-0000-000000000004', :'CHILD_B', :'HOME_ID', current_date - 8, 'activity', 'Can we go swimming more? I used to go with my dad and it makes me feel happy.', 'Request for more swimming. Connection to positive memories with father.', 'Weekly swimming session arranged at local pool. Exploring whether father contact could include swimming as shared activity.', 'We would love to take you swimming more. How about every Saturday morning?', :'STAFF_JAMES', now() - interval '8 days'),
  ('e0000001-0000-0000-0000-000000000005', :'CHILD_C', :'HOME_ID', current_date - 10, 'complaint', 'I do not like being told to go to bed so early. None of my friends have to be in bed by nine.', 'Complaint about bedtime. Child feels it is too early compared to peers.', 'Bedtime reviewed in consultation with child. Agreed 9:30pm on school nights, 10pm on weekends.', 'We have heard your views and we have adjusted your bedtime. You can read in your room from 9pm.', :'STAFF_SARAH', now() - interval '10 days');

-- ── 3. Child Progress Goals ───────────────────────────────────────────────────

INSERT INTO child_progress_goals (id, child_id, home_id, goal_area, title, description, status, target_date, created_by, created_at) VALUES
  ('f0000001-0000-0000-0000-000000000001', :'CHILD_A', :'HOME_ID', 'education', 'Improve maths attainment to age-related expectations', 'Working with tutor twice weekly. Target to move from working towards to at expected standard.', 'active', current_date + 90, :'STAFF_DARREN', now() - interval '30 days'),
  ('f0000001-0000-0000-0000-000000000002', :'CHILD_A', :'HOME_ID', 'emotional_wellbeing', 'Develop self-regulation strategies', 'Working with therapist on identifying triggers and building coping toolkit. Using zones of regulation.', 'active', current_date + 60, :'STAFF_DARREN', now() - interval '45 days'),
  ('f0000001-0000-0000-0000-000000000003', :'CHILD_B', :'HOME_ID', 'relationships', 'Build trusting relationships with 2+ staff', 'Child has history of placement breakdowns linked to relationship difficulties with carers.', 'active', current_date + 120, :'STAFF_DARREN', now() - interval '20 days'),
  ('f0000001-0000-0000-0000-000000000004', :'CHILD_C', :'HOME_ID', 'independence', 'Develop independent living skills (cooking, budgeting)', 'Aged 16, preparing for semi-independence. Weekly cooking sessions and monthly budget management.', 'active', current_date + 180, :'STAFF_DARREN', now() - interval '60 days');

-- ── 4. Reg 44 Visits ──────────────────────────────────────────────────────────

INSERT INTO reg44_visits (id, home_id, visit_date, visitor_name, report_status, summary, strengths, concerns, children_views_summary, staff_views_summary, manager_response, created_by, created_at) VALUES
  ('g0000001-0000-0000-0000-000000000001', :'HOME_ID', current_date - 14, 'Margaret Okonkwo', 'reviewed', 'Monthly Regulation 44 visit. Home observed to be warm, well-maintained and child-focused. Children appeared settled and engaged in activities.', 'Excellent child voice practice — visible evidence of children shaping their environment. Staff interactions warm and playful. Strong evidence of key work records.', 'Fire drill frequency below expectation (1 in last quarter, 3 required). One supervision record past due.', 'Children spoke positively about staff and activities. One child expressed wish for more swimming.', 'Staff feel well supported. Raised concern about agency staff cover during sickness.', 'Fire drill schedule updated to ensure monthly frequency. Supervision scheduled for this week.', :'STAFF_DARREN', now() - interval '14 days'),
  ('g0000001-0000-0000-0000-000000000002', :'HOME_ID', current_date - 44, 'Margaret Okonkwo', 'closed', 'Routine monthly visit. All statutory requirements met. Children settled. Admissions process for new child well-managed.', 'Admissions process exemplary — matching panel evidence strong. Children prepared well for new arrival. Warm welcome pack provided.', NULL, 'Children welcoming of new placement. Existing children involved in showing new child around.', 'Staff spoke positively about admissions training received.', NULL, :'STAFF_DARREN', now() - interval '44 days'),
  ('g0000001-0000-0000-0000-000000000003', :'HOME_ID', current_date - 75, 'Margaret Okonkwo', 'closed', 'Monthly visit. Home undergoing refurbishment of second bathroom. Minor disruption managed well. Children consulted on decoration choices.', 'Children genuinely consulted on decoration. Budget allocated for bedroom personalisation. Strong evidence of child participation.', 'Temporary loss of one bathroom causing some morning routine delays. Risk assessment for building work not filed in expected location.', 'Children excited about new bathroom. Expressed preference for colours used.', 'Staff managed building disruption professionally. Good communication with children about timelines.', 'Risk assessment now filed correctly. Morning routine adjusted temporarily.', :'STAFF_DARREN', now() - interval '75 days');

-- ── 5. Reg 45 Reviews ─────────────────────────────────────────────────────────

INSERT INTO reg45_reviews (id, home_id, period_start, period_end, status, quality_of_care_summary, children_experiences_summary, safeguarding_summary, leadership_summary, strengths, improvement_actions, created_at) VALUES
  ('h0000001-0000-0000-0000-000000000001', :'HOME_ID', current_date - 180, current_date, 'draft', 'Quality of care rated as good across all ILACS domains. Evidence of strong relational practice and child-centred approach.', 'Children report feeling safe, listened to, and cared for. Voice of the child practice is embedded and evidenced throughout records.', 'No safeguarding referrals in period. Safer recruitment fully compliant. All staff DBS current.', 'Leadership stable. Manager in post for 18 months. Strong oversight evidenced through daily log review and supervision records.', 'Child voice practice, relational approach, stability of staffing', 'Fire drill frequency, agency staff induction records, medication audit trail', now() - interval '7 days'),
  ('h0000001-0000-0000-0000-000000000002', :'HOME_ID', current_date - 365, current_date - 180, 'approved', 'Good quality of care demonstrated across the review period. Placement stability at 100%.', 'All children report positive experiences. Progress tracked through outcome stars showing improvement in 5/7 areas.', 'One safeguarding referral made appropriately. Response and follow-up evidenced.', 'Leadership effective. Good partnership working with placing authorities.', 'Placement stability, outcome tracking, partnership working', 'Voice of child recording consistency, Reg 44 action follow-up timeliness', now() - interval '187 days');

-- ── 6. Staff Competence Records ───────────────────────────────────────────────

INSERT INTO staff_competence_records (id, staff_id, home_id, safer_recruitment_complete, dbs_status, dbs_date, dbs_update_service, references_received, reference_count, right_to_work, induction_complete, induction_date, probation_status, level3_status, mandatory_training_complete, safeguarding_training_date, medication_competency, medication_competency_date, physical_intervention_trained, physical_intervention_date, last_supervision_date, supervision_frequency_weeks, last_appraisal_date, can_lead_shift, can_administer_medication, can_lone_work, can_supervise_others, created_by, created_at) VALUES
  ('i0000001-0000-0000-0000-000000000001', :'STAFF_SARAH', :'HOME_ID', true, 'current', current_date - 400, true, true, 3, true, true, current_date - 500, 'passed', 'achieved', true, current_date - 60, true, current_date - 90, true, current_date - 120, current_date - 14, 4, current_date - 150, true, true, true, true, :'STAFF_DARREN', now() - interval '500 days'),
  ('i0000001-0000-0000-0000-000000000002', :'STAFF_TOM', :'HOME_ID', true, 'current', current_date - 300, false, true, 2, true, true, current_date - 365, 'passed', 'in_progress', true, current_date - 45, true, current_date - 60, true, current_date - 90, current_date - 28, 4, current_date - 200, true, true, false, false, :'STAFF_DARREN', now() - interval '365 days'),
  ('i0000001-0000-0000-0000-000000000003', :'STAFF_JAMES', :'HOME_ID', true, 'current', current_date - 200, true, true, 2, true, true, current_date - 240, 'passed', 'enrolled', false, current_date - 330, false, NULL, true, current_date - 80, current_date - 42, 4, NULL, false, false, true, false, :'STAFF_DARREN', now() - interval '240 days');

-- ── 7. Inspection Evidence Items ──────────────────────────────────────────────

INSERT INTO inspection_evidence_items (id, home_id, child_id, source_type, title, summary, evidence_category, judgement_area, confidence_score, evidence_date, created_by, created_at) VALUES
  ('j0000001-0000-0000-0000-000000000001', :'HOME_ID', :'CHILD_A', 'key_work', 'Key Work Session — Wishes and Feelings Discussion', 'Structured key work session exploring child wishes around family contact. Direct quotes captured. Actions arising documented and followed through.', 'wishes_and_feelings', 'overall_experiences_and_progress', 92, current_date - 7, :'STAFF_SARAH', now() - interval '7 days'),
  ('j0000001-0000-0000-0000-000000000002', :'HOME_ID', :'CHILD_B', 'incident', 'Incident Response — Missing Episode Follow-up', 'Full return home interview completed. Risk assessment updated. Strategy discussion held with SW. Child voice captured on return.', 'missing_from_care', 'help_and_protection', 85, current_date - 14, :'STAFF_DARREN', now() - interval '14 days'),
  ('j0000001-0000-0000-0000-000000000003', :'HOME_ID', NULL, 'supervision', 'Supervision Record — Reflective Practice Discussion', 'Supervision exploring staff response to recent challenging behaviour. Reflective model used. Learning captured and shared with team.', 'staff_supervision', 'effectiveness_of_leaders', 78, current_date - 10, :'STAFF_DARREN', now() - interval '10 days'),
  ('j0000001-0000-0000-0000-000000000004', :'HOME_ID', :'CHILD_A', 'daily_log', 'Daily Log — Child Engagement in Education', 'Positive school report shared. Child achieving expected standard in English. Tutor feedback positive. Child expressed pride in progress.', 'education', 'overall_experiences_and_progress', 88, current_date - 3, :'STAFF_TOM', now() - interval '3 days'),
  ('j0000001-0000-0000-0000-000000000005', :'HOME_ID', NULL, 'risk_assessment', 'Updated Risk Assessment — Community Safety', 'Risk assessment updated following locality risk review. New mitigations identified. Staff briefed. Children involved in safety planning age-appropriately.', 'risk_assessment', 'help_and_protection', 90, current_date - 5, :'STAFF_DARREN', now() - interval '5 days'),
  ('j0000001-0000-0000-0000-000000000006', :'HOME_ID', NULL, 'reg44_report', 'Regulation 44 Visit Report — April 2026', 'Independent visitor confirmed good practice. Strengths in child voice and relational approach. One area for development: fire drill frequency.', 'regulation_44', 'effectiveness_of_leaders', 95, current_date - 14, :'STAFF_DARREN', now() - interval '14 days'),
  ('j0000001-0000-0000-0000-000000000007', :'HOME_ID', :'CHILD_C', 'child_voice', 'Voice of the Child — House Meeting Minutes', 'Children proposed and voted on Friday Movie Night. Democratic process evidenced. All children participated. Outcome implemented within one week.', 'wishes_and_feelings', 'overall_experiences_and_progress', 94, current_date - 12, :'STAFF_SARAH', now() - interval '12 days'),
  ('j0000001-0000-0000-0000-000000000008', :'HOME_ID', :'CHILD_B', 'risk_assessment', 'Child-Specific Risk Assessment — Contextual Safeguarding', 'CSE risk assessment reviewed. No escalation required. Protective factors strengthened. Child engaging with safety planning.', 'safeguarding', 'help_and_protection', 82, current_date - 20, :'STAFF_DARREN', now() - interval '20 days'),
  ('j0000001-0000-0000-0000-000000000009', :'HOME_ID', NULL, 'training_record', 'Team Training — Trauma-Informed Practice (CPD)', 'Whole team attended trauma-informed practice refresher. Reflective exercise on applying theory to current children. Action plans created.', 'training', 'effectiveness_of_leaders', 75, current_date - 21, :'STAFF_DARREN', now() - interval '21 days'),
  ('j0000001-0000-0000-0000-000000000010', :'HOME_ID', :'CHILD_A', 'placement_plan', 'Placement Plan Review — Education Focus', 'Placement plan updated following positive PEP. New educational targets agreed. SENCO input incorporated. Child aspirations discussed and recorded.', 'placement_planning', 'overall_experiences_and_progress', 87, current_date - 9, :'STAFF_DARREN', now() - interval '9 days');

-- ── 8. Incident Learning Reviews ──────────────────────────────────────────────

INSERT INTO incident_learning_reviews (id, incident_id, home_id, child_id, review_status, manager_oversight, trigger_analysis, what_worked, learning_summary, staff_debrief_required, child_keywork_required, created_by, created_at) VALUES
  ('k0000001-0000-0000-0000-000000000001', 'd0000001-0000-0000-0000-000000000001', :'HOME_ID', :'CHILD_A', 'required', NULL, NULL, NULL, NULL, true, true, :'STAFF_DARREN', now() - interval '6 hours'),
  ('k0000001-0000-0000-0000-000000000002', 'k0000002-0000-0000-0000-000000000001', :'HOME_ID', :'CHILD_B', 'completed', 'Reviewed and approved. De-escalation worked well. No repeat expected.', 'Transition from preferred activity triggered frustration. Pattern of difficulty with transitions noted.', 'Staff maintained calm tone. Used distraction technique effectively. Child responded to 5-minute warning approach.', 'Transitions remain a trigger. 5-minute warnings should be standard practice. Team briefed.', false, true, :'STAFF_DARREN', now() - interval '14 days');

-- ── 9. Provider Home Summaries ────────────────────────────────────────────────

INSERT INTO provider_home_summaries (id, home_id, period_start, period_end, inspection_readiness_score, open_risks_count, serious_incidents_count, reg44_status, reg45_status, overdue_actions_count, supervision_compliance_pct, training_compliance_pct, complaints_open, missing_episodes, created_at) VALUES
  ('l0000001-0000-0000-0000-000000000001', :'HOME_ID', current_date - 30, current_date, 82, 2, 0, 'current', 'draft', 1, 85, 90, 0, 1, now() - interval '1 day');

-- ── 10. Smart Record Links (auto-generated examples) ──────────────────────────

INSERT INTO smart_record_links (id, home_id, source_type, source_id, target_type, target_id, relationship, suggested_by, created_by, created_at) VALUES
  ('m0000001-0000-0000-0000-000000000001', :'HOME_ID', 'incident', 'd0000001-0000-0000-0000-000000000001', 'child_profile', :'CHILD_A', 'involves_child', 'system', :'STAFF_DARREN', now() - interval '6 hours'),
  ('m0000001-0000-0000-0000-000000000002', :'HOME_ID', 'reg44_visit', 'g0000001-0000-0000-0000-000000000001', 'inspection_evidence', 'j0000001-0000-0000-0000-000000000006', 'evidence_item', 'system', :'STAFF_DARREN', now() - interval '14 days'),
  ('m0000001-0000-0000-0000-000000000003', :'HOME_ID', 'child_voice', 'e0000001-0000-0000-0000-000000000001', 'child_progress', 'f0000001-0000-0000-0000-000000000002', 'evidence_of_progress', 'user', :'STAFF_SARAH', now() - interval '1 day');
